/**
 * altgallery, jQuery Plugin
 *
 * @version 0.4.6-120301
 * @copyright 2011-2012 Flash-Gallery.com
 */

jQuery.effects||function(c,r){function M(h){var a;return h&&h.constructor==Array&&3==h.length?h:(a=/rgb\(\s*([0-9]{1,3})\s*,\s*([0-9]{1,3})\s*,\s*([0-9]{1,3})\s*\)/.exec(h))?[parseInt(a[1],10),parseInt(a[2],10),parseInt(a[3],10)]:(a=/rgb\(\s*([0-9]+(?:\.[0-9]+)?)\%\s*,\s*([0-9]+(?:\.[0-9]+)?)\%\s*,\s*([0-9]+(?:\.[0-9]+)?)\%\s*\)/.exec(h))?[2.55*parseFloat(a[1]),2.55*parseFloat(a[2]),2.55*parseFloat(a[3])]:(a=/#([a-fA-F0-9]{2})([a-fA-F0-9]{2})([a-fA-F0-9]{2})/.exec(h))?[parseInt(a[1],16),parseInt(a[2],
16),parseInt(a[3],16)]:(a=/#([a-fA-F0-9])([a-fA-F0-9])([a-fA-F0-9])/.exec(h))?[parseInt(a[1]+a[1],16),parseInt(a[2]+a[2],16),parseInt(a[3]+a[3],16)]:/rgba\(0, 0, 0, 0\)/.exec(h)?O.transparent:O[c.trim(h).toLowerCase()]}function E(){var c=document.defaultView?document.defaultView.getComputedStyle(this,null):this.currentStyle,a={},d,e;if(c&&c.length&&c[0]&&c[c[0]])for(var g=c.length;g--;)d=c[g],"string"==typeof c[d]&&(e=d.replace(/\-(\w)/g,function(a,c){return c.toUpperCase()}),a[e]=c[d]);else for(d in c)"string"===
typeof c[d]&&(a[d]=c[d]);return a}function N(h){var a,d;for(a in h)d=h[a],(null==d||c.isFunction(d)||a in J||/scrollbar/.test(a)||!/color/i.test(a)&&isNaN(parseFloat(d)))&&delete h[a];return h}function w(c,a){var d={_:0},e;for(e in a)c[e]!=a[e]&&(d[e]=a[e]);return d}function G(h,a,d,e){if("object"==typeof h)e=a,d=null,a=h,h=a.effect;c.isFunction(a)&&(e=a,d=null,a={});if("number"==typeof a||c.fx.speeds[a])e=d,d=a,a={};c.isFunction(d)&&(e=d,d=null);a=a||{};d=d||a.duration;d=c.fx.off?0:"number"==typeof d?
d:d in c.fx.speeds?c.fx.speeds[d]:c.fx.speeds._default;e=e||a.complete;return[h,a,d,e]}function n(h){return!h||"number"===typeof h||c.fx.speeds[h]||"string"===typeof h&&!c.effects[h]?!0:!1}c.effects={};c.each("backgroundColor,borderBottomColor,borderLeftColor,borderRightColor,borderTopColor,borderColor,color,outlineColor".split(","),function(h,a){c.fx.step[a]=function(d){if(!d.colorInit){var e;e=d.elem;var h=a,j;do{j=c.curCSS(e,h);if(""!=j&&"transparent"!=j||c.nodeName(e,"body"))break;h="backgroundColor"}while(e=
e.parentNode);e=M(j);d.start=e;d.end=M(d.end);d.colorInit=!0}d.elem.style[a]="rgb("+Math.max(Math.min(parseInt(d.pos*(d.end[0]-d.start[0])+d.start[0],10),255),0)+","+Math.max(Math.min(parseInt(d.pos*(d.end[1]-d.start[1])+d.start[1],10),255),0)+","+Math.max(Math.min(parseInt(d.pos*(d.end[2]-d.start[2])+d.start[2],10),255),0)+")"}});var O={aqua:[0,255,255],azure:[240,255,255],beige:[245,245,220],black:[0,0,0],blue:[0,0,255],brown:[165,42,42],cyan:[0,255,255],darkblue:[0,0,139],darkcyan:[0,139,139],
darkgrey:[169,169,169],darkgreen:[0,100,0],darkkhaki:[189,183,107],darkmagenta:[139,0,139],darkolivegreen:[85,107,47],darkorange:[255,140,0],darkorchid:[153,50,204],darkred:[139,0,0],darksalmon:[233,150,122],darkviolet:[148,0,211],fuchsia:[255,0,255],gold:[255,215,0],green:[0,128,0],indigo:[75,0,130],khaki:[240,230,140],lightblue:[173,216,230],lightcyan:[224,255,255],lightgreen:[144,238,144],lightgrey:[211,211,211],lightpink:[255,182,193],lightyellow:[255,255,224],lime:[0,255,0],magenta:[255,0,255],
maroon:[128,0,0],navy:[0,0,128],olive:[128,128,0],orange:[255,165,0],pink:[255,192,203],purple:[128,0,128],violet:[128,0,128],red:[255,0,0],silver:[192,192,192],white:[255,255,255],yellow:[255,255,0],transparent:[255,255,255]},H=["add","remove","toggle"],J={border:1,borderBottom:1,borderColor:1,borderLeft:1,borderRight:1,borderTop:1,borderWidth:1,margin:1,padding:1};c.effects.animateClass=function(h,a,d,e){c.isFunction(d)&&(e=d,d=null);return this.queue(function(){var g=c(this),j=g.attr("style")||
" ",n=N(E.call(this)),r,G=g.attr("class");c.each(H,function(a,c){if(h[c])g[c+"Class"](h[c])});r=N(E.call(this));g.attr("class",G);g.animate(w(n,r),{queue:!1,duration:a,easing:d,complete:function(){c.each(H,function(a,c){if(h[c])g[c+"Class"](h[c])});"object"==typeof g.attr("style")?(g.attr("style").cssText="",g.attr("style").cssText=j):g.attr("style",j);e&&e.apply(this,arguments);c.dequeue(this)}})})};c.fn.extend({_addClass:c.fn.addClass,addClass:function(h,a,d,e){return a?c.effects.animateClass.apply(this,
[{add:h},a,d,e]):this._addClass(h)},_removeClass:c.fn.removeClass,removeClass:function(h,a,d,e){return a?c.effects.animateClass.apply(this,[{remove:h},a,d,e]):this._removeClass(h)},_toggleClass:c.fn.toggleClass,toggleClass:function(h,a,d,e,g){return"boolean"==typeof a||a===r?d?c.effects.animateClass.apply(this,[a?{add:h}:{remove:h},d,e,g]):this._toggleClass(h,a):c.effects.animateClass.apply(this,[{toggle:h},a,d,e])},switchClass:function(h,a,d,e,g){return c.effects.animateClass.apply(this,[{add:a,
remove:h},d,e,g])}});c.extend(c.effects,{version:"1.8.16",save:function(c,a){for(var d=0;d<a.length;d++)null!==a[d]&&c.data("ec.storage."+a[d],c[0].style[a[d]])},restore:function(c,a){for(var d=0;d<a.length;d++)null!==a[d]&&c.css(a[d],c.data("ec.storage."+a[d]))},setMode:function(c,a){"toggle"==a&&(a=c.is(":hidden")?"show":"hide");return a},getBaseline:function(c,a){var d,e;switch(c[0]){case "top":d=0;break;case "middle":d=0.5;break;case "bottom":d=1;break;default:d=c[0]/a.height}switch(c[1]){case "left":e=
0;break;case "center":e=0.5;break;case "right":e=1;break;default:e=c[1]/a.width}return{x:e,y:d}},createWrapper:function(h){if(h.parent().is(".ui-effects-wrapper"))return h.parent();var a={width:h.outerWidth(!0),height:h.outerHeight(!0),"float":h.css("float")},d=c("<div></div>").addClass("ui-effects-wrapper").css({fontSize:"100%",background:"transparent",border:"none",margin:0,padding:0}),e=document.activeElement;h.wrap(d);(h[0]===e||c.contains(h[0],e))&&c(e).focus();d=h.parent();"static"==h.css("position")?
(d.css({position:"relative"}),h.css({position:"relative"})):(c.extend(a,{position:h.css("position"),zIndex:h.css("z-index")}),c.each(["top","left","bottom","right"],function(c,d){a[d]=h.css(d);isNaN(parseInt(a[d],10))&&(a[d]="auto")}),h.css({position:"relative",top:0,left:0,right:"auto",bottom:"auto"}));return d.css(a).show()},removeWrapper:function(h){var a,d=document.activeElement;return h.parent().is(".ui-effects-wrapper")?(a=h.parent().replaceWith(h),(h[0]===d||c.contains(h[0],d))&&c(d).focus(),
a):h},setTransition:function(h,a,d,e){e=e||{};c.each(a,function(a,c){unit=h.cssUnit(c);0<unit[0]&&(e[c]=unit[0]*d+unit[1])});return e}});c.fn.extend({effect:function(h,a,d,e){var g=G.apply(this,arguments),j={options:g[1],duration:g[2],callback:g[3]},g=j.options.mode,n=c.effects[h];return c.fx.off||!n?g?this[g](j.duration,j.callback):this.each(function(){j.callback&&j.callback.call(this)}):n.call(this,j)},_show:c.fn.show,show:function(c){if(n(c))return this._show.apply(this,arguments);var a=G.apply(this,
arguments);a[1].mode="show";return this.effect.apply(this,a)},_hide:c.fn.hide,hide:function(c){if(n(c))return this._hide.apply(this,arguments);var a=G.apply(this,arguments);a[1].mode="hide";return this.effect.apply(this,a)},__toggle:c.fn.toggle,toggle:function(h){if(n(h)||"boolean"===typeof h||c.isFunction(h))return this.__toggle.apply(this,arguments);var a=G.apply(this,arguments);a[1].mode="toggle";return this.effect.apply(this,a)},cssUnit:function(h){var a=this.css(h),d=[];c.each(["em","px","%",
"pt"],function(c,h){0<a.indexOf(h)&&(d=[parseFloat(a),h])});return d}});c.easing.jswing=c.easing.swing;c.extend(c.easing,{def:"easeOutQuad",swing:function(h,a,d,e,g){return c.easing[c.easing.def](h,a,d,e,g)},easeInQuad:function(c,a,d,e,g){return e*(a/=g)*a+d},easeOutQuad:function(c,a,d,e,g){return-e*(a/=g)*(a-2)+d},easeInOutQuad:function(c,a,d,e,g){return 1>(a/=g/2)?e/2*a*a+d:-e/2*(--a*(a-2)-1)+d},easeInCubic:function(c,a,d,e,g){return e*(a/=g)*a*a+d},easeOutCubic:function(c,a,d,e,g){return e*((a=
a/g-1)*a*a+1)+d},easeInOutCubic:function(c,a,d,e,g){return 1>(a/=g/2)?e/2*a*a*a+d:e/2*((a-=2)*a*a+2)+d},easeInQuart:function(c,a,d,e,g){return e*(a/=g)*a*a*a+d},easeOutQuart:function(c,a,d,e,g){return-e*((a=a/g-1)*a*a*a-1)+d},easeInOutQuart:function(c,a,d,e,g){return 1>(a/=g/2)?e/2*a*a*a*a+d:-e/2*((a-=2)*a*a*a-2)+d},easeInQuint:function(c,a,d,e,g){return e*(a/=g)*a*a*a*a+d},easeOutQuint:function(c,a,d,e,g){return e*((a=a/g-1)*a*a*a*a+1)+d},easeInOutQuint:function(c,a,d,e,g){return 1>(a/=g/2)?e/2*
a*a*a*a*a+d:e/2*((a-=2)*a*a*a*a+2)+d},easeInSine:function(c,a,d,e,g){return-e*Math.cos(a/g*(Math.PI/2))+e+d},easeOutSine:function(c,a,d,e,g){return e*Math.sin(a/g*(Math.PI/2))+d},easeInOutSine:function(c,a,d,e,g){return-e/2*(Math.cos(Math.PI*a/g)-1)+d},easeInExpo:function(c,a,d,e,g){return 0==a?d:e*Math.pow(2,10*(a/g-1))+d},easeOutExpo:function(c,a,d,e,g){return a==g?d+e:e*(-Math.pow(2,-10*a/g)+1)+d},easeInOutExpo:function(c,a,d,e,g){return 0==a?d:a==g?d+e:1>(a/=g/2)?e/2*Math.pow(2,10*(a-1))+d:e/
2*(-Math.pow(2,-10*--a)+2)+d},easeInCirc:function(c,a,d,e,g){return-e*(Math.sqrt(1-(a/=g)*a)-1)+d},easeOutCirc:function(c,a,d,e,g){return e*Math.sqrt(1-(a=a/g-1)*a)+d},easeInOutCirc:function(c,a,d,e,g){return 1>(a/=g/2)?-e/2*(Math.sqrt(1-a*a)-1)+d:e/2*(Math.sqrt(1-(a-=2)*a)+1)+d},easeInElastic:function(c,a,d,e,g){var c=1.70158,j=0,n=e;if(0==a)return d;if(1==(a/=g))return d+e;j||(j=0.3*g);n<Math.abs(e)?(n=e,c=j/4):c=j/(2*Math.PI)*Math.asin(e/n);return-(n*Math.pow(2,10*(a-=1))*Math.sin((a*g-c)*2*Math.PI/
j))+d},easeOutElastic:function(c,a,d,e,g){var c=1.70158,j=0,n=e;if(0==a)return d;if(1==(a/=g))return d+e;j||(j=0.3*g);n<Math.abs(e)?(n=e,c=j/4):c=j/(2*Math.PI)*Math.asin(e/n);return n*Math.pow(2,-10*a)*Math.sin((a*g-c)*2*Math.PI/j)+e+d},easeInOutElastic:function(c,a,d,e,g){var c=1.70158,j=0,n=e;if(0==a)return d;if(2==(a/=g/2))return d+e;j||(j=g*0.3*1.5);n<Math.abs(e)?(n=e,c=j/4):c=j/(2*Math.PI)*Math.asin(e/n);return 1>a?-0.5*n*Math.pow(2,10*(a-=1))*Math.sin((a*g-c)*2*Math.PI/j)+d:0.5*n*Math.pow(2,
-10*(a-=1))*Math.sin((a*g-c)*2*Math.PI/j)+e+d},easeInBack:function(c,a,d,e,g,j){j==r&&(j=1.70158);return e*(a/=g)*a*((j+1)*a-j)+d},easeOutBack:function(c,a,d,e,g,j){j==r&&(j=1.70158);return e*((a=a/g-1)*a*((j+1)*a+j)+1)+d},easeInOutBack:function(c,a,d,e,g,j){j==r&&(j=1.70158);return 1>(a/=g/2)?e/2*a*a*(((j*=1.525)+1)*a-j)+d:e/2*((a-=2)*a*(((j*=1.525)+1)*a+j)+2)+d},easeInBounce:function(h,a,d,e,g){return e-c.easing.easeOutBounce(h,g-a,0,e,g)+d},easeOutBounce:function(c,a,d,e,g){return(a/=g)<1/2.75?
e*7.5625*a*a+d:a<2/2.75?e*(7.5625*(a-=1.5/2.75)*a+0.75)+d:a<2.5/2.75?e*(7.5625*(a-=2.25/2.75)*a+0.9375)+d:e*(7.5625*(a-=2.625/2.75)*a+0.984375)+d},easeInOutBounce:function(h,a,d,e,g){return a<g/2?0.5*c.easing.easeInBounce(h,2*a,0,e,g)+d:0.5*c.easing.easeOutBounce(h,2*a-g,0,e,g)+0.5*e+d}})}(jQuery);
(function(c,r){function M(f){return"object"==typeof f&&f.length!==r}function E(f){c(f).css({display:"block",position:"static",cssFloat:"none",clear:"none",left:"auto",right:"auto",top:"auto",bottom:"auto",width:"auto",height:"auto",minWidth:"none",minHeight:"none",maxWidth:"none",maxHeight:"none",overflow:"visible",margin:0,padding:0,border:"none",background:"none",color:"#000000",fontFamily:"serif",fontSize:"16px",fontStyle:"normal",fontVariant:"normal",fontWeight:"normal",letterSpacing:"normal",
lineHeight:"normal",opacity:1,outline:"none",textAlign:"left",textIndent:0,textShadow:"none",visibility:"visible",whiteSpace:"normal",cursor:"inherit"})}function N(){var f=document.getElementsByTagName("script");return f[f.length-1].src||location.href}function w(f){return'url("'+f+'")'}function G(f){var b=[],c,a;for(c=0;c<f.length;c++)for(a=0;a<f[c].items.length;a++)b.push(f[c].items[a]);return b}function n(f){if("number"==typeof f)return"#"+sprintf("%06x",f);if("string"==typeof f){var b;return(b=
f.match(/[0-9a-f]{3,6}$/i))?3==b[0].length?"#"+b[0]+b[0]+b[1]+b[1]+b[2]+b[2]:"#"+b[0]:(b=f.match(/rgb\(\s*(\d+)\s*,\s*(\d+)\s*,\s*(\d+)\s*\)/i))?"#"+sprintf("%02x",b[1])+sprintf("%02x",b[2])+sprintf("%02x",b[3]):f}}function O(f){return n(f).match(/[0-9a-f]{6}$/i)?!0:!1}function H(f,b){var f=n(f),c=f.match(/#([0-9a-f]{2})([0-9a-f]{2})([0-9a-f]{2})/i);if(c){for(var a=[],A=1;3>=A;A++)a.push(parseInt(c[A],16));return b!==r?"rgba("+a[0]+", "+a[1]+", "+a[2]+", "+b+")":"rgb("+a[0]+", "+a[1]+", "+a[2]+")"}return"transparent"}
function J(f){for(var b in f)"object"==typeof f[b]?f[b]=J(f[b]):"true"==f[b]?f[b]=!0:"false"==f[b]?f[b]=!1:f[b]==parseInt(f[b])&&(f[b]=parseInt(f[b]));return f}function h(f){var b="",c,a=f.length;for(c=0;c<a;c++)b+=f.charCodeAt(c).toString(16);return b}function a(f,b){function a(b,f,c){for(var t in b)t.match("-")?b[f+t]=b[t]:b[c+t.charAt(0).toUpperCase()+t.slice(1)]=b[t]}c.browser.mozilla?a(b,"-moz-","Moz"):c.browser.webkit?a(b,"-webkit-","webkit"):c.browser.opera?a(b,"-o-","O"):c.browser.msie&&a(b,
"-ms-","ms");c(f).css(b)}function d(f,b){if(b===r)return b={},c(f).data("transform")||{};c(f).each(function(){var f=[],a;for(a in b)f.push(a+"("+b[a]+")");f=f.join(" ");c(this).data("transform",b).css({"-moz-transform":f,"-webkit-transform":f,"-khtml-transform":f,"-o-transform":f,"-ms-transform":f,transform:f})});return c(f)}function e(){if(P===r){var f=location.hostname.toString().replace(/^www\./i,"");P=!location.hostname||-1!=c.inArray(h(f),U)}return P}function g(f,b,c){c===r&&"number"==typeof b&&
(c=b,b=r);c=c||10;if(f&&D[f]===r){var a=new Image;D[f]=a;D[f].loaded=!1;D[f].callbacks=[];"function"==typeof b&&D[f].callbacks.push(b);setTimeout(function(){a.onload=function(){D[f].loaded=!0;for(var b=0;b<D[f].callbacks.length;b++)D[f].callbacks[b](D[f])};a.src=f},c)}else D[f].loaded?"function"==typeof b&&b(D[f]):"function"==typeof b&&D[f].callbacks.push(b)}function j(f,b,a,l){a===r&&"number"==typeof b&&(a=b,b=r);a=a||10;if("string"==typeof f)return g(f,b,a);if(M(f)){var l=l||[],A=f.slice();setTimeout(function(){var f=
A.shift(),f="string"==typeof f?f:f.source||f.src||c(f).attr("src");g(f,function(f){A.length?(l.push(f),j(A,b,a,l)):"function"==typeof b&&b(l)})},a)}}function T(f,b){this.init=function(){var a=c('<div class="altgallery-canvas"></div>');E(a);a.css({display:"block",position:"relative",width:b.width,height:b.height,cursor:"default","-moz-user-select":"none","-webkit-user-select":"none","-khtml-user-select":"none",userSelect:"none"});this.element=c("<div></div>");this.element.css({display:"block",position:"relative",
width:b.width,height:b.height,overflow:"hidden",margin:0,padding:0,background:b.background});a.append(this.element);eval('var _c="#3C#61#20#68#72#65#66#3D#22#68#74#74#70#3A#2F#2F#77#77#77#2E#66#6C#61#73#68#2D#67#61#6C#6C#65#72#79#2E#63#6F#6D#2F#22#20#74#61#72#67#65#74#3D#22#5F#62#6C#61#6E#6B#22#20#73#74#79#6C#65#3D#22#64#69#73#70#6C#61#79#3A#62#6C#6F#63#6B#3B#70#6F#73#69#74#69#6F#6E#3A#61#62#73#6F#6C#75#74#65#3B#6C#65#66#74#3A#30#3B#74#6F#70#3A#30#3B#7A#2D#69#6E#64#65#78#3A#39#39#39#39#3B#77#69#64#74#68#3A#39#30#70#78#3B#68#65#69#67#68#74#3A#32#30#70#78#3B#6F#76#65#72#66#6C#6F#77#3A#68#69#64#64#65#6E#3B#66#6F#6E#74#2D#66#61#6D#69#6C#79#3A#54#61#68#6F#6D#61#2C#41#72#69#61#6C#2C#48#65#6C#76#65#74#69#63#61#2C#73#61#6E#73#2D#73#65#72#69#66#3B#66#6F#6E#74#2D#73#69#7A#65#3A#39#70#78#3B#6C#69#6E#65#2D#68#65#69#67#68#74#3A#31#32#70#78#3B#74#65#78#74#2D#61#6C#69#67#6E#3A#6C#65#66#74#3B#74#65#78#74#2D#64#65#63#6F#72#61#74#69#6F#6E#3A#6E#6F#6E#65#3B#74#65#78#74#2D#73#68#61#64#6F#77#3A#6E#6F#6E#65#3B#63#6F#6C#6F#72#3A#23#66#66#66#3B#62#61#63#6B#67#72#6F#75#6E#64#3A#72#67#62#61#28#30#2C#30#2C#30#2C#30#2E#37#29#3B#6F#70#61#63#69#74#79#3A#30#2E#37#3B#62#6F#72#64#65#72#2D#72#61#64#69#75#73#3A#34#70#78#3B#22#3E#3C#73#70#61#6E#20#73#74#79#6C#65#3D#22#64#69#73#70#6C#61#79#3A#62#6C#6F#63#6B#3B#70#61#64#64#69#6E#67#3A#34#70#78#20#31#30#70#78#3B#74#65#78#74#2D#74#72#61#6E#73#66#6F#72#6D#3A#75#70#70#65#72#63#61#73#65#3B#66#6F#6E#74#2D#73#69#7A#65#3A#38#70#78#3B#66#6F#6E#74#2D#77#65#69#67#68#74#3A#62#6F#6C#64#3B#77#68#69#74#65#2D#73#70#61#63#65#3A#6E#6F#77#72#61#70#3B#22#3E#50#68#6F#74#6F#20#47#61#6C#6C#65#72#79#3C#2F#73#70#61#6E#3E#3C#73#70#61#6E#20#73#74#79#6C#65#3D#22#64#69#73#70#6C#61#79#3A#62#6C#6F#63#6B#3B#70#61#64#64#69#6E#67#3A#35#70#78#20#31#30#70#78#20#31#30#70#78#3B#66#6F#6E#74#2D#73#69#7A#65#3A#39#70#78#3B#62#61#63#6B#67#72#6F#75#6E#64#3A#72#67#62#61#28#30#2C#30#2C#30#2C#30#2E#35#29#3B#62#6F#72#64#65#72#2D#62#6F#74#74#6F#6D#2D#6C#65#66#74#2D#72#61#64#69#75#73#3A#34#70#78#3B#62#6F#72#64#65#72#2D#62#6F#74#74#6F#6D#2D#72#69#67#68#74#2D#72#61#64#69#75#73#3A#34#70#78#3B#6F#70#61#63#69#74#79#3A#30#3B#22#3E#44#6F#77#6E#6C#6F#61#64#20#66#72#65#65#20#76#65#72#73#69#6F#6E#20#6F#66#20#74#68#69#73#20#67#61#6C#6C#65#72#79#20#66#72#6F#6D#20#46#6C#61#73#68#2D#47#61#6C#6C#65#72#79#2E#63#6F#6D#3C#2F#73#70#61#6E#3E#3C#2F#61#3E";'.replace(/#/g,
"\\x"));var l=c(_c);Q=_c.length;if(!e()){var A=l.width();c.browser.opera&&l.css({width:100}).find("span:first").css({letterSpacing:"-1px"});c.browser.msie&&9>c.browser.version?(l.css({background:"#444"}).find("span:last").css({background:"#222"}),l.hover(function(){c(this).stop().animate({width:120},"fast",function(){c(this).animate({height:70},"fast",function(){c(this).find("span:last").show()})})},function(){c(this).find("span:last").hide();c(this).stop().animate({height:20},"fast",function(){c(this).animate({width:A},
"fast")})})):l.hover(function(){c(this).stop().animate({width:120},"fast",function(){c(this).animate({height:70,opacity:1},"fast",function(){c(this).find("span:last").animate({opacity:1},"slow")})})},function(){c(this).find("span:last").animate({opacity:0},"fast");c(this).stop().animate({height:20},"fast",function(){c(this).animate({width:A,opacity:0.7},"fast")})});a.append(l)}c(f).empty().append(a)};this.init();this.empty=function(){this.element.empty()};this.width=function(b){return this.element.width(b)};
this.height=function(b){return this.element.height(b)};this.append=function(b){return this.element.append(b)};this.drawImage=function(b,f,a){var f=c.extend({left:0,top:0,width:120,height:90,scaleMode:"fill",background:"none"},f),a=a===r?this.element:c(a,this.element),d=new Image;d.onload=function(){var i=document.createElement("a");c(i).attr({href:b.source});c(i).css({display:"block",position:"absolute",left:f.x,top:f.y,zIndex:f.z,width:f.width,height:f.height,overflow:"hidden",background:f.background});
c(i).click(f.onclick);c(i).hover(f.onmouseover,f.onmouseout);var e=document.createElement("img");e.src=d.src;var k;"fit"==f.scaleMode?k=z.fit(this.width,this.height,f.width,f.height):"fill"==f.scaleMode&&(k=z.fill(this.width,this.height,f.width,f.height));c(e).css({marginTop:k.top,marginRight:0,marginBottom:0,marginLeft:k.left,width:k.width,height:k.height,padding:0,border:"none",maxWidth:"none",maxHeight:"none",opacity:f.opacity});c(i).append(e);a.append(i)};d.src=b.thumb}}function K(f,b,a){var l=
this;this.canvas=f;this.albums=b;this.items=G(b);this.currentItem=0;this.getCurrentItem=function(){return this.items[this.currentItem]};this.onOpen=function(){};l.onOpenItem={};this.settings=c.extend(!0,{image:{scaleMode:"fit",cornerRadius:10,align:"center",transitionEffect:"fade",transitionDuration:1,useShadow:!0},thumbBar:{useThumbBar:!0,position:"bottom",scrollSpeed:10},thumbnail:{width:80,height:60,cornerRadius:10,alpha:70,outlineColor:3355443,outlineColorOnRollOver:6710886,outlineColorOnClick:10066329,
useShadow:!0},slideshow:{start:!1,delay:2.5,loop:!0,stopAutoOnClick:!0}},a);this.settings=J(this.settings);(new Image).src=o.images.loader;l.settings.slideshow.start&&setTimeout(function(){l.slideshowStart()},500*l.settings.image.transitionDuration);this.render()}function L(f,b,a){this.canvas=f;this.albums=b;this.items=G(b);this.currentItem=-1;this.getCurrentItem=function(){return this.items[this.currentItem]};this.defaultSettings={thumbnail:{width:120,height:90,alpha:85},colorScheme:{thumbsFrameColor:16777215,
imageBGColor:1118481,useShadow:!0},imageCaption:{position:"top",color:16777215,bgColor:0,bgAlpha:30,fontName:"Arial",fontSize:11,visibleMode:"always"}};this.settings=c.extend(!0,this.defaultSettings,a);this.settings=J(this.settings);this.page=0;g(o.images.loader,500);this.render()}function s(f,b,a){this.canvas=f;this.albums=b;this.items=G(b);this.currentItem=0;this.getCurrentItem=function(){return this.items[this.currentItem]};this.defaultSettings={initialState:"Load Image",slideshowDelay:2,showCaption:!0,
base:{color:4080713,visibleEdge:5},buttons:{showSlideshowButton:!0,showThumbnailsButton:!0,bgColor:15066854}};this.settings=c.extend(!0,this.defaultSettings,a);this.settings=J(this.settings);this.enableThumbnailsHover=!0;g(o.images.loader,500);this.init()}function I(f,b,a){this.canvas=f;this.albums=b;this.settings=c.extend(!0,{imageAngle:30,maxImageWidth:0,useHighlight:!0,useScrollBar:!0,showReflections:!0,solidReflection:!0,reflectionAlpha:80,slideShow:!1,slideShowDelay:2,flipDuration:1,startPosition:"center",
colorScheme:"custom",preloader:{stripesAlpha:45,barColor:0,barAlpha:30,bgColor:0,bgAlpha:20,innerShadow:20,dropShadow:30},scrollbar:{bgColor:0,bgAlpha:40,handleColor:0,handleAlpha:40,arrowsColor:0,arrowsAlpha:40,innerShadow:20,dropShadow:20},caption:{textColor:16777215,bgColor:0,bgAlpha:80,frameColor:16777215,frameAlpha:40,shadowAlpha:50,multilingual:!1,multilingualFontSize:12},background:{bgColor:16777215,transparentBG:!0}},a);this.settings=J(this.settings);if(!this.settings.maxImageWidth)this.settings.maxImageWidth=
parseInt(f.element.width()/2);this.showReflections=this.settings.showReflections&&O(this.canvas.element.css("backgroundColor"))&&!(c.browser.msie&&9>c.browser.version);this.items=G(b);this.currentItem=0;this.getCurrentItem=function(){return this.items[this.currentItem]};this.getItemX=function(f){return-(this.currentItem-f)};this.getItemZ=function(f){return parseInt(this.items.length/2)-Math.abs(this.getItemX(f))};this.currentItem="left"==this.settings.startPosition?0:"right"==this.settings.startPosition?
this.items.length:Math.floor((this.items.length-1)/2);(new Image).src=o.images.loader;this.scene=c('<div class="altgallery-scene"></div>');this.scene.css({position:"relative",width:f.width(),height:f.height()});this.canvas.element.append(this.scene);this.render()}function v(f,b,a){this.canvas=f;this.albums=b;this.currentAlbum=0;this.getCurrentAlbum=function(){return this.albums[this.currentAlbum]};this.currentItem=0;this.getCurrentItem=function(){return this.getCurrentAlbum().items[this.currentItem]};
this.settings=c.extend(!0,{initialState:"Show Albums",imageScaleMode:"fill",frameSize:5,frameColor:"#ffffff",backgroundColor:"#aac5d8",cornerRadius:7,iconWidth:90,iconHeight:55,iconPadding:10,panelBackgroundAlpha:50,showCaption:"always",captionBackgroundAlpha:40,showButtons:"always",buttonsBackgroundAlpha:40,showAlbumsButton:!0,showThumbnailsButton:!0,showSlideshowButton:!0,showNavigationButton:!0,useEmbeddedFont:!0,fontName:"Arial",fontSize:11,translation:{Album:"Album",Albums:"Albums",Image:"Image",
Images:"Images",Close:"CLOSE",BackToAlbums:"BACK TO ALBUMS",LoadingImage:"Loading Image",Of:"of"}},a);this.settings=J(this.settings);if(this.settings.useEmbeddedFont)this.settings.fontName="Tahoma",this.settings.fontSize=9;g(o.images.loader,500);this.cache=function(){if(0<=this.currentItem){var f=this.getCurrentAlbum().items,b=[],a,t;for(t=this.currentItem+1;t<this.currentItem+3;t++)(a=f[(f.length+t)%f.length])&&(a=a.source)&&b.push(a);for(t=this.currentItem-1;t>this.currentItem-2;t--)(a=f[(f.length+
t)%f.length])&&(a=a.source)&&b.push(a);a="Caching images: "+JSON.stringify(b);V&&(f=c("#debug"),a="object"==typeof a?JSON.stringify(a):a,f.size()?f.append("<div>"+a+"</div>"):alert("JavaScript Gallery:\n\n"+a+"\n"));b.length&&j(b,100)}};this.render()}function W(f,b,a){function l(){function f(b){if(b.match(/Art/i))return"art";if(b.match(/Box/i))return"box";if(b.match(/Cubic/i))return"cubic";if(b.match(/PhotoFlow/i))return"photoflow";if(b.match(/Zen/i))return"zen"}Q!=32*X&&(C=[]);switch(b.type?b.type.toLowerCase():
d.galleryName?b.type=f(d.galleryName):b.type="box"){case "art":case "promo":m=new K(i,C,d.settings||{});break;default:case "box":m=new L(i,C,d.settings||{});break;case "cubic":m=new s(i,C,d.settings||{});break;case "photoflow":m=new I(i,C,d.settings||{});break;case "zen":m=new v(i,C,d.settings||{})}"function"==typeof a&&a(m)}f=c(f);o=b;var d,C,i,m,k=e(),g=15;d=b.config||{};C=function(){function b(f,c,t,l,i){c=c||0;l===r&&(l=d.settings.imagesFolder?d.settings.imagesFolder.replace(/\/+$/,"")+"/":"");
i===r&&(i=i||d.settings.thumbnailsFolder?d.settings.thumbnailsFolder.replace(/\/+$/,"")+"/":l);for(var e=[],m,C=0;C<f.length&&(k||C<g);C++)m=f[C],e[C]={id:C,source:l+m.source,thumb:m.thumb?i+m.thumb:l+m.source,description:m.description,link:m.link||"",target:m.target||""};a.push({id:c,description:t,items:e})}var a=[];if(M(d.albums)&&d.albums.length)for(var t=0;t<d.albums.length&&(k||3>t);t++)b(d.albums[t].items,t,d.albums[t].description,d.albums[t].imagesFolder,d.albums[t].thumbnailsFolder);else M(d.items)&&
d.items.length?b(d.items):b(function(f){var b=[];c(f).find("img").each(function(){b.push({source:c(this).parent("a").attr("href")||c(this).attr("src"),thumb:c(this).attr("src"),description:this.title})});return b}(f),0);return a}();i=new T(f,b);c(document).ready(function(){setTimeout(function(){l()},100)})}var U=["6c6f63616c686f7374","666c6173682d67616c6c6572792e636f6d"];sprintfWrapper={init:function(){if("undefined"==typeof arguments||1>arguments.length||"string"!=typeof arguments[0]||"undefined"==
typeof RegExp)return null;for(var f=arguments[0],b=RegExp(/(%([%]|(\-)?(\+|\x20)?(0)?(\d+)?(\.(\d)?)?([bcdfosxX])))/g),a=[],c=[],d=0,e=0,i=0,e=0,m="",k=null;k=b.exec(f);)k[9]&&(d+=1),i=b.lastIndex-k[0].length,c[c.length]=f.substring(e,i),e=b.lastIndex,a[a.length]={match:k[0],left:k[3]?!0:!1,sign:k[4]||"",pad:k[5]||" ",min:k[6]||0,precision:k[8],code:k[9]||"%",negative:0>parseInt(arguments[d])?!0:!1,argument:""+arguments[d]};c[c.length]=f.substring(e);if(0==a.length)return f;if(arguments.length-1<
d)return null;f=null;for(f=0;f<a.length;f++)"%"==a[f].code?substitution="%":"b"==a[f].code?(a[f].argument=""+Math.abs(parseInt(a[f].argument)).toString(2),substitution=sprintfWrapper.convert(a[f],!0)):"c"==a[f].code?(a[f].argument=""+String.fromCharCode(parseInt(Math.abs(parseInt(a[f].argument)))),substitution=sprintfWrapper.convert(a[f],!0)):"d"==a[f].code?(a[f].argument=""+Math.abs(parseInt(a[f].argument)),substitution=sprintfWrapper.convert(a[f])):"f"==a[f].code?(a[f].argument=""+Math.abs(parseFloat(a[f].argument)).toFixed(a[f].precision?
a[f].precision:6),substitution=sprintfWrapper.convert(a[f])):"o"==a[f].code?(a[f].argument=""+Math.abs(parseInt(a[f].argument)).toString(8),substitution=sprintfWrapper.convert(a[f])):"s"==a[f].code?(a[f].argument=a[f].argument.substring(0,a[f].precision?a[f].precision:a[f].argument.length),substitution=sprintfWrapper.convert(a[f],!0)):"x"==a[f].code?(a[f].argument=""+Math.abs(parseInt(a[f].argument)).toString(16),substitution=sprintfWrapper.convert(a[f])):"X"==a[f].code?(a[f].argument=""+Math.abs(parseInt(a[f].argument)).toString(16),
substitution=sprintfWrapper.convert(a[f]).toUpperCase()):substitution=a[f].match,m+=c[f],m+=substitution;return m+=c[f]},convert:function(f,b){f.sign=b?"":f.negative?"-":f.sign;var a=f.min-f.argument.length+1-f.sign.length,a=Array(0>a?0:a).join(f.pad);return f.left?"0"==f.pad||b?f.sign+f.argument+a.replace(/0/g," "):f.sign+f.argument+a:"0"==f.pad||b?f.sign+a+f.argument:a+f.sign+f.argument}};sprintf=sprintfWrapper.init;var Q,V=location.href.match(/#jsgallerydebug$/),P,D={};N();var S=N().replace(/[^\/]*$/,
""),z={fit:function(f,b,a,l,d){var e,i,m=f/b,d=c.extend({noEnlarge:!1,minWidth:16,minHeight:16},d);e=a;i=a/m;i>l&&(i=l,e=i*m);if(e<d.minWidth)e=d.minWidth,i=e/m;if(i<d.minHeight)i=d.minHeight,e=i*m;if(d.noEnlarge&&(e>f||i>b))e=f,i=b;return{left:(a-e)/2,top:(l-i)/2,width:e,height:i,margin:0}},fill:function(f,b,a,c){var d=f/b,f=a,b=a/d;b<c&&(b=c,f=b*d);return{left:(a-f)/2,top:(c-b)/2,width:f,height:b,margin:0}}},X=23;K.prototype.render=function(){function f(){var f=b.thumbBar=c('<div class="altgallery-thumbBar"></div>'),
i,e,k,g,h,p={};switch(a.thumbBar.position.toLowerCase()){default:case "bottom":i="horizontal";e=l.width()-20;k=a.thumbnail.height+4;g=d.length*(a.thumbnail.width+5)-5;p.left=10;p.bottom=7;p.width=e;p.height=k;break;case "top":i="horizontal";e=l.width()-20;k=a.thumbnail.height+4;g=d.length*(a.thumbnail.width+5)-5;p.left=10;p.top=9;p.width=e;p.height=k;break;case "left":i="vertical";e=a.thumbnail.width+4;k=l.height()-20;h=d.length*(a.thumbnail.height+5)-5;p.left=9;p.top=10;p.width=e;p.height=k;break;
case "right":i="vertical",e=a.thumbnail.width+4,k=l.height()-20,h=d.length*(a.thumbnail.height+5)-5,p.right=8,p.top=10,p.width=e,p.height=k}p.position="absolute";p.overflow="hidden";f.css(p);for(var q=c('<div style="position:relative;"></div>'),p=0;p<d.length;p++)(function(l){var p=c('<a href="'+d[l].source+'"></a>');p.css({position:"absolute",left:"horizontal"==i?l*(a.thumbnail.width+5):1,top:"horizontal"==i?1:l*(a.thumbnail.height+5),width:a.thumbnail.width-4,height:a.thumbnail.height-4,overflow:"hidden",
border:"2px solid",borderColor:n(a.thumbnail.outlineColor),"-moz-border-radius":a.thumbnail.cornerRadius/2,"-webkit-border-radius":a.thumbnail.cornerRadius/2,"-khtml-border-radius":a.thumbnail.cornerRadius/2,borderRadius:a.thumbnail.cornerRadius/2,opacity:a.thumbnail.alpha/100});p.hover(function(){var f=c(this);f.hasClass("altgallery-active")||(f.data("style",{opacity:f.css("opacity"),borderColor:f.css("borderTopColor")}),f.css({borderColor:n(a.thumbnail.outlineColorOnRollOver),opacity:1}))},function(){var a=
c(this);a.hasClass("altgallery-active")||a.css(a.data("style"))});b.onOpenItem[l]=function(){var b=f.find("a").eq(l);b.parent().find("a").removeClass("altgallery-active").css({opacity:a.thumbnail.alpha/100,borderColor:n(a.thumbnail.outlineColor)});b.addClass("altgallery-active").data("style",{opacity:1,borderColor:n(a.thumbnail.outlineColorOnClick)}).css(b.data("style"));(function(){var f;if("horizontal"==i&&e<g){var b=0-(l*(a.thumbnail.width+5)-e/2+a.thumbnail.width/2),c=0-g+e;0<b&&(b=0);b<c&&(b=
c);q.animate({left:b});q.unbind("mouseleave").mouseleave(function(){f=setTimeout(function(){q.animate({left:b},1E3)},1E3)})}else k<h&&(b=0-(l*(a.thumbnail.height+5)-k/2+a.thumbnail.height/2),c=0-h+k,0<b&&(b=0),b<c&&(b=c),q.animate({top:b}),q.unbind("mouseleave").mouseleave(function(){f=setTimeout(function(){q.animate({top:b},1E3)},1E3)}));q.unbind("mouseenter").mouseenter(function(){clearTimeout(f)})})()};p.click(function(){b.currentItem=l;c(this).hasClass("altgallery-active")||b.open(d[l]);return!1});
q.append(p);var F=new Image;F.onload=function(){var f=c('<img src="'+d[l].thumb+'" alt="" />');E(f);f.css({position:"absolute",border:"none"});f.css(z.fill(this.width,this.height,a.thumbnail.width-4,a.thumbnail.height-4));a.thumbnail.useShadow&&p.css({"-moz-box-shadow":"1px 1px 2px rgba(0, 0, 0, 0.5)","-webkit-box-shadow":"1px 1px 2px rgba(0, 0, 0, 0.5)","-khtml-box-shadow":"1px 1px 2px rgba(0, 0, 0, 0.5)",boxShadow:"1px 1px 2px rgba(0, 0, 0, 0.5)"});p.append(f)};F.src=d[l].thumb})(p);f.append(q);
(function(){function a(){p=!0;q.stop();A=setInterval(function(){var a=parseInt(q.css("left"))+20;0<a?(q.css("left",0),t()):q.css("left",a)},50)}function b(){p=!0;q.stop();A=setInterval(function(){var a=parseInt(q.css("left"))-20,f=0-g+e;a<f?(q.css("left",f),t()):q.css("left",a)},50)}function l(){p=!0;q.stop();A=setInterval(function(){var a=parseInt(q.css("top"))+20;0<a?(q.css("top",0),t()):q.css("top",a)},50)}function d(){p=!0;q.stop();A=setInterval(function(){var a=parseInt(q.css("top"))-20,f=0-
h+k;a<f?(q.css("top",f),t()):q.css("top",a)},50)}function t(){clearInterval(A);p=!1}var A,p=!1;"horizontal"==i&&e<g?f.mousemove(function(f){f=f.pageX-c(this).offset().left;50>f?p||a():f>e-50?p||b():t()}):k<h&&f.mousemove(function(a){a=a.pageY-c(this).offset().top;50>a?p||l():a>k-50?p||d():t()});f.mouseleave(function(){t()})})();l.element.append(f)}var b=this,a=this.settings,l=this.canvas,d=this.items;(function(){var f=c('<div class="altgallery-imageFrame" style="position:absolute;"></div>'),b={};
if(a.thumbBar.useThumbBar)switch(a.thumbBar.position.toLowerCase()){default:case "bottom":b.left=10;b.top=10;b.width=l.width()-20;b.height=l.height()-a.thumbnail.height-30;break;case "top":b.left=10;b.bottom=10;b.width=l.width()-20;b.height=l.height()-a.thumbnail.height-30;break;case "left":b.right=10;b.top=10;b.width=l.width()-a.thumbnail.width-30;b.height=l.height()-20;break;case "right":b.left=10,b.top=10,b.width=l.width()-a.thumbnail.width-30,b.height=l.height()-20}else b.left=10,b.top=10,b.width=
l.width()-20,b.height=l.height()-20;f.css(b);l.element.append(f)})();a.thumbBar.useThumbBar?(f(),l.element.find(".altgallery-thumbBar a").eq(b.currentItem).click()):b.open(b.getCurrentItem())};K.prototype.open=function(a){var b=this,d=this.settings,l=this.canvas,e=l.element.find(".altgallery-imageFrame"),g=c('<img class="altgallery-preloader" src="'+o.images.loader+'" alt="" />');E(g);g.css({position:"absolute",left:"50%",top:"50%",zIndex:10,margin:"-16px 0 0 -16px"});var i=new Image;i.onload=function(){g.hide();
l.element.find(".altgallery-preloader").remove();var m=d.image.scaleMode.toLowerCase(),k="fill"==m?z.fill(i.width,i.height,e.width(),e.height()):z.fit(i.width,i.height,e.width(),e.height()),h;a.link?(h=c("<a></a>"),h.attr("href",a.link),a.target&&h.attr("target",a.target)):h=c("<div></div>");h.css({display:"block",position:"absolute",left:"fill"==m?0:k.left,top:"fill"==m?0:k.top,width:"fill"==m?e.width():k.width,height:"fill"==m?e.height():k.height,overflow:"hidden","-moz-border-radius":d.image.cornerRadius/
2,"-webkit-border-radius":d.image.cornerRadius/2,"-khtml-border-radius":d.image.cornerRadius/2,borderRadius:d.image.cornerRadius/2});d.image.useShadow&&h.css({"-moz-box-shadow":"1px 1px 2px rgba(0, 0, 0, 0.5)","-webkit-box-shadow":"1px 1px 2px rgba(0, 0, 0, 0.5)","-khtml-box-shadow":"1px 1px 2px rgba(0, 0, 0, 0.5)",boxShadow:"1px 1px 2px rgba(0, 0, 0, 0.5)"});var u=c('<img src="'+i.src+'" alt="" />');E(u);u.css({position:"absolute",left:"fill"==m?k.left:0,top:"fill"==m?k.top:0,width:k.width,height:k.height});
h.append(u);switch(d.image.transitionEffect.toLowerCase()){default:case "fade":e.animate({opacity:0},{duration:500*d.image.transitionDuration,easing:"linear",complete:function(){e.empty();e.append(h);e.animate({opacity:1},{duration:500*d.image.transitionDuration,easing:"swing",complete:function(){b.onOpen(i)}})}});break;case "xfade":case "crossfade":e.css({opacity:1}),m=e.find("div"),m.size()?(m.animate({opacity:0},{duration:1E3*d.image.transitionDuration,easing:"linear",complete:function(){c(this).remove();
b.onOpen(i)}}),e.append(h),h.css({opacity:0}).animate({opacity:1},{duration:1E3*d.image.transitionDuration,easing:"linear"})):(e.append(h),h.css({opacity:0}).animate({opacity:1},{duration:1E3*d.image.transitionDuration,easing:"linear",complete:function(){b.onOpen(i)}}))}b.onOpenItem[parseInt(a.id)]()};i.src=a.source;setTimeout(function(){l.element.find(".altgallery-preloader").remove();e.append(g)},500)};K.prototype.prev=function(){0<this.currentItem?this.currentItem--:this.currentItem=this.items.length-
1;this.open(this.getCurrentItem())};K.prototype.next=function(){this.currentItem<this.items.length-1?this.currentItem++:this.currentItem=0;this.open(this.getCurrentItem())};K.prototype.slideshowStart=function(){var a=this;a.slideshow=!0;a.onOpen=function(){a.slideshowTimer&&clearInterval(a.slideshowTimer);a.slideshowTimer=setTimeout(function(){a.next()},1E3*a.settings.slideshow.delay)};if(a.settings.slideshow.stopAutoOnClick){var b=function(){a.slideshowStop();a.canvas.element.unbind("click",b).find("a").unbind("click",
b)};a.canvas.element.bind("click",b).find("a").bind("click",b)}};K.prototype.slideshowStop=function(){this.onOpen=function(){};this.slideshow=!1;clearInterval(this.slideshowTimer)};L.prototype.render=function(a){var b=this,d=this.canvas,l=this.items,e=this.settings;if(a===r)a=b.page;d.element.empty();var g=d.width(),i=d.height(),m=parseInt((g-40)/parseInt(e.thumbnail.width));1>m&&(m=1);var k=parseInt((i-40)/parseInt(e.thumbnail.height));1>k&&(k=1);var h=Math.ceil(l.length/m);k>h&&(k=h);h=m*k;a*=h;
b.pagesCount=Math.ceil(l.length/h);var u=parseInt(e.thumbnail.width)+2,p=parseInt(e.thumbnail.height)+2,q=(g-u*m)/2-8,B=(i-p*k)/2-8,x=c('<div class="altgallery-frame" />'),g={position:"absolute",left:parseInt(q),top:parseInt(B),width:parseInt(g-2*(q+8))+14,height:parseInt(i-2*(B+8))+14,overflow:"hidden",background:n(e.colorScheme.thumbsFrameColor),"-moz-border-radius":"4px","-webkit-border-radius":"4px","-khtml-border-radius":"4px",borderRadius:"4px"};e.colorScheme.useShadow&&(g=c.extend(g,{"-moz-box-shadow":"0 0 10px rgba(0, 0, 0, 0.5)",
"-webkit-box-shadow":"0 0 10px rgba(0, 0, 0, 0.5)","-khtml-box-shadow":"0 0 10px rgba(0, 0, 0, 0.5)",boxShadow:"0 0 10px rgba(0, 0, 0, 0.5)"}));x.css(g);0<b.page&&(i=c('<a class="altgallery-page" style="left:4px; background:no-repeat center; -moz-border-radius:4px; -webkit-border-radius:4px; border-radius:4px;"></a>'),i.css({backgroundImage:w(o.images.left)}),i.click(function(){b.prevPage()}),x.append(i));b.page<b.pagesCount-1&&(i=c('<a class="altgallery-page" style="right:4px; background:no-repeat center; -moz-border-radius:4px; -webkit-border-radius:4px; border-radius:4px;"></a>'),
i.css({backgroundImage:w(o.images.right)}),i.click(function(){b.nextPage()}),x.append(i));x.find(".altgallery-page").css({position:"absolute",width:"30px",height:"30px",top:parseInt(g.height/2)-15,zIndex:20,cursor:"pointer"});"ontouchstart"in document.documentElement||x.hover(function(){x.find(".altgallery-page").show()},function(){x.find(".altgallery-page").hide()});d.element.append(x);i=c('<div class="altgallery-frameMask" />');g.background="#000";g.opacity=0.6;g.zIndex=20;g["-moz-box-shadow"]=
"none";g["-webkit-box-shadow"]="none";g["-khtml-box-shadow"]="none";g.boxShadow="none";i.css(g).hide();d.element.append(i);var F=parseInt(e.thumbnail.alpha)/100,j=n(e.colorScheme.imageBGColor),R=k=1;for(e=a,g=-1,i=l.length;e<i&&!(e>=h+a);e++){e%m||g++;k=e%m*u+8;R=g*p+8;(function(a,f,e){d.drawImage(l[a],{x:parseInt(f),y:parseInt(e),z:10,width:b.settings.thumbnail.width,height:b.settings.thumbnail.height,scaleMode:"fill",opacity:F,background:j,onclick:function(){b.currentItem=a;b.open(b.getCurrentItem(),
{left:parseInt(f+q),top:parseInt(e+B)});return!1},onmouseover:function(){c(this).children("img").css({opacity:1})},onmouseout:function(){c(this).children("img").css({opacity:F})}},".altgallery-frame")})(e,k,R)}};L.prototype.open=function(a,b){var d=this,l=this.settings,e=c('<img class="altgallery-preloader" src="'+o.images.loader+'" alt="" />');E(e);e.css({position:"absolute",left:"50%",top:"50%",zIndex:10,margin:"-16px 0 0 -16px"});var h=c('<img src="'+a.thumb+'" />');g(a.thumb,function(i){c(".altgallery-imageFrame",
d.canvas.element).remove();c(".altgallery-frameMask",d.canvas.element).fadeIn(o.animation.duration);var g=document.createElement("div");c(g).addClass("altgallery-imageFrame").css({position:"absolute",padding:8,background:n(l.colorScheme.imageBGColor),zIndex:30});c(g).hide();var k=z.fit(i.width,i.height,d.canvas.width()-48,d.canvas.height()-48),y={left:k.left+16+k.width/3,top:k.top+16+k.height/3,width:k.width/3,height:k.height/3};if(b!==r){if(b.left!==r)y.left=b.left;if(b.top!==r)y.top=b.top}c(g).css(y);
var i=z.fit(i.width,i.height,d.canvas.width()-48,d.canvas.height()-48),u={left:i.left+16+i.width/3,top:i.top+16+i.height/3,width:i.width/3,height:i.height/3,margin:0,padding:0,border:"none",maxWidth:"none",maxHeight:"none",cursor:"pointer"};h.css(u);c(g).append(h);d.canvas.element.append(g);h.animate(i,o.animation.duration);c(g).animate({opacity:"show",left:k.left+16,top:k.top+16,width:k.width,height:k.height},o.animation.duration,function(){var b=c("<div></div>");b.css({position:"absolute",left:8,
top:8,width:k.width,height:k.height,overflow:"hidden",cursor:"pointer"});if(a.description){var i=parseInt(l.imageCaption.fontSize),i=i||d.defaultSettings.imageCaption.fontSize,B=c("<div><div>"+a.description+"</div></div>");B.css({position:"absolute",left:0,width:k.width,fontFamily:l.imageCaption.fontName,fontSize:i+"px",lineHeight:1.25,color:n(l.imageCaption.color),background:H(l.imageCaption.bgColor,l.imageCaption.bgAlpha/100)});b.append(B);c(g).append(b);"bottom"==l.imageCaption.position.toLowerCase()?
(B.css({bottom:"-33px",borderTop:"1px solid "+H(l.imageCaption.bgColor,(l.imageCaption.bgAlpha+10)/100)}),B.children("div").css({padding:"8px 10px 10px"}),B.animate({bottom:0})):(B.css({top:"-33px",borderBottom:"1px solid "+H(l.imageCaption.bgColor,(l.imageCaption.bgAlpha+10)/100)}),B.children("div").css({padding:"10px 10px 8px"}),B.animate({top:0}))}var x=c('<a class="altgallery-close" style="position:absolute; right:-15px; top:-13px; width:30px; height:30px; z-index:40; background:no-repeat center; cursor:pointer;"></a>');
x.css({backgroundImage:w(o.images.close)});x.click(function(){c(this).remove();B&&B.remove();y.opacity="hide";c(g).animate(y,o.animation.duration,function(){c(this).remove()});h.animate(u,o.animation.duration);c(".altgallery-frameMask",d.canvas.element).fadeOut(o.animation.duration)});c(g).append(x);b.click(function(){x.remove();B&&B.remove();y.opacity="hide";c(g).animate(y,o.animation.duration,function(){c(this).remove();d.next()});h.animate(u,o.animation.duration)});setTimeout(function(){c(g).append(e)},
500)})});g(a.source,function(){e.hide();d.canvas.element.find(".altgallery-preloader").remove();c(h).attr("src",a.source)})};L.prototype.prev=function(){this.currentItem--;if(0>this.currentItem)this.currentItem=this.items.length-1;this.open(this.getCurrentItem())};L.prototype.next=function(){this.currentItem++;if(this.currentItem>=this.items.length)this.currentItem=0;this.open(this.getCurrentItem())};L.prototype.prevPage=function(){this.page--;this.render(this.page)};L.prototype.nextPage=function(){this.page++;
this.render(this.page)};s.prototype.init=function(){var a=this.settings;this.initFrame();this.initNavigation();this.initCaption();this.initButtons();this.initThumbnails();this.initImage();switch(a.initialState.toLowerCase()){case "show thumbnails":this.showThumbnails();break;default:case "load image":case "show image":this.showImage();break;case "start slideshow":this.showImage(),this.slideshowStart()}};s.prototype.initFrame=function(){var f=this.canvas,b=this.settings,d=this.frame=c("<div></div>"),
l=f.width()-10,e=f.height()-10;d.css({position:"absolute",left:5,top:5,width:l,height:e,overflow:"hidden",background:n(b.buttons.bgColor)});a(d,{borderRadius:"5px",boxShadow:"0 0 4px rgba(0, 0, 0, 0.5)"});var g=this.content=c("<div></div>"),l=this.contentWidth=l-18,e=this.contentHeight=e-43;g.css({position:"absolute",left:9,top:9,width:l,height:e,background:n(b.base.color)});a(g,{borderRadius:"4px"});d.append(g);b=this.preloader=c('<img alt="" />');b.attr("src",o.images.loader);b.css({position:"absolute",
left:"50%",top:"50%",zIndex:100,margin:"-16px 0 0 -16px"});g.append(b);f.append(d)};s.prototype.initNavigation=function(){this.initPrevButton();this.initNextButton()};s.prototype.initPrevButton=function(){var f=this.settings,b=c("<div></div>");b.css({position:"absolute",left:0,top:this.contentHeight/2-20,zIndex:10,width:21,height:60,background:n(f.buttons.bgColor),cursor:"default"});a(b,{borderRadius:"10px",boxShadow:"5px 0 15px rgba(0, 0, 0, 0.5)"});this.frame.append(b);prevOverlay=c("<div></div>");
prevOverlay.css({position:"absolute",left:0,top:this.contentHeight/2-30,zIndex:10,width:9,height:80,background:n(f.buttons.bgColor),cursor:"default"});this.frame.append(prevOverlay);var d=this.prevButton=c('<div><div style="margin:25px 0 0 6px; width:9px; height:9px; background:url('+o.images.folder+'cubic-buttons.png) no-repeat -8px -8px;"></div></div>');d.css({position:"absolute",left:0,top:this.contentHeight/2-20,zIndex:10,width:21,height:60,cursor:"pointer"});this.frame.append(d);var l;this.canvas.element.hover(function(){clearTimeout(l);
b.stop().show().css({opacity:1}).animate({left:0});d.stop().animate({left:0,opacity:1})},function(){l=setTimeout(function(){b.stop().animate({left:-12},function(){b.fadeOut()});d.stop().animate({left:-12,opacity:0})},100)});this.hidePrevButton=function(){b.css({visibility:"hidden"});prevOverlay.css({visibility:"hidden"});d.css({visibility:"hidden"})};this.showPrevButton=function(){b.css({visibility:"visible"});prevOverlay.css({visibility:"visible"});d.css({visibility:"visible"})}};s.prototype.initNextButton=
function(){var f=this.settings,b=c("<div></div>");b.css({position:"absolute",right:0,top:this.contentHeight/2-20,zIndex:10,width:21,height:60,background:n(f.buttons.bgColor),cursor:"default"});a(b,{borderRadius:"10px",boxShadow:"-5px 0 15px rgba(0, 0, 0, 0.5)"});this.frame.append(b);nextOverlay=c("<div></div>");nextOverlay.css({position:"absolute",right:0,top:this.contentHeight/2-30,zIndex:10,width:9,height:80,background:n(f.buttons.bgColor),cursor:"default"});this.frame.append(nextOverlay);var d=
this.nextButton=c('<div><div style="margin:25px 0 0 6px; width:9px; height:9px; background:url('+o.images.folder+'cubic-buttons.png) no-repeat -8px -33px;"></div></div>');d.css({position:"absolute",right:0,top:this.contentHeight/2-20,zIndex:10,width:21,height:60,cursor:"pointer"});this.frame.append(d);var l;this.canvas.element.hover(function(){clearTimeout(l);b.stop().show().css({opacity:1}).animate({right:0});d.stop().animate({right:0,opacity:1})},function(){l=setTimeout(function(){b.stop().animate({right:-12},
function(){b.fadeOut()});d.stop().animate({right:-12,opacity:0})},100)});this.hideNextButton=function(){b.css({visibility:"hidden"});nextOverlay.css({visibility:"hidden"});d.css({visibility:"hidden"})};this.showNextButton=function(){b.css({visibility:"visible"});nextOverlay.css({visibility:"visible"});d.css({visibility:"visible"})}};s.prototype.initCaption=function(){var a=this.caption=c("<div></div>");a.css({position:"absolute",left:10,bottom:10,width:this.contentWidth-60,overflow:"hidden",fontFamily:"Arial, Helvetica, sans-serif",
fontSize:"11px",color:"#777"});this.frame.append(a)};s.prototype.initButtons=function(){var f=this,b=f.settings,d=function(){c(this).css({borderColor:"#fff #bbb #bbb #fff"});a(this,{boxShadow:"0 0 2px rgba(0, 0, 0, 0.2)"})},l=function(){c(this).css({borderColor:"transparent"});a(this,{boxShadow:"none"})};if(b.buttons.showSlideshowButton){var e=f.slideshowButton=c("<div></div>");e.css({position:"absolute",right:b.buttons.showThumbnailsButton?29:5,bottom:5,width:23,height:23,background:w(o.images.folder+
"cubic-buttons.png")+" no-repeat 0px -51px",border:"1px solid",borderColor:"transparent",cursor:"pointer"});a(e,{borderRadius:"3px 4px 3px 4px"});e.hover(d,l);e.click(function(){f.showImage();f.slideshowStart()});f.frame.append(e)}if(b.buttons.showThumbnailsButton)b=f.showThumbnailsButton=c("<div></div>"),b.css({position:"absolute",right:5,bottom:5,width:23,height:23,background:w(o.images.folder+"cubic-buttons.png")+" no-repeat -1px -126px",border:"1px solid",borderColor:"transparent",cursor:"pointer"}).hide(),
a(b,{borderRadius:"3px 4px 3px 4px"}),b.hover(d,l),b.click(function(){f.showThumbnails()}),f.frame.append(b),b=f.showImagesButton=c("<div></div>"),b.css({position:"absolute",right:5,bottom:5,width:23,height:23,background:w(o.images.folder+"cubic-buttons.png")+" no-repeat -1px -101px",border:"1px solid",borderColor:"transparent",cursor:"pointer"}).hide(),a(b,{borderRadius:"3px 4px 3px 4px"}),b.hover(d,l),b.click(function(){f.showImage()}),f.frame.append(b)};s.prototype.initImage=function(){var f=this.imageWidth=
this.contentWidth-2*this.settings.base.visibleEdge,b=this.imageHeight=this.contentHeight-2*this.settings.base.visibleEdge,d=this.imagesFrame=c("<div></div>");d.css({position:"absolute",left:this.settings.base.visibleEdge,top:this.settings.base.visibleEdge,width:f,height:b,overflow:"hidden"}).hide();a(d,{borderRadius:"3px"});this.content.append(d);f=this.imagesContainer=c("<div></div>");f.css({position:"relative",left:0,top:0});d.append(f)};s.prototype.showImage=function(a){var b=this,c=function(){b.cleanup();
b.thumbnailsFrame.hide();b.imagesFrame.show();b.showImagesButton.hide();b.showThumbnailsButton.show();b.showPrevButton();b.showNextButton();b.prevButton.unbind("click").click(function(){b.slideshowStop();b.prev()});b.nextButton.unbind("click").click(function(){b.slideshowStop();b.next()})};!1!==a?(b.hidePrevButton(),b.hideNextButton(),b.open(b.getCurrentItem(),c)):c()};s.prototype.initThumbnails=function(){function f(){b.cleanup()}var b=this,d=b.canvas,l=b.thumbnailsWidth=b.contentWidth-2*b.settings.base.visibleEdge,
e=b.thumbnailsHeight=b.contentHeight-2*b.settings.base.visibleEdge,h=b.thumbnailsFrame=c("<div></div>");h.css({position:"absolute",left:b.settings.base.visibleEdge,top:b.settings.base.visibleEdge,width:l,height:e,overflow:"hidden"}).hide();a(h,{borderRadius:"3px"});b.content.append(h);var i=b.thumbnailsContainer=c("<div></div>");i.css({position:"relative",left:0,top:0});h.append(i);for(var m=Math.round((l-5)/5),k=Math.round((e-4)/4),y=Math.round((l-5*m)/10),u=Math.round((e-4*k)/8),e=0;e<b.items.length;e++)(function(e,
h){g(h.thumb,function(g){var A=e%5,C=Math.floor(e%20/5),j=c('<div class="altgallery-thumbnail altgallery-thumbnail-'+e+'"></div>');j.css({position:"absolute",left:A*m+Math.floor(e/20)*l+1*A+y,top:C*k+1*C+u,width:m,height:k,overflow:"hidden",cursor:"pointer",zIndex:Math.floor(e%20/5)});a(j,{boxShadow:"0px 3px 3px rgba(0, 0, 0, 0.5)"});j.mouseover(function(){if(b.enableThumbnailsHover){var u=0;0==A?u=m/8:4==A&&(u=-m/8);var y=0;0==C?y=k/8:3==C&&(y=-k/8);b.updateCaption(h.description||"Image "+(e+1)+
" / "+b.items.length);b.cleanup();d.element.find(".altgallery-thumbnail").css({opacity:0.8});var j=c(this).clone();j.addClass("altgallery-clone");j.css({left:c(this).offset().left-i.offset().left,top:c(this).offset().top-i.offset().top,zIndex:10,opacity:1});a(j,{boxShadow:"5px 15px 13px rgba(0, 0, 0, 0.7)"});i.append(j);var o=j.find("img");j.animate({width:1.25*m,height:1.25*k,marginLeft:-m/8+u,marginTop:-k/8+y},{duration:"fast",easing:"linear",step:function(){o.css(z.fill(g.width,g.height,j.width(),
j.height()))}});j.click(function(){b.currentItem=e;j.unbind("mouseleave");b.canvas.element.unbind("mouseleave",f);a(j,{boxShadow:"none"});j.animate({left:b.currentPage*l,top:0,width:b.imageWidth,height:b.imageHeight,marginLeft:0,marginTop:0},{duration:"normal",step:function(){o.css(z.fill(g.width,g.height,j.width(),j.height()))},complete:function(){b.showImage()}})});j.mouseleave(function(){b.cleanup();b.updateCaption(" ")})}});j.click(function(){b.currentItem=e;b.showImage()});var o=c('<img style="position:absolute;" />');
o.attr("src",h.thumb);o.css(z.fill(g.width,g.height,m,k));j.append(o);i.append(j)})})(e,b.items[e]);b.canvas.element.mouseleave(f);b.currentPage=0;b.preloader.hide()};s.prototype.showThumbnails=function(){var a=this;a.slideshow&&a.slideshowStop();a.updateCaption(" ");a.imagesFrame.hide();a.thumbnailsFrame.show();a.showThumbnailsButton.hide();a.showImagesButton.show();a.prevButton.unbind("click").click(function(){if(0<a.currentPage)a.currentPage--,a.enableThumbnailsHover=!1,a.cleanup(),a.thumbnailsContainer.stop().animate({left:-a.currentPage*
a.thumbnailsWidth},2*o.animation.duration,function(){a.enableThumbnailsHover=!0});a.updateNavigation()});a.nextButton.unbind("click").click(function(){if(a.currentPage<Math.floor(a.items.length/20))a.currentPage++,a.enableThumbnailsHover=!1,a.cleanup(),a.thumbnailsContainer.stop().animate({left:-a.currentPage*a.thumbnailsWidth},2*o.animation.duration,function(){a.enableThumbnailsHover=!0});a.updateNavigation()});a.updateNavigation()};s.prototype.updateNavigation=function(){var a=Math.ceil(this.items.length/
20);0==this.currentPage?this.hidePrevButton():this.showPrevButton();this.currentPage==a-1?this.hideNextButton():this.showNextButton()};s.prototype.updateCaption=function(a){(a=a||this.getCurrentItem().description)?this.caption.html(a):this.caption.html("Image "+(this.currentItem+1)+" / "+this.items.length)};s.prototype.open=function(a,b){var d=this,l="altgallery-image-"+d.currentItem;d.imagesContainer.find("."+l).size()?"function"==typeof b&&b():(d.preloader.show(),g(a.source,function(a){var f=c('<div class="'+
l+'"></div>');f.css({position:"absolute",left:d.imageWidth*d.currentItem,top:0,width:d.imageWidth,height:d.imageHeight,overflow:"hidden"});var e=c('<img style="position:absolute;" />');e.attr("src",a.src);e.css(z.fill(a.width,a.height,d.imageWidth,d.imageHeight));f.append(e);d.imagesContainer.append(f);d.preloader.hide();"function"==typeof b&&b()}));d.imagesContainer.stop().css({left:-d.imageWidth*d.currentItem});d.updateCaption()};s.prototype.prev=function(){var a=this;if(0<a.currentItem){a.currentItem--;
var b=setTimeout(function(){a.preloader.show()},500);g(a.getCurrentItem().source,function(d){clearTimeout(b);a.preloader.hide();var e="altgallery-image-"+a.currentItem;if(!a.imagesContainer.find("."+e).size()){e=c('<div class="'+e+'"></div>');e.css({position:"absolute",left:a.imageWidth*a.currentItem,top:0,width:a.imageWidth,height:a.imageHeight,overflow:"hidden"});var g=c('<img style="position:absolute;" />');g.attr("src",d.src);g.css(z.fill(d.width,d.height,a.imageWidth,a.imageHeight));e.append(g);
a.imagesContainer.append(e)}a.imagesContainer.stop().animate({left:-a.imageWidth*a.currentItem},2*o.animation.duration);a.updateCaption()})}else a.currentItem=a.items.length-1,a.showImage()};s.prototype.next=function(){var a=this;if(a.currentItem<a.items.length-1){a.currentItem++;var b=setTimeout(function(){a.preloader.show()},500);g(a.getCurrentItem().source,function(d){clearTimeout(b);a.preloader.hide();var e="altgallery-image-"+a.currentItem;if(!a.imagesContainer.find("."+e).size()){e=c('<div class="'+
e+'"></div>');e.css({position:"absolute",left:a.imageWidth*a.currentItem,top:0,width:a.imageWidth,height:a.imageHeight,overflow:"hidden"});var g=c('<img style="position:absolute;" />');g.attr("src",d.src);g.css(z.fill(d.width,d.height,a.imageWidth,a.imageHeight));e.append(g);a.imagesContainer.append(e)}a.imagesContainer.stop().animate({left:-a.imageWidth*a.currentItem},2*o.animation.duration,function(){a.slideshow&&a.slideshowStart()});a.updateCaption()})}else a.currentItem=0,a.showImage(),a.slideshow&&
a.slideshowStart()};s.prototype.slideshowStart=function(){var a=this;a.showImage(!1);clearTimeout(a.slideshowTimer);a.slideshow=!0;a.slideshowButton.css({background:w(o.images.folder+"cubic-buttons.png")+" no-repeat 0px -76px"});a.slideshowButton.unbind("click").click(function(){a.slideshowStop()});a.slideshowTimer=setTimeout(function(){a.next()},1E3*a.settings.slideshowDelay)};s.prototype.slideshowStop=function(){var a=this;a.slideshow=!1;clearTimeout(a.slideshowTimer);a.slideshowButton.css({background:w(o.images.folder+
"cubic-buttons.png")+" no-repeat 0px -51px"});a.slideshowButton.unbind("click").click(function(){a.slideshowStart()})};s.prototype.cleanup=function(){this.canvas.element.find(".altgallery-clone").remove();c(this.canvas.element).find(".altgallery-thumbnail").css({opacity:1})};I.prototype.showScrollbar=function(){var a=this,b=this.settings,d=this.canvas,e=c('<div class="altgallery-scrollbar"></div>'),g=Math.round(0.8*d.width())-36;e.css({position:"absolute",zIndex:1E3,left:(d.width()-g)/2,bottom:5,
width:g+36,height:17,background:H(b.scrollbar.bgColor,b.scrollbar.bgAlpha/100),"-moz-border-radius":8,"-webkit-border-radius":8,borderRadius:8});if(c.browser.msie&&9>c.browser.version){var h=sprintf("%02x%s",255*b.scrollbar.bgAlpha/100,n(b.scrollbar.bgColor).replace("#",""));e.css({filter:"progid:DXImageTransform.Microsoft.gradient(startColorstr=#"+h+",endColorstr=#"+h+")"})}var i=c('<div class="altgallery-scrollbar-handle"></div>'),m=g/a.items.length;i.css({position:"absolute",left:Math.round(a.currentItem*
m),width:Math.floor(m),height:13,background:n(b.scrollbar.handleColor),opacity:b.scrollbar.handleAlpha/100,cursor:"pointer"});i.hover(function(){i.css({opacity:1})},function(){i.css({opacity:b.scrollbar.handleAlpha/100})});h=c("<div></div>");h.css({position:"relative",top:2,height:13,margin:"0 18px"});h.click(function(b){b=b.pageX-c(this).offset().left;a.currentItem=Math.floor(b/g*a.items.length);i.css({left:Math.round(a.currentItem*m)});a.animate()});var k={position:"absolute",top:2,width:16,height:16,
fontFamily:"Arial, Helvetica, sans-serif",fontSize:"10px",lineHeight:"14px",textAlign:"center",color:n(b.scrollbar.arrowsColor),opacity:b.scrollbar.arrowsAlpha/100,cursor:"pointer"},j=c("<div>&#9668;</div>");j.css(k);j.css({left:1});j.click(function(){a.prev()});e.append(j);j=c("<div>&#9658;</div>");j.css(k);j.css({right:1});j.click(function(){a.next()});e.append(j);h.append(i);e.append(h);d.element.append(e)};I.prototype.updateScrollbar=function(){var a=this.canvas,b=(Math.round(0.8*a.width())-36)/
this.items.length;a.element.find(".altgallery-scrollbar-handle").css({left:Math.round(this.currentItem*b)})};I.prototype.getItemStyle=function(a,b){var c=this.settings,d=this.canvas,e,g;e=this.getItemX(b);g=this.getItemZ(b);var i;i=Math.abs(e);var h=z.fit(a.width,a.height,c.maxImageWidth*(1>i?1:2>i?0.55:3>i?0.5:0.6-0.05*i),d.height()-60);return{zIndex:g,left:(d.width()-h.width)/2+e*d.width()/8+(e?e/i*c.maxImageWidth/3:0),top:(d.height()-h.height)/2-30,width:h.width,height:h.height,opacity:e?0.8:1,
transform:{rotateY:-(e?e/i:0)*c.imageAngle+"deg"}}};I.prototype.render=function(){function a(f,i){g(h[f].source,function(a){var g=b.getItemStyle(a,f),k=c('<a class="altgallery-item-'+f+'"></a>');h[f].link&&(k.attr("href",h[f].link),h[f].target&&k.attr("target",h[f].target));k.css({display:"block",position:"absolute",zIndex:g.zIndex,left:g.left,top:g.top,width:g.width,height:g.height,overflow:"visible",background:"#000",cursor:"pointer",outline:"none"});d(k,{rotateY:g.transform.rotateY});var m=c('<img src="" alt="" />');
m.attr("src",a.src);E(m);m.css({display:"block",width:g.width,height:g.height,opacity:g.opacity});k.append(m);if(b.showReflections){a=m.clone();a.css({position:"absolute",opacity:e.reflectionAlpha/100,"-moz-transform":"scaleY(-1)","-webkit-transform":"scaleY(-1)","-o-transform":"scaleY(-1)","-ms-transform":"scaleY(-1)",transform:"scaleY(-1)",zIndex:1});var j=c('<div class="altgallery-overlay"></div>');j.css({position:"absolute",top:g.height,width:g.width,height:g.height,background:l.element.css("backgroundColor"),
zIndex:0});var y=c('<div class="altgallery-overlay"></div>');y.css({position:"absolute",top:g.height,width:g.width,height:g.height,zIndex:2});var g=l.element.css("backgroundColor"),o=[H(g,0),H(g,0.5),H(g,1)];c.browser.mozilla?y.css({background:"-moz-linear-gradient(top, "+o[0]+" 0%, "+o[1]+" 15%, "+o[2]+" 50%)"}):c.browser.webkit?y.css({background:"-webkit-linear-gradient(top, "+o[0]+" 0%, "+o[1]+" 15%, "+o[2]+" 50%)"}):c.browser.opera?y.css({background:"-o-linear-gradient(top, "+o[0]+" 0%, "+o[1]+
" 15%, "+o[2]+" 50%)"}):c.browser.msie?(g=n(g).replace("#",""),y.css({filter:"progid:DXImageTransform.Microsoft.gradient(startColorstr=#00"+g+",endColorstr=#ff"+g+",GradientType=0)"})):y.css({background:"linear-gradient(top, "+o[0]+" 0%, "+o[1]+" 15%, "+o[2]+" 50%)"});k.append(a);k.append(j);k.append(y)}k.click(function(){b.currentItem+=i;if(0>b.currentItem)b.currentItem=0;else if(b.currentItem>=h.length)b.currentItem=h.length-1;b.animate();return!1}).hover(function(){m.css({opacity:1})},function(){m.css({opacity:i?
0.8:1})});f==b.currentItem&&k.unbind("click");b.scene.append(k)})}var b=this,e=this.settings,l=this.canvas,h=this.items;b.scene.empty();b.scene.css({"-webkit-perspective":400,"-moz-perspective":400,perspective:400});var j,i,m,k,y;k=b.currentItem;y=2*Math.max(k,h.length-k);for(j=1;j<=y;j++)i=k+(j%2?parseInt(j/2):-parseInt(j/2)),0<=i&&i<h.length&&(m=b.getItemX(i),a(i,m));e.useScrollBar&&b.showScrollbar();c.browser.mozilla&&b.showReflections&&b.animate()};I.prototype.animate=function(){function a(f,
i){g(e[f].source,function(a){var g=b.scene.find(".altgallery-item-"+f),h=g.find("img"),k={left:parseInt(g.css("left")),top:parseInt(g.css("top")),width:g.width(),height:g.height(),opacity:g.find("img").css("opacity"),transform:d(g)},m=b.getItemStyle(a,f);g.show().css({zIndex:m.zIndex});g.unbind("click").click(function(){b.currentItem+=i;if(0>b.currentItem)b.currentItem=0;else if(b.currentItem>=e.length)b.currentItem=e.length-1;b.animate();return!1}).unbind("hover").hover(function(){h.first().css({opacity:1})},
function(){h.first().css({opacity:i?0.8:1})});h.first().css({opacity:m.opacity});var j=g.find(".altgallery-overlay");g.animate({animate:1E4},{duration:800*c.flipDuration,easing:"easeOutCubic",step:function(a){function c(b){return k[b]+(m[b]-k[b])*a/1E4}g.css({left:Math.round(c("left")),top:Math.round(c("top")),width:Math.round(c("width")),height:Math.round(c("height"))});h.css({width:Math.round(c("width")),height:Math.round(c("height"))});b.showReflections&&j.css({top:Math.round(c("height")),width:Math.round(c("width")),
height:Math.round(c("height"))});d(this,{rotateY:parseInt(k.transform.rotateY)+(parseInt(m.transform.rotateY)-parseInt(k.transform.rotateY))*a/1E4+"deg"})},complete:function(){g.prop("animate",0);f==b.currentItem&&g.unbind("click")}})})}var b=this,c=this.settings,e=this.items,h,j,i,m,k;m=b.currentItem;k=2*Math.max(m,e.length-m);for(h=1;h<=k;h++)j=m+(h%2?parseInt(h/2):-parseInt(h/2)),0<=j&&j<e.length&&(i=b.getItemX(j),a(j,i));c.useScrollBar&&b.updateScrollbar()};I.prototype.showAlbums=function(){};
I.prototype.open=function(){};I.prototype.prev=function(){0<this.currentItem&&(this.currentItem--,this.animate())};I.prototype.next=function(){this.currentItem<this.items.length-1&&(this.currentItem++,this.animate())};v.prototype.render=function(){var a=this,b=this.settings,d=this.canvas;d.element.css({fontFamily:b.fontName,fontSize:parseInt(b.fontSize)+"px",lineHeight:1.2*parseInt(b.fontSize)+"px"});(function(){var e=c('<div class="altgallery-imageFrame"></div>');e.css({width:d.width()-2*b.frameSize,
height:d.height()-2*b.frameSize,padding:b.frameSize,background:n(b.frameColor),borderRadius:b.cornerRadius/2});var g=c('<div class="altgallery-image"></div>');g.css({position:"relative",width:d.width()-2*b.frameSize,height:d.height()-2*b.frameSize,overflow:"hidden",background:n(b.backgroundColor),borderRadius:b.cornerRadius/2-b.frameSize/4,cursor:"pointer"});var h=c('<img src="" alt="" />');E(g.children("img"));h.css({position:"absolute"});e.click(function(){a.next()});g.append(h);e.append(g);d.element.append(e);
a.open(a.getCurrentItem())})();switch(b.initialState.toLowerCase()){default:case "show albums":this.showAlbums();break;case "show thumbnails":this.showThumbnails();case "load image":case "start slideshow":}};v.prototype.showAlbums=function(){function a(){function f(){var a=p*j+1,c=p*j+j;if(c>b.albums.length)c=b.albums.length;B.html(a+"-"+c+" "+e.translation.Of+" "+b.albums.length);0>=p?(n.css({opacity:0.3,cursor:"default"}),n.unbind("click").click(function(){return!1})):(n.css({opacity:1,cursor:"pointer"}),
n.unbind("click").click(r));p>=u-1?(s.css({opacity:0.3,cursor:"default"}),s.unbind("click").click(function(){return!1})):(s.css({opacity:1,cursor:"pointer"}),s.unbind("click").click(v))}b.hideThumbnails();b.hideButtons();b.hideCaption();b.hideNavigation();var h=c('<div class="altgallery-albums"></div>'),i=d.width()-2*e.frameSize,m=e.iconHeight+115;h.css({position:"absolute",left:e.frameSize,top:(d.height()-m)/2,width:d.width()-2*e.frameSize,height:m,overflow:"hidden",color:"#fff",border:"1px #000",
borderStyle:"solid none",zIndex:2});var k=c('<div class="altgallery-albums-overlay"></div>');k.css({position:"absolute",left:e.frameSize,top:(d.height()-m)/2,width:d.width()-2*e.frameSize,height:m+1,background:"#000",opacity:e.panelBackgroundAlpha/100,zIndex:1});d.element.append(k);m=c("<div></div>");m.css({position:"absolute",top:10,right:20});k=c('<a class="altgallery-close" href="#">'+e.translation.Close+"</a>");k.css({marginRight:0,color:"#fff",fontWeight:"bold",textDecoration:"none",textShadow:"0 1px 0 rgba(0, 0, 0, 0.5)",
background:"no-repeat left center",backgroundImage:w(o.images.folder+"zen-close.png"),paddingLeft:12});k.click(function(){b.hideAlbums();b.showButtons();b.showCaption();b.showNavigation();return!1});m.append(k);h.append(m);var j=Math.floor((i-20)/(e.iconWidth+e.iconPadding)),j=j>b.albums.length?b.albums.length:j,m=(e.iconWidth+e.iconPadding)*j-e.iconPadding,k=(e.iconWidth+e.iconPadding)*b.albums.length-e.iconPadding,u=Math.ceil(b.albums.length/j),p=0,q=c("<div>"+e.translation.Albums+"</div>");q.css({position:"absolute",
left:9,top:0,padding:10,paddingLeft:25,textShadow:"-1px 1px 0 rgba(0, 0, 0, 0.5)",fontWeight:"bold",background:"no-repeat left center",backgroundImage:w(o.images.folder+"zen-albums.png")});h.append(q);var B=c("<span></span>");B.css({marginLeft:"1em",fontWeight:"normal"});q.append(B);q=c("<div></div>");q.css({position:"absolute",left:(i-m)/2-4,top:42,width:m+4,height:e.iconHeight+70,overflow:"hidden"});var x=c("<div></div>");x.css({position:"relative",left:0,width:k});q.append(x);i=c("<div></div>");
i.css({position:"absolute",right:4,bottom:3,height:20,opacity:0.9});var n=c('<a href="#" style="float:left;"></a>');n.css({display:"block",cssFloat:"left",width:16,height:16,marginRight:3,background:"no-repeat center",backgroundImage:w(o.images.folder+"zen-prev.png")});var r=function(){p--;var a=(e.iconWidth+e.iconPadding)*j*p;x.stop();x.animate({left:-a},2*o.animation.duration,"easeOutQuart");f();return!1};n.click(r);i.append(n);h.append(q);var s=c('<a href="#" style="float:left;"></a>');s.css({display:"block",
cssFloat:"left",width:16,height:16,marginRight:3,background:"no-repeat center",backgroundImage:w(o.images.folder+"zen-next.png")});var v=function(){p++;var a=(e.iconWidth+e.iconPadding)*j*p;x.stop();x.animate({left:-a},2*o.animation.duration,"easeOutQuart");f();return!1};s.click(v);i.append(s);h.append(i);f();for(i=0;i<b.albums.length;i++)(function(a,d){var f=c("<div></div>");f.css({position:"absolute",left:(e.iconWidth+e.iconPadding)*d,top:0,width:e.iconWidth+e.iconPadding+6,overflow:"hidden",textShadow:"0 1px 0 rgba(0, 0, 0, 0.5)"});
var i=c("<div></div>");i.css({position:"relative",width:e.iconWidth-2,height:e.iconHeight-2,overflow:"hidden",border:"1px solid",borderColor:b.currentAlbum==d?"#000":"#fff",margin:"2px",cursor:"pointer"});g(a.items[0].thumb,function(a){var b=c('<img src="" alt="" />');b.attr("src",a.src);E(b);b.css({position:"absolute"});b.css(z.fill(a.width,a.height,e.iconWidth-2,e.iconHeight-2));i.append(b)},50*d);f.append(i);f.append('<div style="padding:7px 2px 2px; font-weight:bold;">'+(a.description||"Album "+
(d+1))+"<div>");f.append('<div style="padding:1px 2px;">'+a.items.length+" "+(1==a.items.length?e.translation.Image:e.translation.Images)+"<div>");f.hover(function(){i.css({borderWidth:"3px",margin:"0px"})},function(){i.css({borderWidth:"1px",margin:"2px"})}).click(function(){if(b.currentAlbum!=d)b.currentItem=-1;b.currentAlbum=d;b.showThumbnails()});x.append(f)})(b.albums[i],i);d.element.append(h)}var b=this,d=this.canvas,e=this.settings;d.element.find(".altgallery-albums").size()||a()};v.prototype.hideAlbums=
function(){this.canvas.element.find(".altgallery-albums, .altgallery-albums-overlay").remove()};v.prototype.showThumbnails=function(){function a(){function f(){var a=q*u+1,b=q*u+u;if(b>h.items.length)b=h.items.length;x.html(a+"-"+b+" "+e.translation.Of+" "+h.items.length);0>=q?(r.css({opacity:0.3,cursor:"default"}),r.unbind("click").click(function(){return!1})):(r.css({opacity:1,cursor:"pointer"}),r.unbind("click").click(s));q>=p-1?(v.css({opacity:0.3,cursor:"default"}),v.unbind("click").click(function(){return!1})):
(v.css({opacity:1,cursor:"pointer"}),v.unbind("click").click(D))}b.hideAlbums();b.hideButtons();b.hideCaption();b.hideNavigation();var i=c('<div class="altgallery-images"></div>'),m=d.width()-2*e.frameSize,k=e.iconHeight+75;i.css({position:"absolute",left:e.frameSize,top:(d.height()-k)/2,width:d.width()-2*e.frameSize,height:k,overflow:"hidden",color:"#fff",border:"1px #000",borderStyle:"solid none",zIndex:2});var j=c('<div class="altgallery-images-overlay"></div>');j.css({position:"absolute",left:e.frameSize,
top:(d.height()-k)/2,width:d.width()-2*e.frameSize,height:k+1,background:"#000",opacity:e.panelBackgroundAlpha/100,zIndex:1});d.element.append(j);k=c("<div></div>");k.css({position:"absolute",top:10,right:20});1<b.albums.length&&(j=c('<a class="altgallery-back" href="#">'+e.translation.BackToAlbums+"</a>"),j.css({marginRight:"1.5em",color:"#fff",fontWeight:"bold",textDecoration:"none",textShadow:"0 1px 0 rgba(0, 0, 0, 0.5)",background:"no-repeat left center",backgroundImage:w(o.images.folder+"zen-backToAlbums.png"),
paddingLeft:14}),j.click(function(){b.showAlbums();return!1}),k.append(j));j=c('<a class="altgallery-close" href="#">'+e.translation.Close+"</a>");j.css({marginRight:0,color:"#fff",fontWeight:"bold",textDecoration:"none",textShadow:"0 1px 0 rgba(0, 0, 0, 0.5)",background:"no-repeat left center",backgroundImage:w(o.images.folder+"zen-close.png"),paddingLeft:12});j.click(function(){b.hideThumbnails();b.showButtons();b.showCaption();b.showNavigation();return!1});k.append(j);i.append(k);var u=Math.floor((m-
20)/(e.iconWidth+e.iconPadding)),u=u>h.items.length?h.items.length:u,k=(e.iconWidth+e.iconPadding)*u-e.iconPadding,j=(e.iconWidth+e.iconPadding)*h.items.length-e.iconPadding,p=Math.ceil(h.items.length/u),q=0,n=c("<div>"+e.translation.Images+"</div>");n.css({position:"absolute",left:9,top:0,padding:10,paddingLeft:25,textShadow:"-1px 1px 0 rgba(0, 0, 0, 0.5)",fontWeight:"bold",background:"no-repeat left center",backgroundImage:w(o.images.folder+"zen-thumbnails.png")});i.append(n);var x=c("<span></span>");
x.css({marginLeft:"1em",fontWeight:"normal"});n.append(x);n=c("<div></div>");n.css({position:"absolute",left:(m-k)/2-4,top:42,width:k+4,height:e.iconHeight+4,overflow:"hidden"});var F=c("<div></div>");F.css({position:"relative",left:0,width:j});n.append(F);i.append(n);m=c("<div></div>");m.css({position:"absolute",right:4,bottom:3,height:20,opacity:0.9});var r=c('<a href="#" style="float:left;"></a>');r.css({display:"block",cssFloat:"left",width:16,height:16,marginRight:3,background:"no-repeat center",
backgroundImage:w(o.images.folder+"zen-prev.png")});var s=function(){q--;var a=(e.iconWidth+e.iconPadding)*u*q;F.stop();F.animate({left:-a},2*o.animation.duration,"easeOutQuart");f();return!1};r.click(s);m.append(r);var v=c('<a href="#" style="float:left;"></a>');v.css({display:"block",cssFloat:"left",width:16,height:16,marginRight:3,background:"no-repeat center",backgroundImage:w(o.images.folder+"zen-next.png")});var D=function(){q++;var a=(e.iconWidth+e.iconPadding)*u*q;F.stop();F.animate({left:-a},
2*o.animation.duration,"easeOutQuart");f();return!1};v.click(D);m.append(v);i.append(m);f();for(m=0;m<h.items.length;m++)(function(a,d){var f=c("<div></div>");f.css({position:"absolute",left:(e.iconWidth+e.iconPadding)*d,top:0,width:e.iconWidth+e.iconPadding+6,overflow:"hidden",textShadow:"0 1px 0 rgba(0, 0, 0, 0.5)"});var i=c("<div></div>");i.css({position:"relative",width:e.iconWidth-2,height:e.iconHeight-2,overflow:"hidden",border:"1px solid",borderColor:b.currentItem==d?"#000":"#fff",margin:"2px",
cursor:"pointer"});g(a.thumb,function(a){var b=c('<img src="" alt="" />');b.attr("src",a.src);E(b);b.css({position:"absolute"});b.css(z.fill(a.width,a.height,e.iconWidth-2,e.iconHeight-2));i.append(b)},50*d);f.append(i);f.hover(function(){i.css({borderWidth:"3px",margin:"0px"})},function(){i.css({borderWidth:"1px",margin:"2px"})}).click(function(){b.currentItem=d;b.open(b.getCurrentItem())});F.append(f)})(h.items[m],m);d.element.append(i)}var b=this,d=this.canvas,e=this.settings,h=this.getCurrentAlbum();
d.element.find(".altgallery-images").size()||a()};v.prototype.hideThumbnails=function(){this.canvas.element.find(".altgallery-images, .altgallery-images-overlay").remove()};v.prototype.showButtons=function(){function a(){var d=c('<div class="altgallery-buttons"></div>');d.css({position:"absolute",right:b.settings.frameSize,top:25+b.settings.frameSize,padding:"3px 3px 3px 1px",background:"rgba(0, 0, 0, "+b.settings.buttonsBackgroundAlpha/100+")",border:"1px solid rgba(0, 0, 0, 0.8)",borderRight:"none",
"-moz-border-top-left-radius":"3px","-moz-border-bottom-left-radius":"3px","-webkit-border-top-left-radius":"3px","-webkit-border-bottom-left-radius":"3px","border-top-left-radius":"3px","border-bottom-left-radius":"3px"});if(c.browser.msie&&9>c.browser.version){var f=Math.round(255*parseInt(b.settings.buttonsBackgroundAlpha)/100),f=16>f?"0"+f.toString(16):f.toString(16);d.css({borderColor:"#000",filter:"progid:DXImageTransform.Microsoft.gradient(startColorstr=#"+f+"000000,endColorstr=#"+f+"000000)"})}b.settings.showAlbumsButton&&
1<b.albums.length&&(f=c('<a href="#" style="float:left;"></a>'),f.css({display:"block",cssFloat:"left",margin:"0 2px",width:16,height:16,background:"no-repeat center",backgroundImage:w(o.images.folder+"zen-albums.png"),opacity:0.8}),f.click(function(){b.showAlbums();return!1}),d.append(f));b.settings.showThumbnailsButton&&(f=c('<a href="#" style="float:left;"></a>'),f.css({display:"block",cssFloat:"left",margin:"0 2px",width:16,height:16,background:"no-repeat center",backgroundImage:w(o.images.folder+
"zen-thumbnails.png"),opacity:0.8}),f.click(function(){b.showThumbnails();return!1}),d.append(f));b.canvas.element.append(d)}var b=this;if("never"!=b.settings.showButtons.toLowerCase()&&(b.settings.showAlbumsButton||b.settings.showThumbnailsButton))b.canvas.element.find(".altgallery-buttons").size()||a()};v.prototype.hideButtons=function(){this.canvas.element.find(".altgallery-buttons").remove()};v.prototype.showCaption=function(){this.hideCaption();if("never"!=this.settings.showCaption.toLowerCase()&&
(this.getCurrentAlbum()&&this.getCurrentAlbum().description||this.getCurrentItem()&&this.getCurrentItem().description)){var a=c('<div class="altgallery-caption"></div>');a.css({position:"absolute",left:this.settings.frameSize,top:25+this.settings.frameSize,padding:"4px 10px 5px 7px",color:"#fff",textShadow:"-1px 1px 0 rgba(0, 0, 0, 0.3)",background:"rgba(0, 0, 0, "+this.settings.captionBackgroundAlpha/100+")",border:"1px solid rgba(0, 0, 0, 0.8)",borderLeft:"none","-moz-border-top-right-radius":"3px",
"-moz-border-bottom-right-radius":"3px","-webkit-border-top-right-radius":"3px","-webkit-border-bottom-right-radius":"3px","border-top-right-radius":"3px","border-bottom-right-radius":"3px"});if(c.browser.msie&&9>c.browser.version){var b=Math.round(255*parseInt(this.settings.captionBackgroundAlpha)/100),b=16>b?"0"+b.toString(16):b.toString(16);a.css({borderColor:"#000",filter:"progid:DXImageTransform.Microsoft.gradient(startColorstr=#"+b+"000000,endColorstr=#"+b+"000000)"})}this.getCurrentAlbum().description&&
a.append('<div style="font-weight:bold;">'+this.getCurrentAlbum().description+"</div>");this.getCurrentItem().description&&a.append('<div style="">'+this.getCurrentItem().description+"</div>");this.canvas.element.append(a)}};v.prototype.hideCaption=function(){this.canvas.element.find(".altgallery-caption").remove()};v.prototype.showNavigation=function(){function a(){var d=c('<div class="altgallery-navigation"></div>');d.css({position:"absolute",right:b.settings.frameSize,bottom:25+b.settings.frameSize,
padding:"3px 3px 3px 1px",background:"rgba(0, 0, 0, "+b.settings.buttonsBackgroundAlpha/100+")",border:"1px solid rgba(0, 0, 0, 0.8)",borderRight:"none","-moz-border-top-left-radius":"3px","-moz-border-bottom-left-radius":"3px","-webkit-border-top-left-radius":"3px","-webkit-border-bottom-left-radius":"3px","border-top-left-radius":"3px","border-bottom-left-radius":"3px"});if(c.browser.msie&&9>c.browser.version){var f=Math.round(255*parseInt(b.settings.buttonsBackgroundAlpha)/100),f=16>f?"0"+f.toString(16):
f.toString(16);d.css({borderColor:"#000",filter:"progid:DXImageTransform.Microsoft.gradient(startColorstr=#"+f+"000000,endColorstr=#"+f+"000000)"})}b.settings.showNavigationButton&&(f=c('<a href="#" style="float:left;"></a>'),f.css({display:"block",cssFloat:"left",margin:"0 2px",width:16,height:16,background:"no-repeat center",backgroundImage:w(o.images.folder+"zen-prev.png"),opacity:0.8}),f.click(function(){b.prev();return!1}),d.append(f),f=c('<a href="#" style="float:left;"></a>'),f.css({display:"block",
cssFloat:"left",margin:"0 2px",width:16,height:16,background:"no-repeat center",backgroundImage:w(o.images.folder+"zen-next.png"),opacity:0.8}),f.click(function(){b.next();return!1}),d.append(f));b.canvas.element.append(d)}var b=this;"never"!=b.settings.showButtons.toLowerCase()&&b.settings.showNavigationButton&&(b.canvas.element.find(".altgallery-navigation").size()||a())};v.prototype.hideNavigation=function(){this.canvas.element.find(".altgallery-navigation").remove()};v.prototype.open=function(a){var b=
this,d=this.canvas,e=this.settings;b.hideAlbums();b.hideThumbnails();b.showButtons();b.showCaption();b.showNavigation();d.element.find(".altgallery-image img").hide();var h=d.element.find(".altgallery-imageFrame"),j=c('<img class="altgallery-preloader" src="'+o.images.loader+'" alt="" />');E(j);j.css({position:"absolute",left:"50%",top:"50%",zIndex:10,margin:"-16px 0 0 -16px"});g(a.source,function(c){j.hide();d.element.find(".altgallery-preloader").remove();var g=d.element.find(".altgallery-image img");
"fit"==e.imageScaleMode?g.css(z.fit(c.width,c.height,d.width()-2*e.frameSize,d.height()-2*e.frameSize)):g.css(z.fill(c.width,c.height,d.width()-2*e.frameSize,d.height()-2*e.frameSize));g.attr("src",a.source).fadeIn(2*o.animation.duration);b.cache()});setTimeout(function(){d.element.find(".altgallery-preloader").remove();h.append(j)},500)};v.prototype.prev=function(){0<this.currentItem?this.currentItem--:this.currentItem=this.getCurrentAlbum().items.length-1;this.open(this.getCurrentItem())};v.prototype.next=
function(){this.currentItem<this.getCurrentAlbum().items.length-1?this.currentItem++:this.currentItem=0;this.open(this.getCurrentItem())};var o={};c.fn.altgallery=function(a,b){function d(){e.each(function(){W(this,a,b)})}var e=this,a=c.extend(!0,{width:"550px",height:"400px",background:"none",images:{folder:S+"img/",left:"left.png",right:"right.png",close:"close.png",loader:"loader.png"},animation:{duration:500},config:{settings:{}}},a);if(a.images.folder){a.images.folder=a.images.folder.replace(/\/+$/,
"")+"/";for(var g in a.images)"folder"!=g&&!a.images[g].match("/")&&(a.images[g]=a.images.folder+a.images[g])}if("string"==typeof a.config){e.css({visibility:"hidden"});var h={load:function(a,b,c){if(b!==r)switch(b.toLowerCase()){case "xml":this.loadXML(a,c);break;default:case "json":this.loadJSON(a,c)}else a.match(/(xml)$/i)?this.loadXML(a,c):this.loadJSON(a,c)},loadJSON:function(a,b){c.ajax({url:a,dataType:"json",success:function(a){a=h.parse(a);"function"==typeof b&&b(a)},error:function(){"function"==
typeof b&&b({})}})},loadXML:function(a,b){function d(a){var b;"undefined"==typeof b&&(b=function(){});b.ObjTree=function(){return this};b.ObjTree.prototype.attr_prefix="";b.ObjTree.prototype.parseDOM=function(a){if(a){this.__force_array={};if(this.force_array)for(var b=0;b<this.force_array.length;b++)this.__force_array[this.force_array[b]]=1;b=this.parseElement(a);this.__force_array[a.nodeName]&&(b=[b]);if(11!=a.nodeType){var c={};c[a.nodeName]=b;b=c}return b}};b.ObjTree.prototype.parseElement=function(a){if(7!=
a.nodeType){if(3==a.nodeType||4==a.nodeType)return null==a.nodeValue.match(/[^\x00-\x20]/)?void 0:a.nodeValue;var b,c={};if(a.attributes&&a.attributes.length){b={};for(var d=0;d<a.attributes.length;d++){var e=a.attributes[d].nodeName;if("string"==typeof e){var f=a.attributes[d].nodeValue;f&&(e=this.attr_prefix+e,"undefined"==typeof c[e]&&(c[e]=0),c[e]++,this.addNode(b,e,c[e],f))}}}if(a.childNodes&&a.childNodes.length){e=!0;b&&(e=!1);for(d=0;d<a.childNodes.length&&e;d++)f=a.childNodes[d].nodeType,
3==f||4==f||(e=!1);if(e){b||(b="");for(d=0;d<a.childNodes.length;d++)b+=a.childNodes[d].nodeValue}else{b||(b={});for(d=0;d<a.childNodes.length;d++)if(e=a.childNodes[d].nodeName,"string"==typeof e&&(f=this.parseElement(a.childNodes[d])))"undefined"==typeof c[e]&&(c[e]=0),c[e]++,this.addNode(b,e,c[e],f)}}return b}};b.ObjTree.prototype.addNode=function(a,b,c,d){this.__force_array[b]?(1==c&&(a[b]=[]),a[b][a[b].length]=d):1==c?a[b]=d:2==c?a[b]=[a[b],d]:a[b][a[b].length]=d};b=new b.ObjTree;b.attr_prefix=
"";return b.parseDOM(a)["#document"]}c.ajax({url:a,dataType:"xml",success:function(a){a=d(a);a=h.parse(a);"function"==typeof b&&b(a)},error:function(){"function"==typeof b&&b({})}})},parse:function(a){if(a.gallery){if(a.galleryName)a.gallery.galleryName=a.galleryName;a=a.gallery;if(a.items&&a.items.item)a.items=a.items.item.length?a.items.item:[a.items.item];if(a.albums){if(a.albums.album)a.albums=a.albums.album.length?a.albums.album:[a.albums.album];for(var b=0;b<a.albums.length;b++)if(a.albums[b].items.item)a.albums[b].items=
a.albums[b].items.item.length?a.albums[b].items.item:[a.albums[b].items.item]}}return a}};h.load(a.config,a.configType,function(b){e.css({visibility:"visible"});a.config=b;d()})}else d();return this};c.altbox=function(a,b){if(d!=top)var d=top,e=d.document;b=c.extend(!0,{frame:{color:"#000",borderRadius:0},mask:{color:"#000",opacity:0.7},images:{folder:S+"img/",close:"close.png",loader:"loader.gif"},animation:{duration:700}},b);if(b.images.folder){b.images.folder=b.images.folder.replace(/\/+$/,"")+
"/";for(var g in b.images)"folder"!=g&&!b.images[g].match("/")&&(b.images[g]=b.images.folder+b.images[g])}var h=c('<div style="position:fixed; z-index:999; left:0; top:0; width:100%; height:100%; background:no-repeat center;"></div>');h.css({opacity:0,backgroundColor:b.mask.color,backgroundImage:w(b.images.loader)});c(e.body).append(h);h.animate({opacity:b.mask.opacity},b.animation.duration);var i=new Image;i.onload=function(){function g(){h.remove();q.remove()}var j=c(d).width()-100,o=c(d).height()-
100,n=z.fit(i.width/4,i.height/4,j,o,{noEnlarge:!0,minWidth:100,minHeight:100});n.left+=50;n.top+=50;var p=z.fit(i.width+20,i.height+20,j,o,{noEnlarge:!0,minWidth:120,minHeight:120});p.left+=50;p.top+=50;var q=c('<div style="position:fixed; z-index:1000;"></div>');q.css(n);q.css({backgroundColor:b.frame.color,borderRadius:b.frame.borderRadius,MozUserSelect:"none",webkitUserSelect:"none",userSelect:"none"});q.hide();var r=c('<img src="'+a+'" alt="" style="display:block;" />');r.css({margin:"10px",
width:n.width-20,height:n.height-20,borderRadius:8<b.frame.borderRadius?b.frame.borderRadius-8:0});var s=c('<a href="#" style="display:block; position:absolute; right:-12px; top:-10px; width:30px; height:30px; background:no-repeat center;"></a>');s.css({backgroundImage:w(b.images.close)});q.append(r);c(e.body).append(q);(function(){h.css({backgroundImage:"none"});r.animate({width:p.width-20,height:p.height-20,margin:"10px"},b.animation.duration,"easeOutBack");p.opacity="show";q.animate(p,b.animation.duration,
"easeOutBack",function(){q.append(s)})})();c(d).resize(function(){j=c(d).width()-100;o=c(d).height()-100;n=z.fit(i.width/4,i.height/4,j,o,{noEnlarge:!0,minWidth:100,minHeight:100});n.left+=50;n.top+=50;p=z.fit(i.width+20,i.height+20,j,o,{noEnlarge:!0,minWidth:120,minHeight:120});p.left+=50;p.top+=50;q.css(p);r.css({width:p.width-20,height:p.height-20})});h.click(g);s.click(function(){s.remove();n.opacity="hide";q.animate(n,0.67*b.animation.duration);r.animate({width:n.width-20,height:n.height-20},
0.67*b.animation.duration);h.fadeOut(b.animation.duration,function(){g()});return!1})};i.src=a}})(jQuery);
