/**
 * altgallery, jQuery Plugin
 *
 * @version 0.4.2
 * @copyright 2011 Flash-Gallery.com
 */

jQuery.effects||function(b,r){function F(f){var a;return f&&f.constructor==Array&&3==f.length?f:(a=/rgb\(\s*([0-9]{1,3})\s*,\s*([0-9]{1,3})\s*,\s*([0-9]{1,3})\s*\)/.exec(f))?[parseInt(a[1],10),parseInt(a[2],10),parseInt(a[3],10)]:(a=/rgb\(\s*([0-9]+(?:\.[0-9]+)?)\%\s*,\s*([0-9]+(?:\.[0-9]+)?)\%\s*,\s*([0-9]+(?:\.[0-9]+)?)\%\s*\)/.exec(f))?[2.55*parseFloat(a[1]),2.55*parseFloat(a[2]),2.55*parseFloat(a[3])]:(a=/#([a-fA-F0-9]{2})([a-fA-F0-9]{2})([a-fA-F0-9]{2})/.exec(f))?[parseInt(a[1],16),parseInt(a[2],
16),parseInt(a[3],16)]:(a=/#([a-fA-F0-9])([a-fA-F0-9])([a-fA-F0-9])/.exec(f))?[parseInt(a[1]+a[1],16),parseInt(a[2]+a[2],16),parseInt(a[3]+a[3],16)]:/rgba\(0, 0, 0, 0\)/.exec(f)?w.transparent:w[b.trim(f).toLowerCase()]}function A(){var b=document.defaultView?document.defaultView.getComputedStyle(this,null):this.currentStyle,a={},d,e;if(b&&b.length&&b[0]&&b[b[0]])for(var g=b.length;g--;)d=b[g],"string"==typeof b[d]&&(e=d.replace(/\-(\w)/g,function(a,b){return b.toUpperCase()}),a[e]=b[d]);else for(d in b)"string"===
typeof b[d]&&(a[d]=b[d]);return a}function B(f){var a,d;for(a in f)d=f[a],(null==d||b.isFunction(d)||a in G||/scrollbar/.test(a)||!/color/i.test(a)&&isNaN(parseFloat(d)))&&delete f[a];return f}function H(b,a){var d={_:0},e;for(e in a)b[e]!=a[e]&&(d[e]=a[e]);return d}function u(f,a,d,e){if("object"==typeof f)e=a,d=null,a=f,f=a.effect;b.isFunction(a)&&(e=a,d=null,a={});if("number"==typeof a||b.fx.speeds[a])e=d,d=a,a={};b.isFunction(d)&&(e=d,d=null);a=a||{};d=d||a.duration;d=b.fx.off?0:"number"==typeof d?
d:d in b.fx.speeds?b.fx.speeds[d]:b.fx.speeds._default;e=e||a.complete;return[f,a,d,e]}function D(f){return!f||"number"===typeof f||b.fx.speeds[f]||"string"===typeof f&&!b.effects[f]?!0:!1}b.effects={};b.each("backgroundColor,borderBottomColor,borderLeftColor,borderRightColor,borderTopColor,borderColor,color,outlineColor".split(","),function(f,a){b.fx.step[a]=function(d){if(!d.colorInit){var f;f=d.elem;var g=a,k;do{k=b.curCSS(f,g);if(""!=k&&"transparent"!=k||b.nodeName(f,"body"))break;g="backgroundColor"}while(f=
f.parentNode);f=F(k);d.start=f;d.end=F(d.end);d.colorInit=!0}d.elem.style[a]="rgb("+Math.max(Math.min(parseInt(d.pos*(d.end[0]-d.start[0])+d.start[0],10),255),0)+","+Math.max(Math.min(parseInt(d.pos*(d.end[1]-d.start[1])+d.start[1],10),255),0)+","+Math.max(Math.min(parseInt(d.pos*(d.end[2]-d.start[2])+d.start[2],10),255),0)+")"}});var w={aqua:[0,255,255],azure:[240,255,255],beige:[245,245,220],black:[0,0,0],blue:[0,0,255],brown:[165,42,42],cyan:[0,255,255],darkblue:[0,0,139],darkcyan:[0,139,139],
darkgrey:[169,169,169],darkgreen:[0,100,0],darkkhaki:[189,183,107],darkmagenta:[139,0,139],darkolivegreen:[85,107,47],darkorange:[255,140,0],darkorchid:[153,50,204],darkred:[139,0,0],darksalmon:[233,150,122],darkviolet:[148,0,211],fuchsia:[255,0,255],gold:[255,215,0],green:[0,128,0],indigo:[75,0,130],khaki:[240,230,140],lightblue:[173,216,230],lightcyan:[224,255,255],lightgreen:[144,238,144],lightgrey:[211,211,211],lightpink:[255,182,193],lightyellow:[255,255,224],lime:[0,255,0],magenta:[255,0,255],
maroon:[128,0,0],navy:[0,0,128],olive:[128,128,0],orange:[255,165,0],pink:[255,192,203],purple:[128,0,128],violet:[128,0,128],red:[255,0,0],silver:[192,192,192],white:[255,255,255],yellow:[255,255,0],transparent:[255,255,255]},I=["add","remove","toggle"],G={border:1,borderBottom:1,borderColor:1,borderLeft:1,borderRight:1,borderTop:1,borderWidth:1,margin:1,padding:1};b.effects.animateClass=function(f,a,d,e){b.isFunction(d)&&(e=d,d=null);return this.queue(function(){var g=b(this),k=g.attr("style")||
" ",n=B(A.call(this)),u,r=g.attr("class");b.each(I,function(a,b){if(f[b])g[b+"Class"](f[b])});u=B(A.call(this));g.attr("class",r);g.animate(H(n,u),{queue:!1,duration:a,easing:d,complete:function(){b.each(I,function(a,b){if(f[b])g[b+"Class"](f[b])});"object"==typeof g.attr("style")?(g.attr("style").cssText="",g.attr("style").cssText=k):g.attr("style",k);e&&e.apply(this,arguments);b.dequeue(this)}})})};b.fn.extend({_addClass:b.fn.addClass,addClass:function(f,a,d,e){return a?b.effects.animateClass.apply(this,
[{add:f},a,d,e]):this._addClass(f)},_removeClass:b.fn.removeClass,removeClass:function(f,a,d,e){return a?b.effects.animateClass.apply(this,[{remove:f},a,d,e]):this._removeClass(f)},_toggleClass:b.fn.toggleClass,toggleClass:function(f,a,d,e,g){return"boolean"==typeof a||a===r?d?b.effects.animateClass.apply(this,[a?{add:f}:{remove:f},d,e,g]):this._toggleClass(f,a):b.effects.animateClass.apply(this,[{toggle:f},a,d,e])},switchClass:function(f,a,d,e,g){return b.effects.animateClass.apply(this,[{add:a,
remove:f},d,e,g])}});b.extend(b.effects,{version:"1.8.16",save:function(b,a){for(var d=0;d<a.length;d++)null!==a[d]&&b.data("ec.storage."+a[d],b[0].style[a[d]])},restore:function(b,a){for(var d=0;d<a.length;d++)null!==a[d]&&b.css(a[d],b.data("ec.storage."+a[d]))},setMode:function(b,a){"toggle"==a&&(a=b.is(":hidden")?"show":"hide");return a},getBaseline:function(b,a){var d,e;switch(b[0]){case "top":d=0;break;case "middle":d=0.5;break;case "bottom":d=1;break;default:d=b[0]/a.height}switch(b[1]){case "left":e=
0;break;case "center":e=0.5;break;case "right":e=1;break;default:e=b[1]/a.width}return{x:e,y:d}},createWrapper:function(f){if(f.parent().is(".ui-effects-wrapper"))return f.parent();var a={width:f.outerWidth(!0),height:f.outerHeight(!0),"float":f.css("float")},d=b("<div></div>").addClass("ui-effects-wrapper").css({fontSize:"100%",background:"transparent",border:"none",margin:0,padding:0}),e=document.activeElement;f.wrap(d);(f[0]===e||b.contains(f[0],e))&&b(e).focus();d=f.parent();"static"==f.css("position")?
(d.css({position:"relative"}),f.css({position:"relative"})):(b.extend(a,{position:f.css("position"),zIndex:f.css("z-index")}),b.each(["top","left","bottom","right"],function(b,d){a[d]=f.css(d);isNaN(parseInt(a[d],10))&&(a[d]="auto")}),f.css({position:"relative",top:0,left:0,right:"auto",bottom:"auto"}));return d.css(a).show()},removeWrapper:function(f){var a,d=document.activeElement;return f.parent().is(".ui-effects-wrapper")?(a=f.parent().replaceWith(f),(f[0]===d||b.contains(f[0],d))&&b(d).focus(),
a):f},setTransition:function(f,a,d,e){e=e||{};b.each(a,function(a,b){unit=f.cssUnit(b);0<unit[0]&&(e[b]=unit[0]*d+unit[1])});return e}});b.fn.extend({effect:function(f,a,d,e){var g=u.apply(this,arguments),k={options:g[1],duration:g[2],callback:g[3]},g=k.options.mode,n=b.effects[f];return b.fx.off||!n?g?this[g](k.duration,k.callback):this.each(function(){k.callback&&k.callback.call(this)}):n.call(this,k)},_show:b.fn.show,show:function(b){if(D(b))return this._show.apply(this,arguments);var a=u.apply(this,
arguments);a[1].mode="show";return this.effect.apply(this,a)},_hide:b.fn.hide,hide:function(b){if(D(b))return this._hide.apply(this,arguments);var a=u.apply(this,arguments);a[1].mode="hide";return this.effect.apply(this,a)},__toggle:b.fn.toggle,toggle:function(f){if(D(f)||"boolean"===typeof f||b.isFunction(f))return this.__toggle.apply(this,arguments);var a=u.apply(this,arguments);a[1].mode="toggle";return this.effect.apply(this,a)},cssUnit:function(f){var a=this.css(f),d=[];b.each(["em","px","%",
"pt"],function(b,f){0<a.indexOf(f)&&(d=[parseFloat(a),f])});return d}});b.easing.jswing=b.easing.swing;b.extend(b.easing,{def:"easeOutQuad",swing:function(f,a,d,e,g){return b.easing[b.easing.def](f,a,d,e,g)},easeInQuad:function(b,a,d,e,g){return e*(a/=g)*a+d},easeOutQuad:function(b,a,d,e,g){return-e*(a/=g)*(a-2)+d},easeInOutQuad:function(b,a,d,e,g){return 1>(a/=g/2)?e/2*a*a+d:-e/2*(--a*(a-2)-1)+d},easeInCubic:function(b,a,d,e,g){return e*(a/=g)*a*a+d},easeOutCubic:function(b,a,d,e,g){return e*((a=
a/g-1)*a*a+1)+d},easeInOutCubic:function(b,a,d,e,g){return 1>(a/=g/2)?e/2*a*a*a+d:e/2*((a-=2)*a*a+2)+d},easeInQuart:function(b,a,d,e,g){return e*(a/=g)*a*a*a+d},easeOutQuart:function(b,a,d,e,g){return-e*((a=a/g-1)*a*a*a-1)+d},easeInOutQuart:function(b,a,d,e,g){return 1>(a/=g/2)?e/2*a*a*a*a+d:-e/2*((a-=2)*a*a*a-2)+d},easeInQuint:function(b,a,d,e,g){return e*(a/=g)*a*a*a*a+d},easeOutQuint:function(b,a,d,e,g){return e*((a=a/g-1)*a*a*a*a+1)+d},easeInOutQuint:function(b,a,d,e,g){return 1>(a/=g/2)?e/2*
a*a*a*a*a+d:e/2*((a-=2)*a*a*a*a+2)+d},easeInSine:function(b,a,d,e,g){return-e*Math.cos(a/g*(Math.PI/2))+e+d},easeOutSine:function(b,a,d,e,g){return e*Math.sin(a/g*(Math.PI/2))+d},easeInOutSine:function(b,a,d,e,g){return-e/2*(Math.cos(Math.PI*a/g)-1)+d},easeInExpo:function(b,a,d,e,g){return 0==a?d:e*Math.pow(2,10*(a/g-1))+d},easeOutExpo:function(b,a,d,e,g){return a==g?d+e:e*(-Math.pow(2,-10*a/g)+1)+d},easeInOutExpo:function(b,a,d,e,g){return 0==a?d:a==g?d+e:1>(a/=g/2)?e/2*Math.pow(2,10*(a-1))+d:e/
2*(-Math.pow(2,-10*--a)+2)+d},easeInCirc:function(b,a,d,e,g){return-e*(Math.sqrt(1-(a/=g)*a)-1)+d},easeOutCirc:function(b,a,d,e,g){return e*Math.sqrt(1-(a=a/g-1)*a)+d},easeInOutCirc:function(b,a,d,e,g){return 1>(a/=g/2)?-e/2*(Math.sqrt(1-a*a)-1)+d:e/2*(Math.sqrt(1-(a-=2)*a)+1)+d},easeInElastic:function(b,a,d,e,g){var b=1.70158,k=0,n=e;if(0==a)return d;if(1==(a/=g))return d+e;k||(k=0.3*g);n<Math.abs(e)?(n=e,b=k/4):b=k/(2*Math.PI)*Math.asin(e/n);return-(n*Math.pow(2,10*(a-=1))*Math.sin((a*g-b)*2*Math.PI/
k))+d},easeOutElastic:function(b,a,d,e,g){var b=1.70158,k=0,n=e;if(0==a)return d;if(1==(a/=g))return d+e;k||(k=0.3*g);n<Math.abs(e)?(n=e,b=k/4):b=k/(2*Math.PI)*Math.asin(e/n);return n*Math.pow(2,-10*a)*Math.sin((a*g-b)*2*Math.PI/k)+e+d},easeInOutElastic:function(b,a,d,e,g){var b=1.70158,k=0,n=e;if(0==a)return d;if(2==(a/=g/2))return d+e;k||(k=g*0.3*1.5);n<Math.abs(e)?(n=e,b=k/4):b=k/(2*Math.PI)*Math.asin(e/n);return 1>a?-0.5*n*Math.pow(2,10*(a-=1))*Math.sin((a*g-b)*2*Math.PI/k)+d:0.5*n*Math.pow(2,
-10*(a-=1))*Math.sin((a*g-b)*2*Math.PI/k)+e+d},easeInBack:function(b,a,d,e,g,k){k==r&&(k=1.70158);return e*(a/=g)*a*((k+1)*a-k)+d},easeOutBack:function(b,a,d,e,g,k){k==r&&(k=1.70158);return e*((a=a/g-1)*a*((k+1)*a+k)+1)+d},easeInOutBack:function(b,a,d,e,g,k){k==r&&(k=1.70158);return 1>(a/=g/2)?e/2*a*a*(((k*=1.525)+1)*a-k)+d:e/2*((a-=2)*a*(((k*=1.525)+1)*a+k)+2)+d},easeInBounce:function(f,a,d,e,g){return e-b.easing.easeOutBounce(f,g-a,0,e,g)+d},easeOutBounce:function(b,a,d,e,g){return(a/=g)<1/2.75?
e*7.5625*a*a+d:a<2/2.75?e*(7.5625*(a-=1.5/2.75)*a+0.75)+d:a<2.5/2.75?e*(7.5625*(a-=2.25/2.75)*a+0.9375)+d:e*(7.5625*(a-=2.625/2.75)*a+0.984375)+d},easeInOutBounce:function(f,a,d,e,g){return a<g/2?0.5*b.easing.easeInBounce(f,2*a,0,e,g)+d:0.5*b.easing.easeOutBounce(f,2*a-g,0,e,g)+0.5*e+d}})}(jQuery);
(function(b,r){function F(a){return"object"==typeof a&&a.length!==r}function A(a){if(location.href.match(/#jsgallerydebug$/)){var c=b("#debug"),a="object"==typeof a?JSON.stringify(a):a;c.size()?c.append("<div>"+a+"</div>"):alert("JavaScript Gallery:\n\n"+a+"\n")}}function B(a){b(a).css({display:"block",position:"static",cssFloat:"none",clear:"none",left:"auto",right:"auto",top:"auto",bottom:"auto",width:"auto",height:"auto",minWidth:"none",minHeight:"none",maxWidth:"none",maxHeight:"none",overflow:"visible",
margin:0,padding:0,border:"none",background:"none",color:"#000000",fontFamily:"serif",fontSize:"16px",fontStyle:"normal",fontVariant:"normal",fontWeight:"normal",letterSpacing:"normal",lineHeight:"normal",opacity:1,outline:"none",textAlign:"left",textIndent:0,textShadow:"none",visibility:"visible",whiteSpace:"normal",cursor:"inherit"})}function H(){var a=document.getElementsByTagName("script");return a[a.length-1].src||location.href}function u(a){return'url("'+a+'")'}function D(a){var c=[],b,h;for(b=
0;b<a.length;b++)for(h=0;h<a[b].items.length;h++)c.push(a[b].items[h]);return c}function w(a){if("number"==typeof a)return"#"+sprintf("%06x",a);if("string"==typeof a){var c;return(c=a.match(/[0-9a-f]{3,6}$/i))?3==c[0].length?"#"+c[0]+c[0]+c[1]+c[1]+c[2]+c[2]:"#"+c[0]:(c=a.match(/rgb\(\s*(\d+)\s*,\s*(\d+)\s*,\s*(\d+)\s*\)/i))?"#"+parseInt(c[1]).toString(16)+parseInt(c[2]).toString(16)+parseInt(c[3]).toString(16):a}}function I(a){return w(a).match(/[0-9a-f]{6}$/i)?!0:!1}function G(a,c){for(var a=w(a),
b=a.match(/#([0-9a-f]{2})([0-9a-f]{2})([0-9a-f]{2})/),h=[],d=1;3>=d;d++)h.push(parseInt(b[d],16));return c!==r?"rgba("+h[0]+", "+h[1]+", "+h[2]+", "+c+")":"rgb("+h[0]+", "+h[1]+", "+h[2]+")"}function f(a){for(var c in a)"object"==typeof a[c]?a[c]=f(a[c]):"true"==a[c]?a[c]=!0:"false"==a[c]?a[c]=!1:a[c]==parseInt(a[c])&&(a[c]=parseInt(a[c]));return a}function a(a,c){if(c===r)return c={},b(a).data("transform")||{};b(a).each(function(){var a=[],h;for(h in c)a.push(h+"("+c[h]+")");a=a.join(" ");b(this).data("transform",
c).css({"-moz-transform":a,"-webkit-transform":a,"-khtml-transform":a,"-o-transform":a,"-ms-transform":a,transform:a})});return b(a)}function d(a,c,b){A("loadImage: request: "+a);b===r&&"number"==typeof c&&(b=c,c=r);b=b||10;if(a&&v[a]===r){var h=new Image;v[a]=h;v[a].loaded=!1;v[a].callbacks=[];"function"==typeof c&&(A("loadImage: added callback for "+a),v[a].callbacks.push(c));setTimeout(function(){h.onload=function(){v[a].loaded=!0;A("loadImage: executing "+v[a].callbacks.length+" callbacks for "+
a);for(var c=0;c<v[a].callbacks.length;c++)v[a].callbacks[c](v[a])};A("loadImage: GET: "+a);h.src=a},b)}else v[a].loaded?"function"==typeof c&&(A("loadImage: added callback for "+a),c(v[a])):"function"==typeof c&&(A("loadImage: added callback for "+a),v[a].callbacks.push(c))}function e(a,c,z,h){z===r&&"number"==typeof c&&(z=c,c=r);z=z||10;if("string"==typeof a)return d(a,c,z);if(F(a)){var h=h||[],J=a.slice();setTimeout(function(){var a=J.shift(),a="string"==typeof a?a:a.source||a.src||b(a).attr("src");
d(a,function(a){J.length?(h.push(a),e(J,c,z,h)):"function"==typeof c&&c(h)})},z)}}function g(a,c){this.init=function(){var d=b('<div class="altgallery-canvas"></div>');B(d);d.css({display:"block",position:"relative",width:c.width,height:c.height,cursor:"default","-moz-user-select":"none","-webkit-user-select":"none","-khtml-user-select":"none",userSelect:"none"});this.element=b("<div></div>");this.element.css({display:"block",position:"relative",width:c.width,height:c.height,overflow:"hidden",margin:0,
padding:0,background:c.background});d.append(this.element);b(a).empty().append(d)};this.init();this.empty=function(){this.element.empty()};this.width=function(a){return this.element.width(a)};this.height=function(a){return this.element.height(a)};this.drawImage=function(a,c,d){var c=b.extend({left:0,top:0,width:120,height:90,scaleMode:"fill",background:"none"},c),d=d===r?this.element:b(d,this.element),i=new Image;i.onload=function(){var t=document.createElement("a");b(t).attr({href:a.source});b(t).css({display:"block",
position:"absolute",left:c.x,top:c.y,zIndex:c.z,width:c.width,height:c.height,overflow:"hidden",background:c.background});b(t).click(c.onclick);b(t).hover(c.onmouseover,c.onmouseout);var e=document.createElement("img");e.src=i.src;var j;"fit"==c.scaleMode?j=y.fit(this.width,this.height,c.width,c.height):"fill"==c.scaleMode&&(j=y.fill(this.width,this.height,c.width,c.height));b(e).css({marginTop:j.top,marginRight:0,marginBottom:0,marginLeft:j.left,width:j.width,height:j.height,padding:0,border:"none",
maxWidth:"none",maxHeight:"none",opacity:c.opacity});b(t).append(e);d.append(t)};i.src=a.thumb}}function k(a,c,d){this.canvas=a;this.albums=c;this.items=D(c);this.currentItem=0;this.getCurrentItem=function(){return this.items[this.currentItem]};this.settings=b.extend(!0,{image:{scaleMode:"fit",cornerRadius:10,align:"center",transitionEffect:"fade",transitionDuration:1,useShadow:!0},thumbBar:{useThumbBar:!0,position:"bottom",scrollSpeed:10},thumbnail:{width:80,height:60,cornerRadius:10,alpha:70,outlineColor:3355443,
outlineColorOnRollOver:6710886,outlineColorOnClick:10066329,useShadow:!0}},d);this.settings=f(this.settings);(new Image).src=q.images.loader;this.render()}function n(a,c,z){this.canvas=a;this.albums=c;this.items=D(c);this.currentItem=-1;this.getCurrentItem=function(){return this.items[this.currentItem]};this.settings=b.extend(!0,{thumbnail:{width:120,height:90,alpha:85},colorScheme:{imageBGColor:1118481}},z);this.settings=f(this.settings);this.page=0;d(q.images.loader,500);this.render()}function C(a,
c,d){this.canvas=a;this.albums=c;this.settings=b.extend(!0,{imageAngle:30,maxImageWidth:0,useHighlight:!0,useScrollBar:!0,showReflections:!0,solidReflection:!0,reflectionAlpha:80,slideShow:!1,slideShowDelay:2,flipDuration:1,startPosition:"center",colorScheme:"custom",preloader:{stripesAlpha:45,barColor:0,barAlpha:30,bgColor:0,bgAlpha:20,innerShadow:20,dropShadow:30},scrollbar:{bgColor:0,bgAlpha:40,handleColor:0,handleAlpha:40,arrowsColor:0,arrowsAlpha:40,innerShadow:20,dropShadow:20},caption:{textColor:16777215,
bgColor:0,bgAlpha:80,frameColor:16777215,frameAlpha:40,shadowAlpha:50,multilingual:!1,multilingualFontSize:12},background:{bgColor:16777215,transparentBG:!0}},d);this.settings=f(this.settings);if(!this.settings.maxImageWidth)this.settings.maxImageWidth=parseInt(a.element.width()/2);this.showReflections=this.settings.showReflections&&I(this.canvas.element.css("backgroundColor"));this.items=D(c);this.currentItem=0;this.getCurrentItem=function(){return this.items[this.currentItem]};this.getItemX=function(a){return-(this.currentItem-
a)};this.getItemZ=function(a){return parseInt(this.items.length/2)-Math.abs(this.getItemX(a))};this.currentItem="left"==this.settings.startPosition?0:"right"==this.settings.startPosition?this.items.length:Math.floor((this.items.length-1)/2);(new Image).src=q.images.loader;this.scene=b('<div class="altgallery-scene"></div>');this.scene.css({position:"relative",width:a.width(),height:a.height()});this.canvas.element.append(this.scene);this.render()}function s(a,c,z){this.canvas=a;this.albums=c;this.currentAlbum=
0;this.getCurrentAlbum=function(){return this.albums[this.currentAlbum]};this.currentItem=0;this.getCurrentItem=function(){return this.getCurrentAlbum().items[this.currentItem]};this.settings=b.extend(!0,{initialState:"Show Albums",imageScaleMode:"fill",frameSize:5,frameColor:"#ffffff",backgroundColor:"#aac5d8",cornerRadius:7,iconWidth:90,iconHeight:55,iconPadding:10,panelBackgroundAlpha:50,showCaption:"always",captionBackgroundAlpha:40,showButtons:"always",buttonsBackgroundAlpha:40,showAlbumsButton:!0,
showThumbnailsButton:!0,showSlideshowButton:!0,showNavigationButton:!0,useEmbeddedFont:!0,fontName:"Arial",fontSize:11,translation:{Album:"Album",Albums:"Albums",Image:"Image",Images:"Images",Close:"CLOSE",BackToAlbums:"BACK TO ALBUMS",LoadingImage:"Loading Image",Of:"of"}},z);this.settings=f(this.settings);if(this.settings.useEmbeddedFont)this.settings.fontName="Tahoma",this.settings.fontSize=9;d(q.images.loader,500);this.cache=function(){if(0<=this.currentItem){var a=this.getCurrentAlbum().items,
c=[],b,d;for(d=this.currentItem+1;d<this.currentItem+3;d++)(b=a[(a.length+d)%a.length])&&(b=b.source)&&c.push(b);for(d=this.currentItem-1;d>this.currentItem-2;d--)(b=a[(a.length+d)%a.length])&&(b=b.source)&&c.push(b);A("Caching images: "+JSON.stringify(c));c.length&&e(c,100)}};this.render()}function N(a,c){function d(){function a(c){if(c.match(/Art/i))return"art";if(c.match(/Box/i))return"box";if(c.match(/PhotoFlow/i))return"photoflow";if(c.match(/Zen/i))return"zen"}switch(c.type?c.type.toLowerCase():
h.galleryName?c.type=a(h.galleryName):c.type="box"){case "art":case "promo":new k(i,e,h.settings||{});break;default:case "box":new n(i,e,h.settings||{});break;case "photoflow":new C(i,e,h.settings||{});break;case "zen":new s(i,e,h.settings||{})}}a=b(a);q=c;var h,e,i;h=c.config||{};(function(){function c(a,b,d){e.push({id:b||0,description:d,items:a})}e=[];if(F(h.albums)&&h.albums.length)for(var d=0;d<h.albums.length;d++)c(h.albums[d].items,d,h.albums[d].description);else F(h.items)&&h.items.length?
c(h.items):c(function(a){var c=[];b(a).find("img").each(function(){c.push({source:b(this).parent("a").attr("href")||b(this).attr("src"),thumb:b(this).attr("src"),description:this.title})});return c}(a),0)})();i=new g(a,c);b(document).ready(function(){setTimeout(function(){d()},100)})}sprintfWrapper={init:function(){if("undefined"==typeof arguments||1>arguments.length||"string"!=typeof arguments[0]||"undefined"==typeof RegExp)return null;for(var a=arguments[0],c=RegExp(/(%([%]|(\-)?(\+|\x20)?(0)?(\d+)?(\.(\d)?)?([bcdfosxX])))/g),
b=[],d=[],e=0,i=0,o=0,i=0,l="",j=null;j=c.exec(a);)j[9]&&(e+=1),o=c.lastIndex-j[0].length,d[d.length]=a.substring(i,o),i=c.lastIndex,b[b.length]={match:j[0],left:j[3]?!0:!1,sign:j[4]||"",pad:j[5]||" ",min:j[6]||0,precision:j[8],code:j[9]||"%",negative:0>parseInt(arguments[e])?!0:!1,argument:""+arguments[e]};d[d.length]=a.substring(i);if(0==b.length)return a;if(arguments.length-1<e)return null;a=null;for(a=0;a<b.length;a++)"%"==b[a].code?substitution="%":"b"==b[a].code?(b[a].argument=""+Math.abs(parseInt(b[a].argument)).toString(2),
substitution=sprintfWrapper.convert(b[a],!0)):"c"==b[a].code?(b[a].argument=""+String.fromCharCode(parseInt(Math.abs(parseInt(b[a].argument)))),substitution=sprintfWrapper.convert(b[a],!0)):"d"==b[a].code?(b[a].argument=""+Math.abs(parseInt(b[a].argument)),substitution=sprintfWrapper.convert(b[a])):"f"==b[a].code?(b[a].argument=""+Math.abs(parseFloat(b[a].argument)).toFixed(b[a].precision?b[a].precision:6),substitution=sprintfWrapper.convert(b[a])):"o"==b[a].code?(b[a].argument=""+Math.abs(parseInt(b[a].argument)).toString(8),
substitution=sprintfWrapper.convert(b[a])):"s"==b[a].code?(b[a].argument=b[a].argument.substring(0,b[a].precision?b[a].precision:b[a].argument.length),substitution=sprintfWrapper.convert(b[a],!0)):"x"==b[a].code?(b[a].argument=""+Math.abs(parseInt(b[a].argument)).toString(16),substitution=sprintfWrapper.convert(b[a])):"X"==b[a].code?(b[a].argument=""+Math.abs(parseInt(b[a].argument)).toString(16),substitution=sprintfWrapper.convert(b[a]).toUpperCase()):substitution=b[a].match,l+=d[a],l+=substitution;
return l+=d[a]},convert:function(a,c){a.sign=c?"":a.negative?"-":a.sign;var b=a.min-a.argument.length+1-a.sign.length,b=Array(0>b?0:b).join(a.pad);return a.left?"0"==a.pad||c?a.sign+a.argument+b.replace(/0/g," "):a.sign+a.argument+b:"0"==a.pad||c?a.sign+b+a.argument:b+a.sign+a.argument}};sprintf=sprintfWrapper.init;var v={};H();var M=H().replace(/[^\/]*$/,""),y={fit:function(a,c,d,h,e){var i,o,l=a/c,e=b.extend({noEnlarge:!1,minWidth:16,minHeight:16},e);i=d;o=d/l;o>h&&(o=h,i=o*l);if(i<e.minWidth)i=
e.minWidth,o=i/l;if(o<e.minHeight)o=e.minHeight,i=o*l;if(e.noEnlarge&&(i>a||o>c))i=a,o=c;a=(h-o)/2;return{left:parseInt((d-i)/2),top:parseInt(a),width:parseInt(i),height:parseInt(o),margin:0}},fill:function(a,c,b,d){var e=a/c,a=b,c=b/e;c<d&&(c=d,a=c*e);d=(d-c)/2;return{left:parseInt((b-a)/2),top:parseInt(d),width:parseInt(a),height:parseInt(c),margin:0}}};k.prototype.render=function(){var a=this,c=this.settings,d=this.canvas,h=this.items;(function(){var a=b('<div class="altgallery-imageFrame" style="position:absolute;"></div>'),
h={};switch(c.thumbBar.position.toLowerCase()){default:case "bottom":h.left=10;h.top=10;h.width=d.width()-20;h.height=d.height()-c.thumbnail.height-30;break;case "top":h.left=10;h.bottom=10;h.width=d.width()-20;h.height=d.height()-c.thumbnail.height-30;break;case "left":h.right=10;h.top=10;h.width=d.width()-c.thumbnail.width-30;h.height=d.height()-20;break;case "right":h.left=10,h.top=10,h.width=d.width()-c.thumbnail.width-30,h.height=d.height()-20}a.css(h);d.element.append(a)})();(function(){var e=
b('<div class="altgallery-thumbBar"></div>'),i,o,l,j,g,m={};switch(c.thumbBar.position.toLowerCase()){default:case "bottom":i="horizontal";o=d.width()-20;l=c.thumbnail.height+4;j=h.length*(c.thumbnail.width+5)-5;m.left=10;m.bottom=7;m.width=o;m.height=l;break;case "top":i="horizontal";o=d.width()-20;l=c.thumbnail.height+4;j=h.length*(c.thumbnail.width+5)-5;m.left=10;m.top=9;m.width=o;m.height=l;break;case "left":i="vertical";o=c.thumbnail.width+4;l=d.height()-20;g=h.length*(c.thumbnail.height+5)-
5;m.left=9;m.top=10;m.width=o;m.height=l;break;case "right":i="vertical",o=c.thumbnail.width+4,l=d.height()-20,g=h.length*(c.thumbnail.height+5)-5,m.right=8,m.top=10,m.width=o,m.height=l}m.position="absolute";m.overflow="hidden";e.css(m);for(var f=b('<div style="position:relative;"></div>'),m=0;m<h.length;m++)(function(d){var e=b('<a href="'+h[d].source+'"></a>');e.css({position:"absolute",left:"horizontal"==i?d*(c.thumbnail.width+5):1,top:"horizontal"==i?1:d*(c.thumbnail.height+5),width:c.thumbnail.width-
4,height:c.thumbnail.height-4,overflow:"hidden",border:"2px solid",borderColor:w(c.thumbnail.outlineColor),"-moz-border-radius":c.thumbnail.cornerRadius/2,"-webkit-border-radius":c.thumbnail.cornerRadius/2,"-khtml-border-radius":c.thumbnail.cornerRadius/2,borderRadius:c.thumbnail.cornerRadius/2,opacity:c.thumbnail.alpha/100});e.hover(function(){var a=b(this);a.hasClass("altgallery-active")||(a.data("style",{opacity:a.css("opacity"),borderColor:a.css("borderTopColor")}),a.css({borderColor:w(c.thumbnail.outlineColorOnRollOver),
opacity:1}))},function(){var a=b(this);a.hasClass("altgallery-active")||a.css(a.data("style"))});e.click(function(){var e=b(this);e.hasClass("altgallery-active")||(e.parent().find("a").removeClass("altgallery-active").css({opacity:c.thumbnail.alpha/100,borderColor:w(c.thumbnail.outlineColor)}),e.addClass("altgallery-active").data("style",{opacity:1,borderColor:w(c.thumbnail.outlineColorOnClick)}).css(e.data("style")),a.open(h[d]),function(){var a;if("horizontal"==i&&o<j){var b=0-(d*(c.thumbnail.width+
5)-o/2+c.thumbnail.width/2),h=0-j+o;0<b&&(b=0);b<h&&(b=h);f.animate({left:b});f.unbind("mouseleave").mouseleave(function(){a=setTimeout(function(){f.animate({left:b},1E3)},1E3)})}else l<g&&(b=0-(d*(c.thumbnail.height+5)-l/2+c.thumbnail.height/2),h=0-g+l,0<b&&(b=0),b<h&&(b=h),f.animate({top:b}),f.unbind("mouseleave").mouseleave(function(){a=setTimeout(function(){f.animate({top:b},1E3)},1E3)}));f.unbind("mouseenter").mouseenter(function(){clearTimeout(a)})}());return!1});f.append(e);0==d&&e.click();
var m=new Image;m.onload=function(){var a=b('<img src="'+h[d].thumb+'" alt="" />');B(a);a.css({position:"absolute",border:"none"});a.css(y.fill(this.width,this.height,c.thumbnail.width-4,c.thumbnail.height-4));c.thumbnail.useShadow&&e.css({"-moz-box-shadow":"1px 1px 2px rgba(0, 0, 0, 0.5)","-webkit-box-shadow":"1px 1px 2px rgba(0, 0, 0, 0.5)","-khtml-box-shadow":"1px 1px 2px rgba(0, 0, 0, 0.5)",boxShadow:"1px 1px 2px rgba(0, 0, 0, 0.5)"});e.append(a)};m.src=h[d].thumb})(m);e.append(f);(function(){function a(){t=
!0;f.stop();z=setInterval(function(){var a=parseInt(f.css("left"))+20;0<a?(f.css("left",0),m()):f.css("left",a)},50)}function c(){t=!0;f.stop();z=setInterval(function(){var a=parseInt(f.css("left"))-20,b=0-j+o;a<b?(f.css("left",b),m()):f.css("left",a)},50)}function d(){t=!0;f.stop();z=setInterval(function(){var a=parseInt(f.css("top"))+20;0<a?(f.css("top",0),m()):f.css("top",a)},50)}function h(){t=!0;f.stop();z=setInterval(function(){var a=parseInt(f.css("top"))-20,b=0-g+l;a<b?(f.css("top",b),m()):
f.css("top",a)},50)}function m(){clearInterval(z);t=!1}var z,t=!1;"horizontal"==i&&o<j?e.mousemove(function(d){d=d.pageX-b(this).offset().left;50>d?t||a():d>o-50?t||c():m()}):l<g&&e.mousemove(function(a){a=a.pageY-b(this).offset().top;50>a?t||d():a>l-50?t||h():m()});e.mouseleave(function(){m()})})();d.element.append(e)})()};k.prototype.open=function(a){var c=this.settings,d=this.canvas,h=d.element.find(".altgallery-imageFrame"),e=b('<img class="altgallery-preloader" src="'+q.images.loader+'" alt="" />');
B(e);e.css({position:"absolute",left:"50%",top:"50%",zIndex:10,margin:"-16px 0 0 -16px"});var i=new Image;i.onload=function(){e.hide();d.element.find(".altgallery-preloader").remove();var a=c.image.scaleMode.toLowerCase(),f="fill"==a?y.fill(i.width,i.height,h.width(),h.height()):y.fit(i.width,i.height,h.width(),h.height()),j=b("<div></div>");j.css({position:"absolute",left:"fill"==a?0:f.left,top:"fill"==a?0:f.top,width:"fill"==a?h.width():f.width,height:"fill"==a?h.height():f.height,overflow:"hidden",
"-moz-border-radius":c.image.cornerRadius/2,"-webkit-border-radius":c.image.cornerRadius/2,"-khtml-border-radius":c.image.cornerRadius/2,borderRadius:c.image.cornerRadius/2});c.image.useShadow&&j.css({"-moz-box-shadow":"1px 1px 2px rgba(0, 0, 0, 0.5)","-webkit-box-shadow":"1px 1px 2px rgba(0, 0, 0, 0.5)","-khtml-box-shadow":"1px 1px 2px rgba(0, 0, 0, 0.5)",boxShadow:"1px 1px 2px rgba(0, 0, 0, 0.5)"});var g=b('<img src="'+i.src+'" alt="" />');B(g);g.css({position:"absolute",left:"fill"==a?f.left:0,
top:"fill"==a?f.top:0,width:f.width,height:f.height});j.append(g);switch(c.image.transitionEffect.toLowerCase()){default:case "fade":h.animate({opacity:0},{duration:500*c.image.transitionDuration,easing:"linear",complete:function(){h.empty();h.append(j);h.animate({opacity:1},{duration:500*c.image.transitionDuration,easing:"linear"})}});break;case "xfade":case "crossfade":j.hide(),a=h.find("div"),a.size()?(a.animate({opacity:0},{duration:1E3*c.image.transitionDuration,easing:"linear",complete:function(){b(this).remove()}}),
h.append(j),j.css({opacity:0}).animate({opacity:1},{duration:1E3*c.image.transitionDuration,easing:"linear"})):(h.append(j),j.css({opacity:0}).animate({opacity:1},{duration:500*c.image.transitionDuration,easing:"linear"}))}};i.src=a.source;setTimeout(function(){d.element.find(".altgallery-preloader").remove();h.append(e)},500)};k.prototype.prev=function(){};k.prototype.next=function(){};k.prototype.prevPage=function(){};k.prototype.nextPage=function(){};n.prototype.render=function(a){var c=this,d=
this.canvas,h=this.items;if(a===r)a=c.page;d.element.empty();var e=this.canvas.width(),i=this.canvas.height(),f=parseInt((e-50)/parseInt(this.settings.thumbnail.width)),g=parseInt((i-50)/parseInt(this.settings.thumbnail.height)),j=Math.ceil(h.length/f);g>j&&(g=j);j=f*g;a*=j;c.pagesCount=Math.ceil(h.length/j);var p=parseInt(this.settings.thumbnail.width)+2,m=parseInt(this.settings.thumbnail.height)+2,K=(e-p*f)/2-8,L=(i-m*g)/2-8,x=b('<div class="altgallery-frame" />'),e={position:"absolute",left:parseInt(K),
top:parseInt(L),width:parseInt(e-2*(K+8))+14,height:parseInt(i-2*(L+8))+14,overflow:"hidden",background:"#fff","-moz-border-radius":"4px","-webkit-border-radius":"4px","-khtml-border-radius":"4px",borderRadius:"4px","-moz-box-shadow":"0 0 10px rgba(0, 0, 0, 0.5)","-webkit-box-shadow":"0 0 10px rgba(0, 0, 0, 0.5)","-khtml-box-shadow":"0 0 10px rgba(0, 0, 0, 0.5)",boxShadow:"0 0 10px rgba(0, 0, 0, 0.5)"};x.css(e);0<c.page&&(i=b('<a class="altgallery-page" style="left:4px; background:no-repeat center; -moz-border-radius:4px; -webkit-border-radius:4px; border-radius:4px;"></a>'),
i.css({backgroundImage:u(q.images.left)}),i.click(function(){c.prevPage()}),x.append(i));c.page<c.pagesCount-1&&(i=b('<a class="altgallery-page" style="right:4px; background:no-repeat center; -moz-border-radius:4px; -webkit-border-radius:4px; border-radius:4px;"></a>'),i.css({backgroundImage:u(q.images.right)}),i.click(function(){c.nextPage()}),x.append(i));x.find(".altgallery-page").css({position:"absolute",width:"30px",height:"30px",top:parseInt(e.height/2)-15,zIndex:20,cursor:"pointer"});"ontouchstart"in
document.documentElement||x.hover(function(){x.find(".altgallery-page").show()},function(){x.find(".altgallery-page").hide()});d.element.append(x);i=b('<div class="altgallery-frameMask" />');e.background="#000";e.opacity=0.6;e.zIndex=20;e["-moz-box-shadow"]="none";e["-webkit-box-shadow"]="none";e["-khtml-box-shadow"]="none";e.boxShadow="none";i.css(e).hide();d.element.append(i);var k=parseInt(this.settings.thumbnail.alpha)/100,O=w(c.settings.colorScheme.imageBGColor),n=1,y=1;for(e=a,i=-1,g=h.length;e<
g&&!(e>=j+a);e++){e%f||i++;n=e%f*p+8;y=i*m+8;(function(a,e,i){d.drawImage(h[a],{x:parseInt(e),y:parseInt(i),z:10,width:c.settings.thumbnail.width,height:c.settings.thumbnail.height,scaleMode:"fill",opacity:k,background:O,onclick:function(){c.currentItem=a;c.open(c.getCurrentItem(),{left:parseInt(e+K),top:parseInt(i+L)});return!1},onmouseover:function(){b(this).children("img").css({opacity:1})},onmouseout:function(){b(this).children("img").css({opacity:k})}},".altgallery-frame")})(e,n,y)}};n.prototype.open=
function(a,c){var d=this,h=b('<img class="altgallery-preloader" src="'+q.images.loader+'" alt="" />');B(h);h.css({position:"absolute",left:"50%",top:"50%",zIndex:10,margin:"-16px 0 0 -16px"});var e=document.createElement("img");e.src=a.thumb;var i=new Image;i.onload=function(){b(".altgallery-imageFrame",d.canvas.element).remove();b(".altgallery-frameMask",d.canvas.element).fadeIn(q.animation.duration);var a=document.createElement("div");b(a).addClass("altgallery-imageFrame").css({position:"absolute",
padding:8,background:"#000",zIndex:30});b(a).hide();var f=y.fit(i.width,i.height,d.canvas.width()-48,d.canvas.height()-48),g={left:f.left+16+f.width/3,top:f.top+16+f.height/3,width:f.width/3,height:f.height/3};if(c!==r){if(c.left!==r)g.left=c.left;if(c.top!==r)g.top=c.top}b(a).css(g);var m=y.fit(i.width,i.height,d.canvas.width()-48,d.canvas.height()-48),o={left:m.left+16+m.width/3,top:m.top+16+m.height/3,width:m.width/3,height:m.height/3,margin:0,padding:0,border:"none",maxWidth:"none",maxHeight:"none",
cursor:"pointer"};b(e).css(o);b(a).append(e);d.canvas.element.append(a);b(e).animate(m,q.animation.duration);b(a).animate({opacity:"show",left:f.left+16,top:f.top+16,width:f.width,height:f.height},q.animation.duration,function(){var c=b('<a class="altgallery-close" style="position:absolute; right:-15px; top:-13px; width:30px; height:30px; z-index:40; background:no-repeat center; cursor:pointer;"></a>');c.css({backgroundImage:u(q.images.close)});c.click(function(){b(this).remove();g.opacity="hide";
b(a).animate(g,q.animation.duration,function(){b(this).remove()});b(e).animate(o,q.animation.duration);b(".altgallery-frameMask",d.canvas.element).fadeOut(q.animation.duration)});b(a).append(c);setTimeout(function(){b(a).append(h)},500)});b(e).click(function(){b(".altgallery-close",a).remove();g.opacity="hide";b(a).animate(g,q.animation.duration,function(){b(this).remove();d.next()});b(e).animate(o,q.animation.duration)})};i.src=a.thumb;var f=new Image;f.onload=function(){h.hide();d.canvas.element.find(".altgallery-preloader").remove();
b(e).attr("src",a.source)};f.src=a.source};n.prototype.prev=function(){this.currentItem--;if(0>this.currentItem)this.currentItem=this.items.length-1;this.open(this.getCurrentItem())};n.prototype.next=function(){this.currentItem++;if(this.currentItem>=this.items.length)this.currentItem=0;this.open(this.getCurrentItem())};n.prototype.prevPage=function(){this.page--;this.render(this.page)};n.prototype.nextPage=function(){this.page++;this.render(this.page)};C.prototype.showScrollbar=function(){var a=
this,c=this.settings,d=this.canvas,e=b('<div class="altgallery-scrollbar"></div>'),f=Math.round(0.8*d.width())-36;e.css({position:"absolute",zIndex:1E3,left:(d.width()-f)/2,bottom:5,width:f+36,height:17,background:G(c.scrollbar.bgColor,c.scrollbar.bgAlpha/100),"-moz-border-radius":8,"-webkit-border-radius":8,borderRadius:8});var i=b('<div class="altgallery-scrollbar-handle"></div>'),g=f/a.items.length;i.css({position:"absolute",left:Math.round(a.currentItem*g),width:Math.floor(g),height:13,background:w(c.scrollbar.handleColor),
opacity:c.scrollbar.handleAlpha/100,cursor:"pointer"});i.hover(function(){i.css({opacity:1})},function(){i.css({opacity:c.scrollbar.handleAlpha/100})});var l=b("<div></div>");l.css({position:"relative",height:13,margin:"2px 18px"});l.click(function(c){c=c.pageX-b(this).offset().left;a.currentItem=Math.floor(c/f*a.items.length);i.css({left:Math.round(a.currentItem*g)});a.animate()});var j={position:"absolute",top:2,width:16,height:16,fontFamily:"Arial, Helvetica, sans-serif",fontSize:"10px",lineHeight:"14px",
textAlign:"center",color:w(c.scrollbar.arrowsColor),opacity:c.scrollbar.arrowsAlpha/100,cursor:"pointer"},p=b("<div>&#9668;</div>");p.css(j);p.css({left:1});p.click(function(){a.prev()});e.append(p);p=b("<div>&#9658;</div>");p.css(j);p.css({right:1});p.click(function(){a.next()});e.append(p);l.append(i);e.append(l);d.element.append(e)};C.prototype.updateScrollbar=function(){var a=this.canvas,b=(Math.round(0.8*a.width())-36)/this.items.length;a.element.find(".altgallery-scrollbar-handle").css({left:Math.round(this.currentItem*
b)})};C.prototype.getItemStyle=function(a,b){var d=this.settings,e=this.canvas,f,i;f=this.getItemX(b);i=this.getItemZ(b);var g;g=Math.abs(f);var l=y.fit(a.width,a.height,d.maxImageWidth*(1>g?1:2>g?0.55:3>g?0.5:0.6-0.05*g),e.height()-60);return{zIndex:i,left:(e.width()-l.width)/2+f*e.width()/8+(f?f/g*d.maxImageWidth/3:0),top:(e.height()-l.height)/2-30,width:l.width,height:l.height,opacity:f?0.8:1,transform:{rotateY:-(f?f/g:0)*d.imageAngle+"deg"}}};C.prototype.render=function(){function e(i,j){d(g[i].source,
function(d){var e=c.getItemStyle(d,i),o=b('<a class="altgallery-item-'+i+'"></a>');g[i].link&&(o.attr("href",g[i].link),g[i].target&&o.attr("target",g[i].target));o.css({display:"block",position:"absolute",zIndex:e.zIndex,left:e.left,top:e.top,width:e.width,height:e.height,overflow:"visible",background:"#000",cursor:"pointer",outline:"none"});a(o,{rotateY:e.transform.rotateY});var l=b('<img src="" alt="" />');l.attr("src",d.src);B(l);l.css({display:"block",width:e.width,height:e.height,opacity:e.opacity});
o.append(l);if(c.showReflections){d=l.clone();d.css({opacity:f.reflectionAlpha/100,"-moz-transform":"scaleY(-1)","-webkit-transform":"scaleY(-1)"});var p=b('<div class="altgallery-overlay"></div>');p.css({position:"absolute",top:e.height,width:e.width,height:e.height});e=h.element.css("backgroundColor");e=[G(e,0),G(e,0.5),G(e,1)];b.browser.mozilla?p.css({background:"-moz-linear-gradient(top, "+e[0]+" 0%, "+e[1]+" 15%, "+e[2]+" 50%)"}):b.browser.webkit?p.css({background:"-webkit-linear-gradient(top, "+
e[0]+" 0%, "+e[1]+" 15%, "+e[2]+" 50%)"}):p.css({background:"linear-gradient(top, "+e[0]+" 0%, "+e[1]+" 15%, "+e[2]+" 50%)"});o.append(d);o.append(p)}o.click(function(){c.currentItem+=j;if(0>c.currentItem)c.currentItem=0;else if(c.currentItem>=g.length)c.currentItem=g.length-1;c.animate();return!1}).hover(function(){l.css({opacity:1})},function(){l.css({opacity:j?0.8:1})});i==c.currentItem&&o.unbind("click");c.scene.append(o)})}var c=this,f=this.settings,h=this.canvas,g=this.items;c.scene.empty();
c.scene.css({"-webkit-perspective":400,"-moz-perspective":400,perspective:400});var i,o,l,j,p;j=c.currentItem;p=2*Math.max(j,g.length-j);for(i=1;i<=p;i++)o=j+(i%2?parseInt(i/2):-parseInt(i/2)),0<=o&&o<g.length&&(l=c.getItemX(o),e(o,l));f.useScrollBar&&c.showScrollbar();b.browser.mozilla&&c.showReflections&&c.animate()};C.prototype.animate=function(){function b(i,f){d(h[i].source,function(b){var d=c.scene.find(".altgallery-item-"+i),g=d.find("img"),o={left:parseInt(d.css("left")),top:parseInt(d.css("top")),
width:d.width(),height:d.height(),opacity:d.find("img").css("opacity"),transform:a(d)},j=c.getItemStyle(b,i);d.show().css({zIndex:j.zIndex});d.unbind("click").click(function(){c.currentItem+=f;if(0>c.currentItem)c.currentItem=0;else if(c.currentItem>=h.length)c.currentItem=h.length-1;c.animate();return!1}).unbind("hover").hover(function(){g.first().css({opacity:1})},function(){g.first().css({opacity:f?0.8:1})});g.first().css({opacity:j.opacity});var l=d.find(".altgallery-overlay");d.animate({animate:1E4},
{duration:800*e.flipDuration,easing:"easeOutCubic",step:function(b){function e(a){return o[a]+(j[a]-o[a])*b/1E4}d.css({left:Math.round(e("left")),top:Math.round(e("top")),width:Math.round(e("width")),height:Math.round(e("height"))});g.css({width:Math.round(e("width")),height:Math.round(e("height"))});c.showReflections&&l.css({top:Math.round(e("height")),width:Math.round(e("width")),height:Math.round(e("height"))});a(this,{rotateY:parseInt(o.transform.rotateY)+(parseInt(j.transform.rotateY)-parseInt(o.transform.rotateY))*
b/1E4+"deg"})},complete:function(){d.prop("animate",0);i==c.currentItem&&d.unbind("click")}})})}var c=this,e=this.settings,h=this.items,f,i,g,l,j;l=c.currentItem;j=2*Math.max(l,h.length-l);for(f=1;f<=j;f++)i=l+(f%2?parseInt(f/2):-parseInt(f/2)),0<=i&&i<h.length&&(g=c.getItemX(i),b(i,g));e.useScrollBar&&c.updateScrollbar()};C.prototype.showAlbums=function(){};C.prototype.open=function(){};C.prototype.prev=function(){0<this.currentItem&&(this.currentItem--,this.animate())};C.prototype.next=function(){this.currentItem<
this.items.length-1&&(this.currentItem++,this.animate())};s.prototype.render=function(){var a=this,c=this.settings,d=this.canvas,e=this.albums;d.element.css({fontFamily:c.fontName,fontSize:parseInt(c.fontSize)+"px",lineHeight:1.2*parseInt(c.fontSize)+"px"});(function(){var f=b('<div class="altgallery-imageFrame"></div>');f.css({width:d.width()-2*c.frameSize,height:d.height()-2*c.frameSize,padding:c.frameSize,background:w(c.frameColor),borderRadius:c.cornerRadius/2});var i=b('<div class="altgallery-image"></div>');
i.css({position:"relative",width:d.width()-2*c.frameSize,height:d.height()-2*c.frameSize,overflow:"hidden",background:w(c.backgroundColor),borderRadius:c.cornerRadius/2-c.frameSize/4,cursor:"pointer"});var g=b('<img src="" alt="" />');B(i.children("img"));g.css({position:"absolute"});f.click(function(){a.next()});i.append(g);f.append(i);d.element.append(f);a.open(e[0].items[0])})();switch(c.initialState.toLowerCase()){default:case "show albums":this.showAlbums();break;case "show thumbnails":this.showThumbnails();
case "load image":case "start slideshow":}};s.prototype.showAlbums=function(){function a(){function f(){var a=k*p+1,b=k*p+p;if(b>c.albums.length)b=c.albums.length;x.html(a+"-"+b+" "+h.translation.Of+" "+c.albums.length);0>=k?(n.css({opacity:0.3,cursor:"default"}),n.unbind("click").click(function(){return!1})):(n.css({opacity:1,cursor:"pointer"}),n.unbind("click").click(r));k>=m-1?(s.css({opacity:0.3,cursor:"default"}),s.unbind("click").click(function(){return!1})):(s.css({opacity:1,cursor:"pointer"}),
s.unbind("click").click(w))}c.hideThumbnails();c.hideButtons();c.hideCaption();c.hideNavigation();var i=b('<div class="altgallery-albums"></div>'),g=e.width()-2*h.frameSize,l=h.iconHeight+115;i.css({position:"absolute",left:h.frameSize,top:(e.height()-l)/2,width:e.width()-2*h.frameSize,height:l,overflow:"hidden",color:"#fff",border:"1px #000",borderStyle:"solid none",zIndex:2});var j=b('<div class="altgallery-albums-overlay"></div>');j.css({position:"absolute",left:h.frameSize,top:(e.height()-l)/
2,width:e.width()-2*h.frameSize,height:l+1,background:"#000",opacity:h.panelBackgroundAlpha/100,zIndex:1});e.element.append(j);l=b("<div></div>");l.css({position:"absolute",top:10,right:20});j=b('<a class="altgallery-close" href="#">'+h.translation.Close+"</a>");j.css({marginRight:0,color:"#fff",fontWeight:"bold",textDecoration:"none",textShadow:"0 1px 0 rgba(0, 0, 0, 0.5)",background:"no-repeat left center",backgroundImage:u(q.images.folder+"zen-close.png"),paddingLeft:12});j.click(function(){c.hideAlbums();
c.showButtons();c.showCaption();c.showNavigation();return!1});l.append(j);i.append(l);var p=Math.floor((g-20)/(h.iconWidth+h.iconPadding)),p=p>c.albums.length?c.albums.length:p,l=(h.iconWidth+h.iconPadding)*p-h.iconPadding,j=(h.iconWidth+h.iconPadding)*c.albums.length-h.iconPadding,m=Math.ceil(c.albums.length/p),k=0,t=b("<div>"+h.translation.Albums+"</div>");t.css({position:"absolute",left:9,top:0,padding:10,paddingLeft:25,textShadow:"-1px 1px 0 rgba(0, 0, 0, 0.5)",fontWeight:"bold",background:"no-repeat left center",
backgroundImage:u(q.images.folder+"zen-albums.png")});i.append(t);var x=b("<span></span>");x.css({marginLeft:"1em",fontWeight:"normal"});t.append(x);t=b("<div></div>");t.css({position:"absolute",left:(g-l)/2-4,top:42,width:l+4,height:h.iconHeight+70,overflow:"hidden"});var E=b("<div></div>");E.css({position:"relative",left:0,width:j});t.append(E);g=b("<div></div>");g.css({position:"absolute",right:4,bottom:3,height:20,opacity:0.9});var n=b('<a href="#"></a>');n.css({display:"block",cssFloat:"left",
width:16,height:16,marginRight:3,background:"no-repeat center",backgroundImage:u(q.images.folder+"zen-prev.png")});var r=function(){k--;var a=(h.iconWidth+h.iconPadding)*p*k;E.stop();E.animate({left:-a},2*q.animation.duration,"easeOutQuart");f();return!1};n.click(r);g.append(n);i.append(t);var s=b('<a href="#"></a>');s.css({display:"block",cssFloat:"left",width:16,height:16,marginRight:3,background:"no-repeat center",backgroundImage:u(q.images.folder+"zen-next.png")});var w=function(){k++;var a=(h.iconWidth+
h.iconPadding)*p*k;E.stop();E.animate({left:-a},2*q.animation.duration,"easeOutQuart");f();return!1};s.click(w);g.append(s);i.append(g);f();for(g=0;g<c.albums.length;g++)(function(a,e){var i=b("<div></div>");i.css({position:"absolute",left:(h.iconWidth+h.iconPadding)*e,top:0,width:h.iconWidth+h.iconPadding+6,overflow:"hidden",textShadow:"0 1px 0 rgba(0, 0, 0, 0.5)"});var f=b("<div></div>");f.css({position:"relative",width:h.iconWidth-2,height:h.iconHeight-2,overflow:"hidden",border:"1px solid",borderColor:c.currentAlbum==
e?"#000":"#fff",margin:"2px",cursor:"pointer"});d(a.items[0].thumb,function(a){var c=b('<img src="" alt="" />');c.attr("src",a.src);B(c);c.css({position:"absolute"});c.css(y.fill(a.width,a.height,h.iconWidth-2,h.iconHeight-2));f.append(c)},50*e);i.append(f);i.append('<div style="padding:7px 2px 2px; font-weight:bold;">'+(a.description||"Album "+(e+1))+"<div>");i.append('<div style="padding:1px 2px;">'+a.items.length+" "+(1==a.items.length?h.translation.Image:h.translation.Images)+"<div>");i.hover(function(){f.css({borderWidth:"3px",
margin:"0px"})},function(){f.css({borderWidth:"1px",margin:"2px"})}).click(function(){if(c.currentAlbum!=e)c.currentItem=-1;c.currentAlbum=e;c.showThumbnails()});E.append(i)})(c.albums[g],g);e.element.append(i)}var c=this,e=this.canvas,h=this.settings;e.element.find(".altgallery-albums").size()||a()};s.prototype.hideAlbums=function(){this.canvas.element.find(".altgallery-albums, .altgallery-albums-overlay").remove()};s.prototype.showThumbnails=function(){function a(){function i(){var a=t*m+1,b=t*
m+m;if(b>f.items.length)b=f.items.length;n.html(a+"-"+b+" "+h.translation.Of+" "+f.items.length);0>=t?(s.css({opacity:0.3,cursor:"default"}),s.unbind("click").click(function(){return!1})):(s.css({opacity:1,cursor:"pointer"}),s.unbind("click").click(w));t>=k-1?(v.css({opacity:0.3,cursor:"default"}),v.unbind("click").click(function(){return!1})):(v.css({opacity:1,cursor:"pointer"}),v.unbind("click").click(A))}c.hideAlbums();c.hideButtons();c.hideCaption();c.hideNavigation();var g=b('<div class="altgallery-images"></div>'),
l=e.width()-2*h.frameSize,j=h.iconHeight+75;g.css({position:"absolute",left:h.frameSize,top:(e.height()-j)/2,width:e.width()-2*h.frameSize,height:j,overflow:"hidden",color:"#fff",border:"1px #000",borderStyle:"solid none",zIndex:2});var p=b('<div class="altgallery-images-overlay"></div>');p.css({position:"absolute",left:h.frameSize,top:(e.height()-j)/2,width:e.width()-2*h.frameSize,height:j+1,background:"#000",opacity:h.panelBackgroundAlpha/100,zIndex:1});e.element.append(p);j=b("<div></div>");j.css({position:"absolute",
top:10,right:20});1<c.albums.length&&(p=b('<a class="altgallery-back" href="#">'+h.translation.BackToAlbums+"</a>"),p.css({marginRight:"1.5em",color:"#fff",fontWeight:"bold",textDecoration:"none",textShadow:"0 1px 0 rgba(0, 0, 0, 0.5)",background:"no-repeat left center",backgroundImage:u(q.images.folder+"zen-backToAlbums.png"),paddingLeft:14}),p.click(function(){c.showAlbums();return!1}),j.append(p));p=b('<a class="altgallery-close" href="#">'+h.translation.Close+"</a>");p.css({marginRight:0,color:"#fff",
fontWeight:"bold",textDecoration:"none",textShadow:"0 1px 0 rgba(0, 0, 0, 0.5)",background:"no-repeat left center",backgroundImage:u(q.images.folder+"zen-close.png"),paddingLeft:12});p.click(function(){c.hideThumbnails();c.showButtons();c.showCaption();c.showNavigation();return!1});j.append(p);g.append(j);var m=Math.floor((l-20)/(h.iconWidth+h.iconPadding)),m=m>f.items.length?f.items.length:m,j=(h.iconWidth+h.iconPadding)*m-h.iconPadding,p=(h.iconWidth+h.iconPadding)*f.items.length-h.iconPadding,
k=Math.ceil(f.items.length/m),t=0,x=b("<div>"+h.translation.Images+"</div>");x.css({position:"absolute",left:9,top:0,padding:10,paddingLeft:25,textShadow:"-1px 1px 0 rgba(0, 0, 0, 0.5)",fontWeight:"bold",background:"no-repeat left center",backgroundImage:u(q.images.folder+"zen-thumbnails.png")});g.append(x);var n=b("<span></span>");n.css({marginLeft:"1em",fontWeight:"normal"});x.append(n);x=b("<div></div>");x.css({position:"absolute",left:(l-j)/2-4,top:42,width:j+4,height:h.iconHeight+4,overflow:"hidden"});
var r=b("<div></div>");r.css({position:"relative",left:0,width:p});x.append(r);g.append(x);l=b("<div></div>");l.css({position:"absolute",right:4,bottom:3,height:20,opacity:0.9});var s=b('<a href="#"></a>');s.css({display:"block",cssFloat:"left",width:16,height:16,marginRight:3,background:"no-repeat center",backgroundImage:u(q.images.folder+"zen-prev.png")});var w=function(){t--;var a=(h.iconWidth+h.iconPadding)*m*t;r.stop();r.animate({left:-a},2*q.animation.duration,"easeOutQuart");i();return!1};
s.click(w);l.append(s);var v=b('<a href="#"></a>');v.css({display:"block",cssFloat:"left",width:16,height:16,marginRight:3,background:"no-repeat center",backgroundImage:u(q.images.folder+"zen-next.png")});var A=function(){t++;var a=(h.iconWidth+h.iconPadding)*m*t;r.stop();r.animate({left:-a},2*q.animation.duration,"easeOutQuart");i();return!1};v.click(A);l.append(v);g.append(l);i();for(l=0;l<f.items.length;l++)(function(a,e){var f=b("<div></div>");f.css({position:"absolute",left:(h.iconWidth+h.iconPadding)*
e,top:0,width:h.iconWidth+h.iconPadding+6,overflow:"hidden",textShadow:"0 1px 0 rgba(0, 0, 0, 0.5)"});var i=b("<div></div>");i.css({position:"relative",width:h.iconWidth-2,height:h.iconHeight-2,overflow:"hidden",border:"1px solid",borderColor:c.currentItem==e?"#000":"#fff",margin:"2px",cursor:"pointer"});d(a.thumb,function(a){var c=b('<img src="" alt="" />');c.attr("src",a.src);B(c);c.css({position:"absolute"});c.css(y.fill(a.width,a.height,h.iconWidth-2,h.iconHeight-2));i.append(c)},50*e);f.append(i);
f.hover(function(){i.css({borderWidth:"3px",margin:"0px"})},function(){i.css({borderWidth:"1px",margin:"2px"})}).click(function(){c.currentItem=e;c.open(c.getCurrentItem())});r.append(f)})(f.items[l],l);e.element.append(g)}var c=this,e=this.canvas,h=this.settings,f=this.getCurrentAlbum();e.element.find(".altgallery-images").size()||a()};s.prototype.hideThumbnails=function(){this.canvas.element.find(".altgallery-images, .altgallery-images-overlay").remove()};s.prototype.showButtons=function(){function a(){var d=
b('<div class="altgallery-buttons"></div>');d.css({position:"absolute",right:c.settings.frameSize,top:25+c.settings.frameSize,padding:"3px 3px 3px 1px",background:"rgba(0, 0, 0, "+c.settings.buttonsBackgroundAlpha/100+")",border:"1px solid rgba(0, 0, 0, 0.8)",borderRight:"none","-moz-border-top-left-radius":"3px","-moz-border-bottom-left-radius":"3px","-webkit-border-top-left-radius":"3px","-webkit-border-bottom-left-radius":"3px","border-top-left-radius":"3px","border-bottom-left-radius":"3px"});
if(c.settings.showAlbumsButton&&1<c.albums.length){var e=b('<a href="#"></a>');e.css({display:"block",cssFloat:"left",margin:"0 2px",width:16,height:16,background:"no-repeat center",backgroundImage:u(q.images.folder+"zen-albums.png"),opacity:0.8});e.click(function(){c.showAlbums();return!1});d.append(e)}c.settings.showThumbnailsButton&&(e=b('<a href="#"></a>'),e.css({display:"block",cssFloat:"left",margin:"0 2px",width:16,height:16,background:"no-repeat center",backgroundImage:u(q.images.folder+"zen-thumbnails.png"),
opacity:0.8}),e.click(function(){c.showThumbnails();return!1}),d.append(e));c.canvas.element.append(d)}var c=this;if("never"!=c.settings.showButtons.toLowerCase()&&(c.settings.showAlbumsButton||c.settings.showThumbnailsButton))c.canvas.element.find(".altgallery-buttons").size()||a()};s.prototype.hideButtons=function(){this.canvas.element.find(".altgallery-buttons").remove()};s.prototype.showCaption=function(){this.hideCaption();if("never"!=this.settings.showCaption.toLowerCase()&&(this.getCurrentAlbum()&&
this.getCurrentAlbum().description||this.getCurrentItem()&&this.getCurrentItem().description)){var a=b('<div class="altgallery-caption"></div>');a.css({position:"absolute",left:this.settings.frameSize,top:25+this.settings.frameSize,padding:"4px 10px 5px 7px",color:"#fff",textShadow:"-1px 1px 0 rgba(0, 0, 0, 0.3)",background:"rgba(0, 0, 0, "+this.settings.captionBackgroundAlpha/100+")",border:"1px solid rgba(0, 0, 0, 0.8)",borderLeft:"none","-moz-border-top-right-radius":"3px","-moz-border-bottom-right-radius":"3px",
"-webkit-border-top-right-radius":"3px","-webkit-border-bottom-right-radius":"3px","border-top-right-radius":"3px","border-bottom-right-radius":"3px"});this.getCurrentAlbum().description&&a.append('<div style="font-weight:bold;">'+this.getCurrentAlbum().description+"</div>");this.getCurrentItem().description&&a.append('<div style="">'+this.getCurrentItem().description+"</div>");this.canvas.element.append(a)}};s.prototype.hideCaption=function(){this.canvas.element.find(".altgallery-caption").remove()};
s.prototype.showNavigation=function(){function a(){var d=b('<div class="altgallery-navigation"></div>');d.css({position:"absolute",right:c.settings.frameSize,bottom:25+c.settings.frameSize,padding:"3px 3px 3px 1px",background:"rgba(0, 0, 0, "+c.settings.buttonsBackgroundAlpha/100+")",border:"1px solid rgba(0, 0, 0, 0.8)",borderRight:"none","-moz-border-top-left-radius":"3px","-moz-border-bottom-left-radius":"3px","-webkit-border-top-left-radius":"3px","-webkit-border-bottom-left-radius":"3px","border-top-left-radius":"3px",
"border-bottom-left-radius":"3px"});if(c.settings.showNavigationButton){var e=b('<a href="#"></a>');e.css({display:"block",cssFloat:"left",margin:"0 2px",width:16,height:16,background:"no-repeat center",backgroundImage:u(q.images.folder+"zen-prev.png"),opacity:0.8});e.click(function(){c.prev();return!1});d.append(e);e=b('<a href="#"></a>');e.css({display:"block",cssFloat:"left",margin:"0 2px",width:16,height:16,background:"no-repeat center",backgroundImage:u(q.images.folder+"zen-next.png"),opacity:0.8});
e.click(function(){c.next();return!1});d.append(e)}c.canvas.element.append(d)}var c=this;"never"!=c.settings.showButtons.toLowerCase()&&c.settings.showNavigationButton&&(c.canvas.element.find(".altgallery-navigation").size()||a())};s.prototype.hideNavigation=function(){this.canvas.element.find(".altgallery-navigation").remove()};s.prototype.open=function(a){var c=this,e=this.canvas,f=this.settings;c.hideAlbums();c.hideThumbnails();c.showButtons();c.showCaption();c.showNavigation();e.element.find(".altgallery-image img").hide();
var g=e.element.find(".altgallery-imageFrame"),i=b('<img class="altgallery-preloader" src="'+q.images.loader+'" alt="" />');B(i);i.css({position:"absolute",left:"50%",top:"50%",zIndex:10,margin:"-16px 0 0 -16px"});d(a.source,function(b){i.hide();e.element.find(".altgallery-preloader").remove();var d=e.element.find(".altgallery-image img");"fit"==f.imageScaleMode?d.css(y.fit(b.width,b.height,e.width()-2*f.frameSize,e.height()-2*f.frameSize)):d.css(y.fill(b.width,b.height,e.width()-2*f.frameSize,e.height()-
2*f.frameSize));d.attr("src",a.source).fadeIn(2*q.animation.duration);c.cache()});setTimeout(function(){e.element.find(".altgallery-preloader").remove();g.append(i)},500)};s.prototype.prev=function(){0<this.currentItem?this.currentItem--:this.currentItem=this.getCurrentAlbum().items.length-1;this.open(this.getCurrentItem())};s.prototype.next=function(){this.currentItem<this.getCurrentAlbum().items.length-1?this.currentItem++:this.currentItem=0;this.open(this.getCurrentItem())};var q={};b.fn.altgallery=
function(a){function c(){d.each(function(){N(this,a)})}var d=this,a=b.extend(!0,{width:"550px",height:"400px",background:"none",images:{folder:M+"img/",left:"left.png",right:"right.png",close:"close.png",loader:"loader.png"},animation:{duration:500},config:{settings:{}}},a);if(a.images.folder){a.images.folder=a.images.folder.replace(/\/+$/,"")+"/";for(var e in a.images)"folder"!=e&&(a.images[e]=a.images.folder+a.images[e].replace(/^\/+/,""))}if("string"==typeof a.config){d.css({visibility:"hidden"});
var f={load:function(a,b,c){if(b!==r)switch(b.toLowerCase()){case "xml":this.loadXML(a,c);break;default:case "json":this.loadJSON(a,c)}else a.match(/(xml)$/i)?this.loadXML(a,c):this.loadJSON(a,c)},loadJSON:function(a,c){b.ajax({url:a,dataType:"json",success:function(a){a=f.parse(a);"function"==typeof c&&c(a)},error:function(){"function"==typeof c&&c({})}})},loadXML:function(a,c){function d(a){var b;"undefined"==typeof b&&(b=function(){});b.ObjTree=function(){return this};b.ObjTree.prototype.attr_prefix=
"";b.ObjTree.prototype.parseDOM=function(a){if(a){this.__force_array={};if(this.force_array)for(var b=0;b<this.force_array.length;b++)this.__force_array[this.force_array[b]]=1;b=this.parseElement(a);this.__force_array[a.nodeName]&&(b=[b]);if(11!=a.nodeType){var c={};c[a.nodeName]=b;b=c}return b}};b.ObjTree.prototype.parseElement=function(a){if(7!=a.nodeType){if(3==a.nodeType||4==a.nodeType)return null==a.nodeValue.match(/[^\x00-\x20]/)?void 0:a.nodeValue;var b,c={};if(a.attributes&&a.attributes.length){b=
{};for(var d=0;d<a.attributes.length;d++){var e=a.attributes[d].nodeName;if("string"==typeof e){var f=a.attributes[d].nodeValue;f&&(e=this.attr_prefix+e,"undefined"==typeof c[e]&&(c[e]=0),c[e]++,this.addNode(b,e,c[e],f))}}}if(a.childNodes&&a.childNodes.length){e=!0;b&&(e=!1);for(d=0;d<a.childNodes.length&&e;d++)f=a.childNodes[d].nodeType,3==f||4==f||(e=!1);if(e){b||(b="");for(d=0;d<a.childNodes.length;d++)b+=a.childNodes[d].nodeValue}else{b||(b={});for(d=0;d<a.childNodes.length;d++)if(e=a.childNodes[d].nodeName,
"string"==typeof e&&(f=this.parseElement(a.childNodes[d])))"undefined"==typeof c[e]&&(c[e]=0),c[e]++,this.addNode(b,e,c[e],f)}}return b}};b.ObjTree.prototype.addNode=function(a,b,c,d){this.__force_array[b]?(1==c&&(a[b]=[]),a[b][a[b].length]=d):1==c?a[b]=d:2==c?a[b]=[a[b],d]:a[b][a[b].length]=d};b=new b.ObjTree;b.attr_prefix="";return b.parseDOM(a)["#document"]}b.ajax({url:a,dataType:"xml",success:function(a){a=d(a);a=f.parse(a);"function"==typeof c&&c(a)},error:function(){"function"==typeof c&&c({})}})},
parse:function(a){if(a.gallery){var b,c;if(a.galleryName)a.gallery.galleryName=a.galleryName;a=a.gallery;b=a.settings.imagesFolder?a.settings.imagesFolder.replace(/\/$/,"")+"/":"";c=a.settings.thumbnailsFolder?a.settings.thumbnailsFolder.replace(/\/$/,"")+"/":b;if(a.items){if(a.items.item)a.items=a.items.item.length?a.items.item:[a.items.item];for(var d=0;d<a.items.length;d++)a.items[d].source=b+a.items[d].source,a.items[d].thumb=a.items[d].thumb==r?a.items[d].source:c+a.items[d].thumb}if(a.albums){if(a.albums.album)a.albums=
a.albums.album.length?a.albums.album:[a.albums.album];for(var e=0;e<a.albums.length;e++){b=a.albums[e].imagesFolder?a.albums[e].imagesFolder.replace(/\/$/,"")+"/":"";c=a.albums[e].thumbnailsFolder?a.albums[e].thumbnailsFolder.replace(/\/$/,"")+"/":b;if(a.albums[e].items.item)a.albums[e].items=a.albums[e].items.item.length?a.albums[e].items.item:[a.albums[e].items.item];for(d=0;d<a.albums[e].items.length;d++)a.albums[e].items[d].source=b+a.albums[e].items[d].source,a.albums[e].items[d].thumb=a.albums[e].items[d].thumb==
r?a.albums[e].items[d].source:c+a.albums[e].items[d].thumb}}}return a}};f.load(a.config,a.configType,function(b){d.css({visibility:"visible"});a.config=b;c()})}else c();return this};b.altbox=function(a,c){if(d!=top)var d=top,e=d.document;c=b.extend(!0,{frame:{color:"#000",borderRadius:0},mask:{color:"#000",opacity:0.7},images:{folder:M+"img/",close:"close.png",loader:"loader.gif"},animation:{duration:700}},c);if(c.images.folder)for(var f in c.images)"folder"!=f&&!c.images[f].match("/")&&(c.images[f]=
c.images.folder+c.images[f]);var g=b('<div style="position:fixed; z-index:999; left:0; top:0; width:100%; height:100%; background:no-repeat center;"></div>');g.css({opacity:0,backgroundColor:c.mask.color,backgroundImage:u(c.images.loader)});b(e.body).append(g);g.animate({opacity:c.mask.opacity},c.animation.duration);var k=new Image;k.onload=function(){function f(){g.remove();q.remove()}var j=b(d).width()-100,p=b(d).height()-100,m=y.fit(k.width/4,k.height/4,j,p,{noEnlarge:!0,minWidth:100,minHeight:100});
m.left+=50;m.top+=50;var n=y.fit(k.width+20,k.height+20,j,p,{noEnlarge:!0,minWidth:120,minHeight:120});n.left+=50;n.top+=50;var q=b('<div style="position:fixed; z-index:1000;"></div>');q.css(m);q.css({backgroundColor:c.frame.color,borderRadius:c.frame.borderRadius,MozUserSelect:"none",webkitUserSelect:"none",userSelect:"none"});q.hide();var r=b('<img src="'+a+'" alt="" style="display:block;" />');r.css({margin:"10px",width:m.width-20,height:m.height-20,borderRadius:8<c.frame.borderRadius?c.frame.borderRadius-
8:0});var s=b('<a href="#" style="display:block; position:absolute; right:-12px; top:-10px; width:30px; height:30px; background:no-repeat center;"></a>');s.css({backgroundImage:u(c.images.close)});q.append(r);b(e.body).append(q);(function(){g.css({backgroundImage:"none"});r.animate({width:n.width-20,height:n.height-20,margin:"10px"},c.animation.duration,"easeOutBack");n.opacity="show";q.animate(n,c.animation.duration,"easeOutBack",function(){q.append(s)})})();b(d).resize(function(){j=b(d).width()-
100;p=b(d).height()-100;m=y.fit(k.width/4,k.height/4,j,p,{noEnlarge:!0,minWidth:100,minHeight:100});m.left+=50;m.top+=50;n=y.fit(k.width+20,k.height+20,j,p,{noEnlarge:!0,minWidth:120,minHeight:120});n.left+=50;n.top+=50;q.css(n);r.css({width:n.width-20,height:n.height-20})});g.click(f);s.click(function(){s.remove();m.opacity="hide";q.animate(m,0.67*c.animation.duration);r.animate({width:m.width-20,height:m.height-20},0.67*c.animation.duration);g.fadeOut(c.animation.duration,function(){f()});return!1})};
k.src=a}})(jQuery);
