/**
 * altgallery, jQuery Plugin
 *
 * @version 0.4.7
 * @copyright 2011-2012 Flash-Gallery.com
 */

jQuery.effects||function(d,t){function J(h){var a;return h&&h.constructor==Array&&3==h.length?h:(a=/rgb\(\s*([0-9]{1,3})\s*,\s*([0-9]{1,3})\s*,\s*([0-9]{1,3})\s*\)/.exec(h))?[parseInt(a[1],10),parseInt(a[2],10),parseInt(a[3],10)]:(a=/rgb\(\s*([0-9]+(?:\.[0-9]+)?)\%\s*,\s*([0-9]+(?:\.[0-9]+)?)\%\s*,\s*([0-9]+(?:\.[0-9]+)?)\%\s*\)/.exec(h))?[2.55*parseFloat(a[1]),2.55*parseFloat(a[2]),2.55*parseFloat(a[3])]:(a=/#([a-fA-F0-9]{2})([a-fA-F0-9]{2})([a-fA-F0-9]{2})/.exec(h))?[parseInt(a[1],16),parseInt(a[2],
16),parseInt(a[3],16)]:(a=/#([a-fA-F0-9])([a-fA-F0-9])([a-fA-F0-9])/.exec(h))?[parseInt(a[1]+a[1],16),parseInt(a[2]+a[2],16),parseInt(a[3]+a[3],16)]:/rgba\(0, 0, 0, 0\)/.exec(h)?N.transparent:N[d.trim(h).toLowerCase()]}function M(){var d=document.defaultView?document.defaultView.getComputedStyle(this,null):this.currentStyle,a={},c,e;if(d&&d.length&&d[0]&&d[d[0]])for(var g=d.length;g--;)c=d[g],"string"==typeof d[c]&&(e=c.replace(/\-(\w)/g,function(a,d){return d.toUpperCase()}),a[e]=d[c]);else for(c in d)"string"===
typeof d[c]&&(a[c]=d[c]);return a}function D(h){var a,c;for(a in h)c=h[a],(null==c||d.isFunction(c)||a in I||/scrollbar/.test(a)||!/color/i.test(a)&&isNaN(parseFloat(c)))&&delete h[a];return h}function O(d,a){var c={_:0},e;for(e in a)d[e]!=a[e]&&(c[e]=a[e]);return c}function v(h,a,c,e){if("object"==typeof h)e=a,c=null,a=h,h=a.effect;d.isFunction(a)&&(e=a,c=null,a={});if("number"==typeof a||d.fx.speeds[a])e=c,c=a,a={};d.isFunction(c)&&(e=c,c=null);a=a||{};c=c||a.duration;c=d.fx.off?0:"number"==typeof c?
c:c in d.fx.speeds?d.fx.speeds[c]:d.fx.speeds._default;e=e||a.complete;return[h,a,c,e]}function n(h){return!h||"number"===typeof h||d.fx.speeds[h]||"string"===typeof h&&!d.effects[h]?!0:!1}d.effects={};d.each("backgroundColor,borderBottomColor,borderLeftColor,borderRightColor,borderTopColor,borderColor,color,outlineColor".split(","),function(h,a){d.fx.step[a]=function(c){if(!c.colorInit){var e;e=c.elem;var h=a,j;do{j=d.curCSS(e,h);if(""!=j&&"transparent"!=j||d.nodeName(e,"body"))break;h="backgroundColor"}while(e=
e.parentNode);e=J(j);c.start=e;c.end=J(c.end);c.colorInit=!0}c.elem.style[a]="rgb("+Math.max(Math.min(parseInt(c.pos*(c.end[0]-c.start[0])+c.start[0],10),255),0)+","+Math.max(Math.min(parseInt(c.pos*(c.end[1]-c.start[1])+c.start[1],10),255),0)+","+Math.max(Math.min(parseInt(c.pos*(c.end[2]-c.start[2])+c.start[2],10),255),0)+")"}});var N={aqua:[0,255,255],azure:[240,255,255],beige:[245,245,220],black:[0,0,0],blue:[0,0,255],brown:[165,42,42],cyan:[0,255,255],darkblue:[0,0,139],darkcyan:[0,139,139],
darkgrey:[169,169,169],darkgreen:[0,100,0],darkkhaki:[189,183,107],darkmagenta:[139,0,139],darkolivegreen:[85,107,47],darkorange:[255,140,0],darkorchid:[153,50,204],darkred:[139,0,0],darksalmon:[233,150,122],darkviolet:[148,0,211],fuchsia:[255,0,255],gold:[255,215,0],green:[0,128,0],indigo:[75,0,130],khaki:[240,230,140],lightblue:[173,216,230],lightcyan:[224,255,255],lightgreen:[144,238,144],lightgrey:[211,211,211],lightpink:[255,182,193],lightyellow:[255,255,224],lime:[0,255,0],magenta:[255,0,255],
maroon:[128,0,0],navy:[0,0,128],olive:[128,128,0],orange:[255,165,0],pink:[255,192,203],purple:[128,0,128],violet:[128,0,128],red:[255,0,0],silver:[192,192,192],white:[255,255,255],yellow:[255,255,0],transparent:[255,255,255]},B=["add","remove","toggle"],I={border:1,borderBottom:1,borderColor:1,borderLeft:1,borderRight:1,borderTop:1,borderWidth:1,margin:1,padding:1};d.effects.animateClass=function(h,a,c,e){d.isFunction(c)&&(e=c,c=null);return this.queue(function(){var g=d(this),j=g.attr("style")||
" ",v=D(M.call(this)),n,t=g.attr("class");d.each(B,function(a,d){if(h[d])g[d+"Class"](h[d])});n=D(M.call(this));g.attr("class",t);g.animate(O(v,n),{queue:!1,duration:a,easing:c,complete:function(){d.each(B,function(a,d){if(h[d])g[d+"Class"](h[d])});"object"==typeof g.attr("style")?(g.attr("style").cssText="",g.attr("style").cssText=j):g.attr("style",j);e&&e.apply(this,arguments);d.dequeue(this)}})})};d.fn.extend({_addClass:d.fn.addClass,addClass:function(h,a,c,e){return a?d.effects.animateClass.apply(this,
[{add:h},a,c,e]):this._addClass(h)},_removeClass:d.fn.removeClass,removeClass:function(h,a,c,e){return a?d.effects.animateClass.apply(this,[{remove:h},a,c,e]):this._removeClass(h)},_toggleClass:d.fn.toggleClass,toggleClass:function(h,a,c,e,g){return"boolean"==typeof a||a===t?c?d.effects.animateClass.apply(this,[a?{add:h}:{remove:h},c,e,g]):this._toggleClass(h,a):d.effects.animateClass.apply(this,[{toggle:h},a,c,e])},switchClass:function(h,a,c,e,g){return d.effects.animateClass.apply(this,[{add:a,
remove:h},c,e,g])}});d.extend(d.effects,{version:"1.8.16",save:function(d,a){for(var c=0;c<a.length;c++)null!==a[c]&&d.data("ec.storage."+a[c],d[0].style[a[c]])},restore:function(d,a){for(var c=0;c<a.length;c++)null!==a[c]&&d.css(a[c],d.data("ec.storage."+a[c]))},setMode:function(d,a){"toggle"==a&&(a=d.is(":hidden")?"show":"hide");return a},getBaseline:function(d,a){var c,e;switch(d[0]){case "top":c=0;break;case "middle":c=0.5;break;case "bottom":c=1;break;default:c=d[0]/a.height}switch(d[1]){case "left":e=
0;break;case "center":e=0.5;break;case "right":e=1;break;default:e=d[1]/a.width}return{x:e,y:c}},createWrapper:function(h){if(h.parent().is(".ui-effects-wrapper"))return h.parent();var a={width:h.outerWidth(!0),height:h.outerHeight(!0),"float":h.css("float")},c=d("<div></div>").addClass("ui-effects-wrapper").css({fontSize:"100%",background:"transparent",border:"none",margin:0,padding:0}),e=document.activeElement;h.wrap(c);(h[0]===e||d.contains(h[0],e))&&d(e).focus();c=h.parent();"static"==h.css("position")?
(c.css({position:"relative"}),h.css({position:"relative"})):(d.extend(a,{position:h.css("position"),zIndex:h.css("z-index")}),d.each(["top","left","bottom","right"],function(d,c){a[c]=h.css(c);isNaN(parseInt(a[c],10))&&(a[c]="auto")}),h.css({position:"relative",top:0,left:0,right:"auto",bottom:"auto"}));return c.css(a).show()},removeWrapper:function(h){var a,c=document.activeElement;return h.parent().is(".ui-effects-wrapper")?(a=h.parent().replaceWith(h),(h[0]===c||d.contains(h[0],c))&&d(c).focus(),
a):h},setTransition:function(h,a,c,e){e=e||{};d.each(a,function(a,d){unit=h.cssUnit(d);0<unit[0]&&(e[d]=unit[0]*c+unit[1])});return e}});d.fn.extend({effect:function(h,a,c,e){var g=v.apply(this,arguments),j={options:g[1],duration:g[2],callback:g[3]},g=j.options.mode,n=d.effects[h];return d.fx.off||!n?g?this[g](j.duration,j.callback):this.each(function(){j.callback&&j.callback.call(this)}):n.call(this,j)},_show:d.fn.show,show:function(d){if(n(d))return this._show.apply(this,arguments);var a=v.apply(this,
arguments);a[1].mode="show";return this.effect.apply(this,a)},_hide:d.fn.hide,hide:function(d){if(n(d))return this._hide.apply(this,arguments);var a=v.apply(this,arguments);a[1].mode="hide";return this.effect.apply(this,a)},__toggle:d.fn.toggle,toggle:function(h){if(n(h)||"boolean"===typeof h||d.isFunction(h))return this.__toggle.apply(this,arguments);var a=v.apply(this,arguments);a[1].mode="toggle";return this.effect.apply(this,a)},cssUnit:function(h){var a=this.css(h),c=[];d.each(["em","px","%",
"pt"],function(d,h){0<a.indexOf(h)&&(c=[parseFloat(a),h])});return c}});d.easing.jswing=d.easing.swing;d.extend(d.easing,{def:"easeOutQuad",swing:function(h,a,c,e,g){return d.easing[d.easing.def](h,a,c,e,g)},easeInQuad:function(d,a,c,e,g){return e*(a/=g)*a+c},easeOutQuad:function(d,a,c,e,g){return-e*(a/=g)*(a-2)+c},easeInOutQuad:function(d,a,c,e,g){return 1>(a/=g/2)?e/2*a*a+c:-e/2*(--a*(a-2)-1)+c},easeInCubic:function(d,a,c,e,g){return e*(a/=g)*a*a+c},easeOutCubic:function(d,a,c,e,g){return e*((a=
a/g-1)*a*a+1)+c},easeInOutCubic:function(d,a,c,e,g){return 1>(a/=g/2)?e/2*a*a*a+c:e/2*((a-=2)*a*a+2)+c},easeInQuart:function(d,a,c,e,g){return e*(a/=g)*a*a*a+c},easeOutQuart:function(d,a,c,e,g){return-e*((a=a/g-1)*a*a*a-1)+c},easeInOutQuart:function(d,a,c,e,g){return 1>(a/=g/2)?e/2*a*a*a*a+c:-e/2*((a-=2)*a*a*a-2)+c},easeInQuint:function(d,a,c,e,g){return e*(a/=g)*a*a*a*a+c},easeOutQuint:function(d,a,c,e,g){return e*((a=a/g-1)*a*a*a*a+1)+c},easeInOutQuint:function(d,a,c,e,g){return 1>(a/=g/2)?e/2*
a*a*a*a*a+c:e/2*((a-=2)*a*a*a*a+2)+c},easeInSine:function(d,a,c,e,g){return-e*Math.cos(a/g*(Math.PI/2))+e+c},easeOutSine:function(d,a,c,e,g){return e*Math.sin(a/g*(Math.PI/2))+c},easeInOutSine:function(d,a,c,e,g){return-e/2*(Math.cos(Math.PI*a/g)-1)+c},easeInExpo:function(d,a,c,e,g){return 0==a?c:e*Math.pow(2,10*(a/g-1))+c},easeOutExpo:function(d,a,c,e,g){return a==g?c+e:e*(-Math.pow(2,-10*a/g)+1)+c},easeInOutExpo:function(d,a,c,e,g){return 0==a?c:a==g?c+e:1>(a/=g/2)?e/2*Math.pow(2,10*(a-1))+c:e/
2*(-Math.pow(2,-10*--a)+2)+c},easeInCirc:function(d,a,c,e,g){return-e*(Math.sqrt(1-(a/=g)*a)-1)+c},easeOutCirc:function(d,a,c,e,g){return e*Math.sqrt(1-(a=a/g-1)*a)+c},easeInOutCirc:function(d,a,c,e,g){return 1>(a/=g/2)?-e/2*(Math.sqrt(1-a*a)-1)+c:e/2*(Math.sqrt(1-(a-=2)*a)+1)+c},easeInElastic:function(d,a,c,e,g){var d=1.70158,j=0,n=e;if(0==a)return c;if(1==(a/=g))return c+e;j||(j=0.3*g);n<Math.abs(e)?(n=e,d=j/4):d=j/(2*Math.PI)*Math.asin(e/n);return-(n*Math.pow(2,10*(a-=1))*Math.sin((a*g-d)*2*Math.PI/
j))+c},easeOutElastic:function(d,a,c,e,g){var d=1.70158,j=0,n=e;if(0==a)return c;if(1==(a/=g))return c+e;j||(j=0.3*g);n<Math.abs(e)?(n=e,d=j/4):d=j/(2*Math.PI)*Math.asin(e/n);return n*Math.pow(2,-10*a)*Math.sin((a*g-d)*2*Math.PI/j)+e+c},easeInOutElastic:function(d,a,c,e,g){var d=1.70158,j=0,n=e;if(0==a)return c;if(2==(a/=g/2))return c+e;j||(j=g*0.3*1.5);n<Math.abs(e)?(n=e,d=j/4):d=j/(2*Math.PI)*Math.asin(e/n);return 1>a?-0.5*n*Math.pow(2,10*(a-=1))*Math.sin((a*g-d)*2*Math.PI/j)+c:0.5*n*Math.pow(2,
-10*(a-=1))*Math.sin((a*g-d)*2*Math.PI/j)+e+c},easeInBack:function(d,a,c,e,g,j){j==t&&(j=1.70158);return e*(a/=g)*a*((j+1)*a-j)+c},easeOutBack:function(d,a,c,e,g,j){j==t&&(j=1.70158);return e*((a=a/g-1)*a*((j+1)*a+j)+1)+c},easeInOutBack:function(d,a,c,e,g,j){j==t&&(j=1.70158);return 1>(a/=g/2)?e/2*a*a*(((j*=1.525)+1)*a-j)+c:e/2*((a-=2)*a*(((j*=1.525)+1)*a+j)+2)+c},easeInBounce:function(h,a,c,e,g){return e-d.easing.easeOutBounce(h,g-a,0,e,g)+c},easeOutBounce:function(d,a,c,e,g){return(a/=g)<1/2.75?
e*7.5625*a*a+c:a<2/2.75?e*(7.5625*(a-=1.5/2.75)*a+0.75)+c:a<2.5/2.75?e*(7.5625*(a-=2.25/2.75)*a+0.9375)+c:e*(7.5625*(a-=2.625/2.75)*a+0.984375)+c},easeInOutBounce:function(h,a,c,e,g){return a<g/2?0.5*d.easing.easeInBounce(h,2*a,0,e,g)+c:0.5*d.easing.easeOutBounce(h,2*a-g,0,e,g)+0.5*e+c}})}(jQuery);
(function(d,t){function J(f){var b=[],d,a;for(d=0;d<f.length;d++)for(a=0;a<f[d].items.length;a++)b.push(f[d].items[a]);return b}function M(f){return"object"==typeof f&&f.length!==t}function D(f){d(f).css({display:"block",position:"static",cssFloat:"none",clear:"none",left:"auto",right:"auto",top:"auto",bottom:"auto",width:"auto",height:"auto",minWidth:"none",minHeight:"none",maxWidth:"none",maxHeight:"none",overflow:"visible",margin:0,padding:0,border:"none",background:"none",color:"#000000",fontFamily:"serif",
fontSize:"16px",fontStyle:"normal",fontVariant:"normal",fontWeight:"normal",letterSpacing:"normal",lineHeight:"normal",opacity:1,outline:"none",textAlign:"left",textIndent:0,textShadow:"none",visibility:"visible",whiteSpace:"normal",cursor:"inherit"})}function O(){var f=document.getElementsByTagName("script");return f[f.length-1].src||location.href}function v(f){return'url("'+f+'")'}function n(f){if("number"==typeof f)return"#"+sprintf("%06x",f);if("string"==typeof f){var b;return(b=f.match(/[0-9a-f]{3,6}$/i))?
3==b[0].length?"#"+b[0]+b[0]+b[1]+b[1]+b[2]+b[2]:"#"+b[0]:(b=f.match(/rgb\(\s*(\d+)\s*,\s*(\d+)\s*,\s*(\d+)\s*\)/i))?"#"+sprintf("%02x",b[1])+sprintf("%02x",b[2])+sprintf("%02x",b[3]):f}}function N(f){return n(f).match(/[0-9a-f]{6}$/i)?!0:!1}function B(f,b){var f=n(f),d=f.match(/#([0-9a-f]{2})([0-9a-f]{2})([0-9a-f]{2})/i);if(d){for(var a=[],A=1;3>=A;A++)a.push(parseInt(d[A],16));return b!==t?"rgba("+a[0]+", "+a[1]+", "+a[2]+", "+b+")":"rgb("+a[0]+", "+a[1]+", "+a[2]+")"}return"transparent"}function I(f){for(var b in f)"object"==
typeof f[b]?f[b]=I(f[b]):"true"==f[b]?f[b]=!0:"false"==f[b]?f[b]=!1:f[b]==parseInt(f[b])&&(f[b]=parseInt(f[b]));return f}function h(f){var b="",d,a=f.length;for(d=0;d<a;d++)b+=f.charCodeAt(d).toString(16);return b}function a(f,b){function a(b,f,d){for(var u in b)u.match("-")?b[f+u]=b[u]:b[d+u.charAt(0).toUpperCase()+u.slice(1)]=b[u]}d.browser.mozilla?a(b,"-moz-","Moz"):d.browser.webkit?a(b,"-webkit-","webkit"):d.browser.opera?a(b,"-o-","O"):d.browser.msie&&a(b,"-ms-","ms");d(f).css(b)}function c(f,
b){if(b===t)return b={},d(f).data("transform")||{};d(f).each(function(){var f=[],a;for(a in b)f.push(a+"("+b[a]+")");f=f.join(" ");d(this).data("transform",b).css({"-moz-transform":f,"-webkit-transform":f,"-khtml-transform":f,"-o-transform":f,"-ms-transform":f,transform:f})});return d(f)}function e(){if(P===t){var f=location.hostname.toString().replace(/^www\./i,"");P=!location.hostname||-1!=d.inArray(h(f),U)}return P}function g(f,b,d){d===t&&"number"==typeof b&&(d=b,b=t);d=d||10;if(f&&G[f]===t){var a=
new Image;G[f]=a;G[f].loaded=!1;G[f].callbacks=[];"function"==typeof b&&G[f].callbacks.push(b);setTimeout(function(){a.onload=function(){G[f].loaded=!0;for(var b=0;b<G[f].callbacks.length;b++)G[f].callbacks[b](G[f])};a.src=f},d)}else G[f].loaded?"function"==typeof b&&b(G[f]):"function"==typeof b&&G[f].callbacks.push(b)}function j(f,b,a,l){a===t&&"number"==typeof b&&(a=b,b=t);a=a||10;if("string"==typeof f)return g(f,b,a);if(M(f)){var l=l||[],A=f.slice();setTimeout(function(){var f=A.shift(),f="string"==
typeof f?f:f.source||f.src||d(f).attr("src");g(f,function(f){A.length?(l.push(f),j(A,b,a,l)):"function"==typeof b&&b(l)})},a)}}function T(f,b){this.init=function(){var a=d('<div class="altgallery-canvas"></div>');D(a);a.css({display:"block",position:"relative",width:b.width,height:b.height,cursor:"default","-moz-user-select":"none","-webkit-user-select":"none","-khtml-user-select":"none",userSelect:"none"});this.element=d("<div></div>");this.element.css({display:"block",position:"relative",width:b.width,
height:b.height,overflow:"hidden",margin:0,padding:0,background:b.background});a.append(this.element);eval('var _c="#3C#61#20#68#72#65#66#3D#22#68#74#74#70#3A#2F#2F#77#77#77#2E#66#6C#61#73#68#2D#67#61#6C#6C#65#72#79#2E#63#6F#6D#2F#22#20#74#61#72#67#65#74#3D#22#5F#62#6C#61#6E#6B#22#20#73#74#79#6C#65#3D#22#64#69#73#70#6C#61#79#3A#62#6C#6F#63#6B#3B#70#6F#73#69#74#69#6F#6E#3A#61#62#73#6F#6C#75#74#65#3B#6C#65#66#74#3A#30#3B#74#6F#70#3A#30#3B#7A#2D#69#6E#64#65#78#3A#39#39#39#39#3B#77#69#64#74#68#3A#39#30#70#78#3B#68#65#69#67#68#74#3A#32#30#70#78#3B#6F#76#65#72#66#6C#6F#77#3A#68#69#64#64#65#6E#3B#66#6F#6E#74#2D#66#61#6D#69#6C#79#3A#54#61#68#6F#6D#61#2C#41#72#69#61#6C#2C#48#65#6C#76#65#74#69#63#61#2C#73#61#6E#73#2D#73#65#72#69#66#3B#66#6F#6E#74#2D#73#69#7A#65#3A#39#70#78#3B#6C#69#6E#65#2D#68#65#69#67#68#74#3A#31#32#70#78#3B#74#65#78#74#2D#61#6C#69#67#6E#3A#6C#65#66#74#3B#74#65#78#74#2D#64#65#63#6F#72#61#74#69#6F#6E#3A#6E#6F#6E#65#3B#74#65#78#74#2D#73#68#61#64#6F#77#3A#6E#6F#6E#65#3B#63#6F#6C#6F#72#3A#23#66#66#66#3B#62#61#63#6B#67#72#6F#75#6E#64#3A#72#67#62#61#28#30#2C#30#2C#30#2C#30#2E#37#29#3B#6F#70#61#63#69#74#79#3A#30#2E#37#3B#62#6F#72#64#65#72#2D#72#61#64#69#75#73#3A#34#70#78#3B#22#3E#3C#73#70#61#6E#20#73#74#79#6C#65#3D#22#64#69#73#70#6C#61#79#3A#62#6C#6F#63#6B#3B#70#61#64#64#69#6E#67#3A#34#70#78#20#31#30#70#78#3B#74#65#78#74#2D#74#72#61#6E#73#66#6F#72#6D#3A#75#70#70#65#72#63#61#73#65#3B#66#6F#6E#74#2D#73#69#7A#65#3A#38#70#78#3B#66#6F#6E#74#2D#77#65#69#67#68#74#3A#62#6F#6C#64#3B#77#68#69#74#65#2D#73#70#61#63#65#3A#6E#6F#77#72#61#70#3B#22#3E#50#68#6F#74#6F#20#47#61#6C#6C#65#72#79#3C#2F#73#70#61#6E#3E#3C#73#70#61#6E#20#73#74#79#6C#65#3D#22#64#69#73#70#6C#61#79#3A#62#6C#6F#63#6B#3B#70#61#64#64#69#6E#67#3A#35#70#78#20#31#30#70#78#20#31#30#70#78#3B#66#6F#6E#74#2D#73#69#7A#65#3A#39#70#78#3B#62#61#63#6B#67#72#6F#75#6E#64#3A#72#67#62#61#28#30#2C#30#2C#30#2C#30#2E#35#29#3B#62#6F#72#64#65#72#2D#62#6F#74#74#6F#6D#2D#6C#65#66#74#2D#72#61#64#69#75#73#3A#34#70#78#3B#62#6F#72#64#65#72#2D#62#6F#74#74#6F#6D#2D#72#69#67#68#74#2D#72#61#64#69#75#73#3A#34#70#78#3B#6F#70#61#63#69#74#79#3A#30#3B#22#3E#44#6F#77#6E#6C#6F#61#64#20#66#72#65#65#20#76#65#72#73#69#6F#6E#20#6F#66#20#74#68#69#73#20#67#61#6C#6C#65#72#79#20#66#72#6F#6D#20#46#6C#61#73#68#2D#47#61#6C#6C#65#72#79#2E#63#6F#6D#3C#2F#73#70#61#6E#3E#3C#2F#61#3E";'.replace(/#/g,
"\\x"));var l=d(_c);Q=_c.length;if(!e()){var A=l.width();d.browser.opera&&l.css({width:100}).find("span:first").css({letterSpacing:"-1px"});d.browser.msie&&9>d.browser.version?(l.css({background:"#444"}).find("span:last").css({background:"#222"}),l.hover(function(){d(this).stop().animate({width:120},"fast",function(){d(this).animate({height:70},"fast",function(){d(this).find("span:last").show()})})},function(){d(this).find("span:last").hide();d(this).stop().animate({height:20},"fast",function(){d(this).animate({width:A},
"fast")})})):l.hover(function(){d(this).stop().animate({width:120},"fast",function(){d(this).animate({height:70,opacity:1},"fast",function(){d(this).find("span:last").animate({opacity:1},"slow")})})},function(){d(this).find("span:last").animate({opacity:0},"fast");d(this).stop().animate({height:20},"fast",function(){d(this).animate({width:A,opacity:0.7},"fast")})});a.append(l)}d(f).empty().append(a)};this.init();this.empty=function(){this.element.empty()};this.width=function(b){return this.element.width(b)};
this.height=function(b){return this.element.height(b)};this.append=function(b){return this.element.append(b)};this.drawImage=function(b,f,a){var f=d.extend({left:0,top:0,width:120,height:90,scaleMode:"fill",background:"none"},f),a=a===t?this.element:d(a,this.element),c=new Image;c.onload=function(){var i=document.createElement("a");d(i).attr({href:b.source});d(i).css({display:"block",position:"absolute",left:f.x,top:f.y,zIndex:f.z,width:f.width,height:f.height,overflow:"hidden",background:f.background});
d(i).click(f.onclick);d(i).hover(f.onmouseover,f.onmouseout);var e=document.createElement("img");e.src=c.src;var k;"fit"==f.scaleMode?k=z.fit(this.width,this.height,f.width,f.height):"fill"==f.scaleMode&&(k=z.fill(this.width,this.height,f.width,f.height));d(e).css({marginTop:k.top,marginRight:0,marginBottom:0,marginLeft:k.left,width:k.width,height:k.height,padding:0,border:"none",maxWidth:"none",maxHeight:"none",opacity:f.opacity});d(i).append(e);a.append(i)};c.src=b.thumb}}function K(f,b,a){var l=
this;this.canvas=f;this.albums=b;this.items=J(b);this.currentItem=0;this.getCurrentItem=function(){return this.items[this.currentItem]};this.onOpen=function(){};l.onOpenItem={};this.settings=d.extend(!0,{image:{scaleMode:"fit",cornerRadius:10,align:"center",transitionEffect:"fade",transitionDuration:1,useShadow:!0},caption:{visibleMode:"onRollOver",position:"bottom",bgColor:0,bgAlpha:30,color:16777215,fontName:"Arial",fontSize:11},thumbBar:{useThumbBar:!0,position:"bottom",scrollSpeed:10},thumbnail:{width:80,
height:60,cornerRadius:10,alpha:70,outlineColor:3355443,outlineColorOnRollOver:6710886,outlineColorOnClick:10066329,useShadow:!0},slideshow:{start:!1,delay:2.5,loop:!0,stopAutoOnClick:!0}},a);this.settings=I(this.settings);(new Image).src=p.images.loader;l.settings.slideshow.start&&setTimeout(function(){l.slideshowStart()},500*l.settings.image.transitionDuration);this.render()}function L(f,b,a){this.canvas=f;this.albums=b;this.items=J(b);this.currentItem=-1;this.getCurrentItem=function(){return this.items[this.currentItem]};
this.defaultSettings={thumbnail:{width:120,height:90,alpha:85},colorScheme:{thumbsFrameColor:16777215,imageBGColor:1118481,useShadow:!0},imageCaption:{position:"top",color:16777215,bgColor:0,bgAlpha:30,fontName:"Arial",fontSize:11,visibleMode:"always"}};this.settings=d.extend(!0,this.defaultSettings,a);this.settings=I(this.settings);this.page=0;g(p.images.loader,500);this.render()}function r(f,b,a){this.canvas=f;this.albums=b;this.items=J(b);this.currentItem=0;this.getCurrentItem=function(){return this.items[this.currentItem]};
this.defaultSettings={initialState:"Load Image",slideshowDelay:2,showCaption:!0,base:{color:4080713,visibleFrame:5},buttons:{showSlideshowButton:!0,showThumbnailsButton:!0,bgColor:15066854}};this.settings=d.extend(!0,this.defaultSettings,a);this.settings=I(this.settings);this.enableThumbnailsHover=!0;g(p.images.loader,500);this.init()}function H(f,b,a){this.canvas=f;this.albums=b;this.settings=d.extend(!0,{imageAngle:30,maxImageWidth:0,useHighlight:!0,useScrollBar:!0,showReflections:!0,solidReflection:!0,
reflectionAlpha:80,slideShow:!1,slideShowDelay:2,flipDuration:1,startPosition:"center",colorScheme:"custom",preloader:{stripesAlpha:45,barColor:0,barAlpha:30,bgColor:0,bgAlpha:20,innerShadow:20,dropShadow:30},scrollbar:{bgColor:0,bgAlpha:40,handleColor:0,handleAlpha:40,arrowsColor:0,arrowsAlpha:40,innerShadow:20,dropShadow:20},caption:{textColor:16777215,bgColor:0,bgAlpha:80,frameColor:16777215,frameAlpha:40,shadowAlpha:50,multilingual:!1,multilingualFontSize:12},background:{bgColor:16777215,transparentBG:!0}},
a);this.settings=I(this.settings);if(!this.settings.maxImageWidth)this.settings.maxImageWidth=parseInt(f.element.width()/2);this.showReflections=this.settings.showReflections&&N(this.canvas.element.css("backgroundColor"))&&!(d.browser.msie&&9>d.browser.version);this.items=J(b);this.currentItem=0;this.getCurrentItem=function(){return this.items[this.currentItem]};this.getItemX=function(f){return-(this.currentItem-f)};this.getItemZ=function(f){return parseInt(this.items.length/2)-Math.abs(this.getItemX(f))};
this.currentItem="left"==this.settings.startPosition?0:"right"==this.settings.startPosition?this.items.length:Math.floor((this.items.length-1)/2);(new Image).src=p.images.loader;this.scene=d('<div class="altgallery-scene"></div>');this.scene.css({position:"relative",width:f.width(),height:f.height()});this.canvas.element.append(this.scene);this.render()}function x(f,b,a){this.canvas=f;this.albums=b;this.currentAlbum=0;this.getCurrentAlbum=function(){return this.albums[this.currentAlbum]};this.currentItem=
0;this.getCurrentItem=function(){return this.getCurrentAlbum().items[this.currentItem]};this.settings=d.extend(!0,{initialState:"Show Albums",imageScaleMode:"fill",frameSize:5,frameColor:"#ffffff",backgroundColor:"#aac5d8",cornerRadius:7,iconWidth:90,iconHeight:55,iconPadding:10,panelBackgroundAlpha:50,showCaption:"always",captionBackgroundAlpha:40,showButtons:"always",buttonsBackgroundAlpha:40,showAlbumsButton:!0,showThumbnailsButton:!0,showSlideshowButton:!0,showNavigationButton:!0,useEmbeddedFont:!0,
fontName:"Arial",fontSize:11,translation:{Album:"Album",Albums:"Albums",Image:"Image",Images:"Images",Close:"CLOSE",BackToAlbums:"BACK TO ALBUMS",LoadingImage:"Loading Image",Of:"of"}},a);this.settings=I(this.settings);if(this.settings.useEmbeddedFont)this.settings.fontName="Tahoma",this.settings.fontSize=9;g(p.images.loader,500);this.cache=function(){if(0<=this.currentItem){var f=this.getCurrentAlbum().items,b=[],a,u;for(u=this.currentItem+1;u<this.currentItem+3;u++)(a=f[(f.length+u)%f.length])&&
(a=a.source)&&b.push(a);for(u=this.currentItem-1;u>this.currentItem-2;u--)(a=f[(f.length+u)%f.length])&&(a=a.source)&&b.push(a);a="Caching images: "+JSON.stringify(b);V&&(f=d("#debug"),a="object"==typeof a?JSON.stringify(a):a,f.size()?f.append("<div>"+a+"</div>"):alert("JavaScript Gallery:\n\n"+a+"\n"));b.length&&j(b,100)}};this.render()}function W(f,b,a){function l(){function f(b){if(b.match(/Art/i))return"art";if(b.match(/Box/i))return"box";if(b.match(/Cubic/i))return"cubic";if(b.match(/PhotoFlow/i))return"photoflow";
if(b.match(/Zen/i))return"zen"}Q!=32*X&&(s=[]);switch(b.type?b.type.toLowerCase():c.galleryName?b.type=f(c.galleryName):b.type="box"){case "art":case "promo":m=new K(i,s,c.settings||{});break;default:case "box":m=new L(i,s,c.settings||{});break;case "cubic":m=new r(i,s,c.settings||{});break;case "photoflow":m=new H(i,s,c.settings||{});break;case "zen":m=new x(i,s,c.settings||{})}"function"==typeof a&&a(m)}f=d(f);p=b;var c,s,i,m,k=e(),g=15;c=b.config||{};s=function(){function b(f,d,u,l,i){d=d||0;l===
t&&(l=c.settings.imagesFolder?c.settings.imagesFolder.replace(/\/+$/,"")+"/":"");i===t&&(i=i||c.settings.thumbnailsFolder?c.settings.thumbnailsFolder.replace(/\/+$/,"")+"/":l);for(var e=[],m,s=0;s<f.length&&(k||s<g);s++)m=f[s],e[s]={id:s,source:l+m.source,thumb:m.thumb?i+m.thumb:l+m.source,description:m.description,link:m.link||"",target:m.target||""};a.push({id:d,description:u,items:e})}var a=[];if(M(c.albums)&&c.albums.length)for(var u=0;u<c.albums.length&&(k||3>u);u++)b(c.albums[u].items,u,c.albums[u].description,
c.albums[u].imagesFolder,c.albums[u].thumbnailsFolder);else M(c.items)&&c.items.length?b(c.items):b(function(f){var b=[];d(f).find("img").each(function(){b.push({source:d(this).parent("a").attr("href")||d(this).attr("src"),thumb:d(this).attr("src"),description:this.title})});return b}(f),0);return a}();i=new T(f,b);d(document).ready(function(){setTimeout(function(){l()},100)})}var U=["3132372e302e302e31","6c6f63616c686f7374","666c6173682d67616c6c6572792e636f6d"];sprintfWrapper={init:function(){if("undefined"==
typeof arguments||1>arguments.length||"string"!=typeof arguments[0]||"undefined"==typeof RegExp)return null;for(var f=arguments[0],b=RegExp(/(%([%]|(\-)?(\+|\x20)?(0)?(\d+)?(\.(\d)?)?([bcdfosxX])))/g),a=[],d=[],c=0,e=0,i=0,e=0,m="",k=null;k=b.exec(f);)k[9]&&(c+=1),i=b.lastIndex-k[0].length,d[d.length]=f.substring(e,i),e=b.lastIndex,a[a.length]={match:k[0],left:k[3]?!0:!1,sign:k[4]||"",pad:k[5]||" ",min:k[6]||0,precision:k[8],code:k[9]||"%",negative:0>parseInt(arguments[c])?!0:!1,argument:""+arguments[c]};
d[d.length]=f.substring(e);if(0==a.length)return f;if(arguments.length-1<c)return null;f=null;for(f=0;f<a.length;f++)"%"==a[f].code?substitution="%":"b"==a[f].code?(a[f].argument=""+Math.abs(parseInt(a[f].argument)).toString(2),substitution=sprintfWrapper.convert(a[f],!0)):"c"==a[f].code?(a[f].argument=""+String.fromCharCode(parseInt(Math.abs(parseInt(a[f].argument)))),substitution=sprintfWrapper.convert(a[f],!0)):"d"==a[f].code?(a[f].argument=""+Math.abs(parseInt(a[f].argument)),substitution=sprintfWrapper.convert(a[f])):
"f"==a[f].code?(a[f].argument=""+Math.abs(parseFloat(a[f].argument)).toFixed(a[f].precision?a[f].precision:6),substitution=sprintfWrapper.convert(a[f])):"o"==a[f].code?(a[f].argument=""+Math.abs(parseInt(a[f].argument)).toString(8),substitution=sprintfWrapper.convert(a[f])):"s"==a[f].code?(a[f].argument=a[f].argument.substring(0,a[f].precision?a[f].precision:a[f].argument.length),substitution=sprintfWrapper.convert(a[f],!0)):"x"==a[f].code?(a[f].argument=""+Math.abs(parseInt(a[f].argument)).toString(16),
substitution=sprintfWrapper.convert(a[f])):"X"==a[f].code?(a[f].argument=""+Math.abs(parseInt(a[f].argument)).toString(16),substitution=sprintfWrapper.convert(a[f]).toUpperCase()):substitution=a[f].match,m+=d[f],m+=substitution;return m+=d[f]},convert:function(f,b){f.sign=b?"":f.negative?"-":f.sign;var a=f.min-f.argument.length+1-f.sign.length,a=Array(0>a?0:a).join(f.pad);return f.left?"0"==f.pad||b?f.sign+f.argument+a.replace(/0/g," "):f.sign+f.argument+a:"0"==f.pad||b?f.sign+a+f.argument:a+f.sign+
f.argument}};sprintf=sprintfWrapper.init;var Q,V=location.href.match(/#jsgallerydebug$/),P,G={};O();var S=O().replace(/[^\/]*$/,""),z={fit:function(f,b,a,l,c){var e,i,m=f/b,c=d.extend({noEnlarge:!1,minWidth:16,minHeight:16},c);e=a;i=a/m;i>l&&(i=l,e=i*m);if(e<c.minWidth)e=c.minWidth,i=e/m;if(i<c.minHeight)i=c.minHeight,e=i*m;if(c.noEnlarge&&(e>f||i>b))e=f,i=b;return{left:(a-e)/2,top:(l-i)/2,width:e,height:i,margin:0}},fill:function(f,b,a,d){var c=f/b,f=a,b=a/c;b<d&&(b=d,f=b*c);return{left:(a-f)/2,
top:(d-b)/2,width:f,height:b,margin:0}}},X=23;K.prototype.render=function(){function f(){var f=b.thumbBar=d('<div class="altgallery-thumbBar"></div>'),i,e,k,g,h,o={};switch(a.thumbBar.position.toLowerCase()){default:case "bottom":i="horizontal";e=l.width()-20;k=a.thumbnail.height+4;g=c.length*(a.thumbnail.width+5)-5;o.left=10;o.bottom=7;o.width=e;o.height=k;break;case "top":i="horizontal";e=l.width()-20;k=a.thumbnail.height+4;g=c.length*(a.thumbnail.width+5)-5;o.left=10;o.top=9;o.width=e;o.height=
k;break;case "left":i="vertical";e=a.thumbnail.width+4;k=l.height()-20;h=c.length*(a.thumbnail.height+5)-5;o.left=9;o.top=10;o.width=e;o.height=k;break;case "right":i="vertical",e=a.thumbnail.width+4,k=l.height()-20,h=c.length*(a.thumbnail.height+5)-5,o.right=8,o.top=10,o.width=e,o.height=k}o.position="absolute";o.overflow="hidden";f.css(o);for(var q=d('<div style="position:relative;"></div>'),o=0;o<c.length;o++)(function(l){var o=d('<a href="'+c[l].source+'"></a>');o.css({position:"absolute",left:"horizontal"==
i?l*(a.thumbnail.width+5):1,top:"horizontal"==i?1:l*(a.thumbnail.height+5),width:a.thumbnail.width-4,height:a.thumbnail.height-4,overflow:"hidden",border:"2px solid",borderColor:n(a.thumbnail.outlineColor),"-moz-border-radius":a.thumbnail.cornerRadius/2,"-webkit-border-radius":a.thumbnail.cornerRadius/2,"-khtml-border-radius":a.thumbnail.cornerRadius/2,borderRadius:a.thumbnail.cornerRadius/2,opacity:a.thumbnail.alpha/100});o.hover(function(){var f=d(this);f.hasClass("altgallery-active")||(f.data("style",
{opacity:f.css("opacity"),borderColor:f.css("borderTopColor")}),f.css({borderColor:n(a.thumbnail.outlineColorOnRollOver),opacity:1}))},function(){var a=d(this);a.hasClass("altgallery-active")||a.css(a.data("style"))});b.onOpenItem[l]=function(){var b=f.find("a").eq(l);b.parent().find("a").removeClass("altgallery-active").css({opacity:a.thumbnail.alpha/100,borderColor:n(a.thumbnail.outlineColor)});b.addClass("altgallery-active").data("style",{opacity:1,borderColor:n(a.thumbnail.outlineColorOnClick)}).css(b.data("style"));
(function(){var f;if("horizontal"==i&&e<g){var b=0-(l*(a.thumbnail.width+5)-e/2+a.thumbnail.width/2),d=0-g+e;0<b&&(b=0);b<d&&(b=d);q.animate({left:b});q.unbind("mouseleave").mouseleave(function(){f=setTimeout(function(){q.animate({left:b},1E3)},1E3)})}else k<h&&(b=0-(l*(a.thumbnail.height+5)-k/2+a.thumbnail.height/2),d=0-h+k,0<b&&(b=0),b<d&&(b=d),q.animate({top:b}),q.unbind("mouseleave").mouseleave(function(){f=setTimeout(function(){q.animate({top:b},1E3)},1E3)}));q.unbind("mouseenter").mouseenter(function(){clearTimeout(f)})})()};
o.click(function(){b.currentItem=l;d(this).hasClass("altgallery-active")||b.open(c[l]);return!1});q.append(o);var F=new Image;F.onload=function(){var f=d('<img src="'+c[l].thumb+'" alt="" />');D(f);f.css({position:"absolute",border:"none"});f.css(z.fill(this.width,this.height,a.thumbnail.width-4,a.thumbnail.height-4));a.thumbnail.useShadow&&o.css({"-moz-box-shadow":"1px 1px 2px rgba(0, 0, 0, 0.5)","-webkit-box-shadow":"1px 1px 2px rgba(0, 0, 0, 0.5)","-khtml-box-shadow":"1px 1px 2px rgba(0, 0, 0, 0.5)",
boxShadow:"1px 1px 2px rgba(0, 0, 0, 0.5)"});o.append(f)};F.src=c[l].thumb})(o);f.append(q);(function(){function a(){o=!0;q.stop();A=setInterval(function(){var a=parseInt(q.css("left"))+20;0<a?(q.css("left",0),u()):q.css("left",a)},50)}function b(){o=!0;q.stop();A=setInterval(function(){var a=parseInt(q.css("left"))-20,f=0-g+e;a<f?(q.css("left",f),u()):q.css("left",a)},50)}function l(){o=!0;q.stop();A=setInterval(function(){var a=parseInt(q.css("top"))+20;0<a?(q.css("top",0),u()):q.css("top",a)},
50)}function c(){o=!0;q.stop();A=setInterval(function(){var a=parseInt(q.css("top"))-20,f=0-h+k;a<f?(q.css("top",f),u()):q.css("top",a)},50)}function u(){clearInterval(A);o=!1}var A,o=!1;"horizontal"==i&&e<g?f.mousemove(function(f){f=f.pageX-d(this).offset().left;50>f?o||a():f>e-50?o||b():u()}):k<h&&f.mousemove(function(a){a=a.pageY-d(this).offset().top;50>a?o||l():a>k-50?o||c():u()});f.mouseleave(function(){u()})})();l.element.append(f)}var b=this,a=this.settings,l=this.canvas,c=this.items;(function(){var f=
d('<div class="altgallery-imageFrame" style="position:absolute;"></div>'),b={};if(a.thumbBar.useThumbBar)switch(a.thumbBar.position.toLowerCase()){default:case "bottom":b.left=10;b.top=10;b.width=l.width()-20;b.height=l.height()-a.thumbnail.height-30;break;case "top":b.left=10;b.bottom=10;b.width=l.width()-20;b.height=l.height()-a.thumbnail.height-30;break;case "left":b.right=10;b.top=10;b.width=l.width()-a.thumbnail.width-30;b.height=l.height()-20;break;case "right":b.left=10,b.top=10,b.width=l.width()-
a.thumbnail.width-30,b.height=l.height()-20}else b.left=10,b.top=10,b.width=l.width()-20,b.height=l.height()-20;f.css(b);l.element.append(f)})();a.thumbBar.useThumbBar?(f(),l.element.find(".altgallery-thumbBar a").eq(b.currentItem).click()):b.open(b.getCurrentItem())};K.prototype.open=function(a){var b=this,c=this.settings,l=this.canvas,e=l.element.find(".altgallery-imageFrame"),s=d('<img class="altgallery-preloader" src="'+p.images.loader+'" alt="" />');D(s);s.css({position:"absolute",left:"50%",
top:"50%",zIndex:10,margin:"-16px 0 0 -16px"});g(a.source,function(i){s.hide();l.element.find(".altgallery-preloader").remove();var m=c.image.scaleMode.toLowerCase(),k="fill"==m?z.fill(i.width,i.height,e.width(),e.height()):z.fit(i.width,i.height,e.width(),e.height()),g;a.link?(g=d("<a></a>"),g.attr("href",a.link),a.target&&g.attr("target",a.target)):g=d("<div></div>");g.css({display:"block",position:"absolute",left:"fill"==m?0:k.left,top:"fill"==m?0:k.top,width:"fill"==m?e.width():k.width,height:"fill"==
m?e.height():k.height,overflow:"hidden","-moz-border-radius":c.image.cornerRadius/2,"-webkit-border-radius":c.image.cornerRadius/2,"-khtml-border-radius":c.image.cornerRadius/2,borderRadius:c.image.cornerRadius/2});c.image.useShadow&&g.css({"-moz-box-shadow":"1px 1px 2px rgba(0, 0, 0, 0.5)","-webkit-box-shadow":"1px 1px 2px rgba(0, 0, 0, 0.5)","-khtml-box-shadow":"1px 1px 2px rgba(0, 0, 0, 0.5)",boxShadow:"1px 1px 2px rgba(0, 0, 0, 0.5)"});var h=d('<img src="'+i.src+'" alt="" />');D(h);h.css({position:"absolute",
left:"fill"==m?k.left:0,top:"fill"==m?k.top:0,width:k.width,height:k.height});g.append(h);if(a.description&&"never"!=c.caption.visibleMode.toLowerCase()){var o=d("<div></div>");o.html(a.description);o.css({position:"absolute",left:0,width:k.width,padding:"9px 10px",fontFamily:c.caption.fontName,fontSize:c.caption.fontSize,lineHeight:1.25,color:n(c.caption.color),background:B(c.caption.bgColor,c.caption.bgAlpha/100)});if("top"==c.caption.position.toLowerCase()){if(o.css({top:0,borderBottom:"1px solid",
borderBottomColor:B("#000000",(c.caption.bgAlpha+10)/100)}),"onrollover"==c.caption.visibleMode.toLowerCase()){var q=1.25*c.caption.fontSize+18;o.css({top:-q}).hide();h.hover(function(){o.show().stop().animate({top:0},p.animation.duration)},function(){o.animate({top:-q},p.animation.duration,function(){o.hide()})})}}else o.css({bottom:0,borderTop:"1px solid",borderTopColor:B("#000000",(c.caption.bgAlpha+10)/100)}),"onrollover"==c.caption.visibleMode.toLowerCase()&&(q=1.25*c.caption.fontSize+18,o.css({bottom:-q}).hide(),
h.hover(function(){o.show().stop().animate({bottom:0},p.animation.duration)},function(){o.animate({bottom:-q},p.animation.duration,function(){o.hide()})}));g.append(o)}switch(c.image.transitionEffect.toLowerCase()){default:case "fade":e.animate({opacity:0},{duration:500*c.image.transitionDuration,easing:"linear",complete:function(){e.empty();e.append(g);e.animate({opacity:1},{duration:500*c.image.transitionDuration,easing:"swing",complete:function(){b.onOpen(i)}})}});break;case "xfade":case "crossfade":e.css({opacity:1}),
m=e.find("div"),m.size()?(m.animate({opacity:0},{duration:1E3*c.image.transitionDuration,easing:"linear",complete:function(){d(this).remove();b.onOpen(i)}}),e.append(g),g.css({opacity:0}).animate({opacity:1},{duration:1E3*c.image.transitionDuration,easing:"linear"})):(e.append(g),g.css({opacity:0}).animate({opacity:1},{duration:1E3*c.image.transitionDuration,easing:"linear",complete:function(){b.onOpen(i)}}))}b.onOpenItem[parseInt(a.id)]()});setTimeout(function(){l.element.find(".altgallery-preloader").remove();
e.append(s)},500)};K.prototype.prev=function(){0<this.currentItem?this.currentItem--:this.currentItem=this.items.length-1;this.open(this.getCurrentItem())};K.prototype.next=function(){this.currentItem<this.items.length-1?this.currentItem++:this.currentItem=0;this.open(this.getCurrentItem())};K.prototype.slideshowStart=function(){var a=this;a.slideshow=!0;a.onOpen=function(){a.slideshowTimer&&clearInterval(a.slideshowTimer);a.slideshowTimer=setTimeout(function(){a.next()},1E3*a.settings.slideshow.delay)};
if(a.settings.slideshow.stopAutoOnClick){var b=function(){a.slideshowStop();a.canvas.element.unbind("click",b).find("a").unbind("click",b)};a.canvas.element.bind("click",b).find("a").bind("click",b)}};K.prototype.slideshowStop=function(){this.onOpen=function(){};this.slideshow=!1;clearInterval(this.slideshowTimer)};L.prototype.render=function(a){var b=this,c=this.canvas,l=this.items,e=this.settings;if(a===t)a=b.page;c.element.empty();var g=c.width(),i=c.height(),m=parseInt((g-40)/parseInt(e.thumbnail.width));
1>m&&(m=1);var k=parseInt((i-40)/parseInt(e.thumbnail.height));1>k&&(k=1);var h=Math.ceil(l.length/m);k>h&&(k=h);h=m*k;a*=h;b.pagesCount=Math.ceil(l.length/h);var C=parseInt(e.thumbnail.width)+2,o=parseInt(e.thumbnail.height)+2,q=(g-C*m)/2-8,w=(i-o*k)/2-8,y=d('<div class="altgallery-frame" />'),g={position:"absolute",left:parseInt(q),top:parseInt(w),width:parseInt(g-2*(q+8))+14,height:parseInt(i-2*(w+8))+14,overflow:"hidden",background:n(e.colorScheme.thumbsFrameColor),"-moz-border-radius":"4px",
"-webkit-border-radius":"4px","-khtml-border-radius":"4px",borderRadius:"4px"};e.colorScheme.useShadow&&(g=d.extend(g,{"-moz-box-shadow":"0 0 10px rgba(0, 0, 0, 0.5)","-webkit-box-shadow":"0 0 10px rgba(0, 0, 0, 0.5)","-khtml-box-shadow":"0 0 10px rgba(0, 0, 0, 0.5)",boxShadow:"0 0 10px rgba(0, 0, 0, 0.5)"}));y.css(g);0<b.page&&(i=d('<a class="altgallery-page" style="left:4px; background:no-repeat center; -moz-border-radius:4px; -webkit-border-radius:4px; border-radius:4px;"></a>'),i.css({backgroundImage:v(p.images.left)}),
i.click(function(){b.prevPage()}),y.append(i));b.page<b.pagesCount-1&&(i=d('<a class="altgallery-page" style="right:4px; background:no-repeat center; -moz-border-radius:4px; -webkit-border-radius:4px; border-radius:4px;"></a>'),i.css({backgroundImage:v(p.images.right)}),i.click(function(){b.nextPage()}),y.append(i));y.find(".altgallery-page").css({position:"absolute",width:"30px",height:"30px",top:parseInt(g.height/2)-15,zIndex:20,cursor:"pointer"});"ontouchstart"in document.documentElement||y.hover(function(){y.find(".altgallery-page").show()},
function(){y.find(".altgallery-page").hide()});c.element.append(y);i=d('<div class="altgallery-frameMask" />');g.background="#000";g.opacity=0.6;g.zIndex=20;g["-moz-box-shadow"]="none";g["-webkit-box-shadow"]="none";g["-khtml-box-shadow"]="none";g.boxShadow="none";i.css(g).hide();c.element.append(i);var F=parseInt(e.thumbnail.alpha)/100,j=n(e.colorScheme.imageBGColor),R=k=1;for(e=a,g=-1,i=l.length;e<i&&!(e>=h+a);e++){e%m||g++;k=e%m*C+8;R=g*o+8;(function(a,f,e){c.drawImage(l[a],{x:parseInt(f),y:parseInt(e),
z:10,width:b.settings.thumbnail.width,height:b.settings.thumbnail.height,scaleMode:"fill",opacity:F,background:j,onclick:function(){b.currentItem=a;b.open(b.getCurrentItem(),{left:parseInt(f+q),top:parseInt(e+w)});return!1},onmouseover:function(){d(this).children("img").css({opacity:1})},onmouseout:function(){d(this).children("img").css({opacity:F})}},".altgallery-frame")})(e,k,R)}};L.prototype.open=function(a,b){var c=this,l=this.settings,e=d('<img class="altgallery-preloader" src="'+p.images.loader+
'" alt="" />');D(e);e.css({position:"absolute",left:"50%",top:"50%",zIndex:10,margin:"-16px 0 0 -16px"});var h=d('<img src="'+a.thumb+'" />');g(a.thumb,function(i){d(".altgallery-imageFrame",c.canvas.element).remove();d(".altgallery-frameMask",c.canvas.element).fadeIn(p.animation.duration);var g=document.createElement("div");d(g).addClass("altgallery-imageFrame").css({position:"absolute",padding:8,background:n(l.colorScheme.imageBGColor),zIndex:30});d(g).hide();var k=z.fit(i.width,i.height,c.canvas.width()-
48,c.canvas.height()-48),E={left:k.left+16+k.width/3,top:k.top+16+k.height/3,width:k.width/3,height:k.height/3};if(b!==t){if(b.left!==t)E.left=b.left;if(b.top!==t)E.top=b.top}d(g).css(E);var i=z.fit(i.width,i.height,c.canvas.width()-48,c.canvas.height()-48),C={left:i.left+16+i.width/3,top:i.top+16+i.height/3,width:i.width/3,height:i.height/3,margin:0,padding:0,border:"none",maxWidth:"none",maxHeight:"none",cursor:"pointer"};h.css(C);d(g).append(h);c.canvas.element.append(g);h.animate(i,p.animation.duration);
d(g).animate({opacity:"show",left:k.left+16,top:k.top+16,width:k.width,height:k.height},p.animation.duration,function(){var b=d("<div></div>");b.css({position:"absolute",left:8,top:8,width:k.width,height:k.height,overflow:"hidden",cursor:"pointer"});if(a.description){var i=parseInt(l.imageCaption.fontSize),i=i||c.defaultSettings.imageCaption.fontSize,w=d("<div><div>"+a.description+"</div></div>");w.css({position:"absolute",left:0,width:k.width,fontFamily:l.imageCaption.fontName,fontSize:i+"px",lineHeight:1.25,
color:n(l.imageCaption.color),background:B(l.imageCaption.bgColor,l.imageCaption.bgAlpha/100)});b.append(w);d(g).append(b);"bottom"==l.imageCaption.position.toLowerCase()?(w.css({bottom:"-33px",borderTop:"1px solid "+B(l.imageCaption.bgColor,(l.imageCaption.bgAlpha+10)/100)}),w.children("div").css({padding:"8px 10px 10px"}),w.animate({bottom:0})):(w.css({top:"-33px",borderBottom:"1px solid "+B(l.imageCaption.bgColor,(l.imageCaption.bgAlpha+10)/100)}),w.children("div").css({padding:"10px 10px 8px"}),
w.animate({top:0}))}var y=d('<a class="altgallery-close" style="position:absolute; right:-15px; top:-13px; width:30px; height:30px; z-index:40; background:no-repeat center; cursor:pointer;"></a>');y.css({backgroundImage:v(p.images.close)});y.click(function(){d(this).remove();w&&w.remove();E.opacity="hide";d(g).animate(E,p.animation.duration,function(){d(this).remove()});h.animate(C,p.animation.duration);d(".altgallery-frameMask",c.canvas.element).fadeOut(p.animation.duration)});d(g).append(y);b.click(function(){y.remove();
w&&w.remove();E.opacity="hide";d(g).animate(E,p.animation.duration,function(){d(this).remove();c.next()});h.animate(C,p.animation.duration)});setTimeout(function(){d(g).append(e)},500)})});g(a.source,function(){e.hide();c.canvas.element.find(".altgallery-preloader").remove();d(h).attr("src",a.source)})};L.prototype.prev=function(){this.currentItem--;if(0>this.currentItem)this.currentItem=this.items.length-1;this.open(this.getCurrentItem())};L.prototype.next=function(){this.currentItem++;if(this.currentItem>=
this.items.length)this.currentItem=0;this.open(this.getCurrentItem())};L.prototype.prevPage=function(){this.page--;this.render(this.page)};L.prototype.nextPage=function(){this.page++;this.render(this.page)};r.prototype.init=function(){var a=this.settings;this.initFrame();this.initNavigation();this.initCaption();this.initButtons();this.initThumbnails();this.initImage();switch(a.initialState.toLowerCase()){case "show thumbnails":this.showThumbnails();break;default:case "load image":case "show image":this.showImage();
break;case "start slideshow":this.showImage(),this.slideshowStart()}};r.prototype.initFrame=function(){var f=this.canvas,b=this.settings,c=this.frame=d("<div></div>"),l=f.width()-10,e=f.height()-10;c.css({position:"absolute",left:5,top:5,width:l,height:e,overflow:"hidden",background:n(b.buttons.bgColor)});a(c,{borderRadius:"5px",boxShadow:"0 0 4px rgba(0, 0, 0, 0.5)"});var g=this.content=d("<div></div>"),l=this.contentWidth=l-18,e=this.contentHeight=e-43;g.css({position:"absolute",left:9,top:9,width:l,
height:e,background:n(b.base.color)});a(g,{borderRadius:"4px"});c.append(g);b=this.preloader=d('<img alt="" />');b.attr("src",p.images.loader);b.css({position:"absolute",left:"50%",top:"50%",zIndex:100,margin:"-16px 0 0 -16px"});g.append(b);f.append(c)};r.prototype.initNavigation=function(){this.initPrevButton();this.initNextButton()};r.prototype.initPrevButton=function(){var f=this.settings,b=d("<div></div>");b.css({position:"absolute",left:0,top:this.contentHeight/2-20,zIndex:10,width:21,height:60,
background:n(f.buttons.bgColor),cursor:"default"});a(b,{borderRadius:"10px",boxShadow:"5px 0 15px rgba(0, 0, 0, 0.5)"});this.frame.append(b);prevOverlay=d("<div></div>");prevOverlay.css({position:"absolute",left:0,top:this.contentHeight/2-30,zIndex:10,width:9,height:80,background:n(f.buttons.bgColor),cursor:"default"});this.frame.append(prevOverlay);var c=this.prevButton=d('<div><div style="margin:25px 0 0 6px; width:9px; height:9px; background:url('+p.images.folder+'cubic-buttons.png) no-repeat -8px -8px;"></div></div>');
c.css({position:"absolute",left:0,top:this.contentHeight/2-20,zIndex:10,width:21,height:60,cursor:"pointer"});this.frame.append(c);var l;this.canvas.element.hover(function(){clearTimeout(l);b.stop().show().css({opacity:1}).animate({left:0});c.stop().animate({left:0,opacity:1})},function(){l=setTimeout(function(){b.stop().animate({left:-12},function(){b.fadeOut()});c.stop().animate({left:-12,opacity:0})},100)});this.hidePrevButton=function(){b.css({visibility:"hidden"});prevOverlay.css({visibility:"hidden"});
c.css({visibility:"hidden"})};this.showPrevButton=function(){b.css({visibility:"visible"});prevOverlay.css({visibility:"visible"});c.css({visibility:"visible"})}};r.prototype.initNextButton=function(){var f=this.settings,b=d("<div></div>");b.css({position:"absolute",right:0,top:this.contentHeight/2-20,zIndex:10,width:21,height:60,background:n(f.buttons.bgColor),cursor:"default"});a(b,{borderRadius:"10px",boxShadow:"-5px 0 15px rgba(0, 0, 0, 0.5)"});this.frame.append(b);nextOverlay=d("<div></div>");
nextOverlay.css({position:"absolute",right:0,top:this.contentHeight/2-30,zIndex:10,width:9,height:80,background:n(f.buttons.bgColor),cursor:"default"});this.frame.append(nextOverlay);var c=this.nextButton=d('<div><div style="margin:25px 0 0 6px; width:9px; height:9px; background:url('+p.images.folder+'cubic-buttons.png) no-repeat -8px -33px;"></div></div>');c.css({position:"absolute",right:0,top:this.contentHeight/2-20,zIndex:10,width:21,height:60,cursor:"pointer"});this.frame.append(c);var l;this.canvas.element.hover(function(){clearTimeout(l);
b.stop().show().css({opacity:1}).animate({right:0});c.stop().animate({right:0,opacity:1})},function(){l=setTimeout(function(){b.stop().animate({right:-12},function(){b.fadeOut()});c.stop().animate({right:-12,opacity:0})},100)});this.hideNextButton=function(){b.css({visibility:"hidden"});nextOverlay.css({visibility:"hidden"});c.css({visibility:"hidden"})};this.showNextButton=function(){b.css({visibility:"visible"});nextOverlay.css({visibility:"visible"});c.css({visibility:"visible"})}};r.prototype.initCaption=
function(){var a=this.caption=d("<div></div>");a.css({position:"absolute",left:10,bottom:10,width:this.contentWidth-60,overflow:"hidden",fontFamily:"Arial, Helvetica, sans-serif",fontSize:"11px",color:"#777"});this.frame.append(a)};r.prototype.initButtons=function(){var f=this,b=f.settings,c=function(){d(this).css({borderColor:"#fff #bbb #bbb #fff"});a(this,{boxShadow:"0 0 2px rgba(0, 0, 0, 0.2)"})},l=function(){d(this).css({borderColor:"transparent"});a(this,{boxShadow:"none"})};if(b.buttons.showSlideshowButton){var e=
f.slideshowButton=d("<div></div>");e.css({position:"absolute",right:b.buttons.showThumbnailsButton?29:5,bottom:5,width:23,height:23,background:v(p.images.folder+"cubic-buttons.png")+" no-repeat 0px -51px",border:"1px solid",borderColor:"transparent",cursor:"pointer"});a(e,{borderRadius:"3px 4px 3px 4px"});e.hover(c,l);e.click(function(){f.showImage();f.slideshowStart()});f.frame.append(e)}if(b.buttons.showThumbnailsButton)b=f.showThumbnailsButton=d("<div></div>"),b.css({position:"absolute",right:5,
bottom:5,width:23,height:23,background:v(p.images.folder+"cubic-buttons.png")+" no-repeat -1px -126px",border:"1px solid",borderColor:"transparent",cursor:"pointer"}).hide(),a(b,{borderRadius:"3px 4px 3px 4px"}),b.hover(c,l),b.click(function(){f.showThumbnails()}),f.frame.append(b),b=f.showImagesButton=d("<div></div>"),b.css({position:"absolute",right:5,bottom:5,width:23,height:23,background:v(p.images.folder+"cubic-buttons.png")+" no-repeat -1px -101px",border:"1px solid",borderColor:"transparent",
cursor:"pointer"}).hide(),a(b,{borderRadius:"3px 4px 3px 4px"}),b.hover(c,l),b.click(function(){f.showImage()}),f.frame.append(b)};r.prototype.initImage=function(){var f=this.imageWidth=this.contentWidth-2*this.settings.base.visibleFrame,b=this.imageHeight=this.contentHeight-2*this.settings.base.visibleFrame,c=this.imagesFrame=d("<div></div>");c.css({position:"absolute",left:this.settings.base.visibleFrame,top:this.settings.base.visibleFrame,width:f,height:b,overflow:"hidden"}).hide();a(c,{borderRadius:"3px"});
this.content.append(c);f=this.imagesContainer=d("<div></div>");f.css({position:"relative",left:0,top:0});c.append(f)};r.prototype.showImage=function(a){var b=this,d=function(){b.cleanup();b.thumbnailsFrame.hide();b.imagesFrame.show();b.showImagesButton.hide();b.showThumbnailsButton.show();b.showPrevButton();b.showNextButton();b.prevButton.unbind("click").click(function(){b.slideshowStop();b.prev()});b.nextButton.unbind("click").click(function(){b.slideshowStop();b.next()})};!1!==a?(b.hidePrevButton(),
b.hideNextButton(),b.open(b.getCurrentItem(),d)):d()};r.prototype.initThumbnails=function(){function f(){b.cleanup()}var b=this,c=b.canvas,l=b.thumbnailsWidth=b.contentWidth-2*b.settings.base.visibleFrame,e=b.thumbnailsHeight=b.contentHeight-2*b.settings.base.visibleFrame,h=b.thumbnailsFrame=d("<div></div>");h.css({position:"absolute",left:b.settings.base.visibleFrame,top:b.settings.base.visibleFrame,width:l,height:e,overflow:"hidden"}).hide();a(h,{borderRadius:"3px"});b.content.append(h);var i=b.thumbnailsContainer=
d("<div></div>");i.css({position:"relative",left:0,top:0});h.append(i);for(var m=Math.round((l-5)/5),k=Math.round((e-4)/4),E=Math.round((l-5*m)/10),C=Math.round((e-4*k)/8),e=0;e<b.items.length;e++)(function(e,h){g(h.thumb,function(g){var A=e%5,s=Math.floor(e%20/5),j=d('<div class="altgallery-thumbnail altgallery-thumbnail-'+e+'"></div>');j.css({position:"absolute",left:A*m+Math.floor(e/20)*l+1*A+E,top:s*k+1*s+C,width:m,height:k,overflow:"hidden",cursor:"pointer",zIndex:Math.floor(e%20/5)});a(j,{boxShadow:"0px 3px 3px rgba(0, 0, 0, 0.5)"});
j.mouseover(function(){if(b.enableThumbnailsHover){var C=0;0==A?C=m/8:4==A&&(C=-m/8);var E=0;0==s?E=k/8:3==s&&(E=-k/8);b.updateCaption(h.description||"Image "+(e+1)+" / "+b.items.length);b.cleanup();c.element.find(".altgallery-thumbnail").css({opacity:0.8});var j=d(this).clone();j.addClass("altgallery-clone");j.css({left:d(this).offset().left-i.offset().left,top:d(this).offset().top-i.offset().top,zIndex:10,opacity:1});a(j,{boxShadow:"5px 15px 13px rgba(0, 0, 0, 0.7)"});i.append(j);var p=j.find("img");
j.animate({width:1.25*m,height:1.25*k,marginLeft:-m/8+C,marginTop:-k/8+E},{duration:"fast",easing:"linear",step:function(){p.css(z.fill(g.width,g.height,j.width(),j.height()))}});j.click(function(){b.currentItem=e;j.unbind("mouseleave");b.canvas.element.unbind("mouseleave",f);a(j,{boxShadow:"none"});j.animate({left:b.currentPage*l,top:0,width:b.imageWidth,height:b.imageHeight,marginLeft:0,marginTop:0},{duration:"normal",step:function(){p.css(z.fill(g.width,g.height,j.width(),j.height()))},complete:function(){b.showImage()}})});
j.mouseleave(function(){b.cleanup();b.updateCaption(" ")})}});j.click(function(){b.currentItem=e;b.showImage()});var p=d('<img style="position:absolute;" />');p.attr("src",h.thumb);p.css(z.fill(g.width,g.height,m,k));j.append(p);i.append(j)})})(e,b.items[e]);b.canvas.element.mouseleave(f);b.currentPage=0;b.preloader.hide()};r.prototype.showThumbnails=function(){var a=this;a.slideshow&&a.slideshowStop();a.updateCaption(" ");a.imagesFrame.hide();a.thumbnailsFrame.show();a.showThumbnailsButton.hide();
a.showImagesButton.show();a.prevButton.unbind("click").click(function(){if(0<a.currentPage)a.currentPage--,a.enableThumbnailsHover=!1,a.cleanup(),a.thumbnailsContainer.stop().animate({left:-a.currentPage*a.thumbnailsWidth},2*p.animation.duration,function(){a.enableThumbnailsHover=!0});a.updateNavigation()});a.nextButton.unbind("click").click(function(){if(a.currentPage<Math.floor(a.items.length/20))a.currentPage++,a.enableThumbnailsHover=!1,a.cleanup(),a.thumbnailsContainer.stop().animate({left:-a.currentPage*
a.thumbnailsWidth},2*p.animation.duration,function(){a.enableThumbnailsHover=!0});a.updateNavigation()});a.updateNavigation()};r.prototype.updateNavigation=function(){var a=Math.ceil(this.items.length/20);0==this.currentPage?this.hidePrevButton():this.showPrevButton();this.currentPage==a-1?this.hideNextButton():this.showNextButton()};r.prototype.updateCaption=function(a){(a=a||this.getCurrentItem().description)?this.caption.html(a):this.caption.html("Image "+(this.currentItem+1)+" / "+this.items.length)};
r.prototype.open=function(a,b){var c=this,l="altgallery-image-"+c.currentItem;c.imagesContainer.find("."+l).size()?"function"==typeof b&&b():(c.preloader.show(),g(a.source,function(a){var f=d('<div class="'+l+'"></div>');f.css({position:"absolute",left:c.imageWidth*c.currentItem,top:0,width:c.imageWidth,height:c.imageHeight,overflow:"hidden"});var e=d('<img style="position:absolute;" />');e.attr("src",a.src);e.css(z.fill(a.width,a.height,c.imageWidth,c.imageHeight));f.append(e);c.imagesContainer.append(f);
c.preloader.hide();"function"==typeof b&&b()}));c.imagesContainer.stop().css({left:-c.imageWidth*c.currentItem});c.updateCaption()};r.prototype.prev=function(){var a=this;if(0<a.currentItem){a.currentItem--;var b=setTimeout(function(){a.preloader.show()},500);g(a.getCurrentItem().source,function(c){clearTimeout(b);a.preloader.hide();var e="altgallery-image-"+a.currentItem;if(!a.imagesContainer.find("."+e).size()){e=d('<div class="'+e+'"></div>');e.css({position:"absolute",left:a.imageWidth*a.currentItem,
top:0,width:a.imageWidth,height:a.imageHeight,overflow:"hidden"});var g=d('<img style="position:absolute;" />');g.attr("src",c.src);g.css(z.fill(c.width,c.height,a.imageWidth,a.imageHeight));e.append(g);a.imagesContainer.append(e)}a.imagesContainer.stop().animate({left:-a.imageWidth*a.currentItem},2*p.animation.duration);a.updateCaption()})}else a.currentItem=a.items.length-1,a.showImage()};r.prototype.next=function(){var a=this;if(a.currentItem<a.items.length-1){a.currentItem++;var b=setTimeout(function(){a.preloader.show()},
500);g(a.getCurrentItem().source,function(c){clearTimeout(b);a.preloader.hide();var e="altgallery-image-"+a.currentItem;if(!a.imagesContainer.find("."+e).size()){e=d('<div class="'+e+'"></div>');e.css({position:"absolute",left:a.imageWidth*a.currentItem,top:0,width:a.imageWidth,height:a.imageHeight,overflow:"hidden"});var g=d('<img style="position:absolute;" />');g.attr("src",c.src);g.css(z.fill(c.width,c.height,a.imageWidth,a.imageHeight));e.append(g);a.imagesContainer.append(e)}a.imagesContainer.stop().animate({left:-a.imageWidth*
a.currentItem},2*p.animation.duration,function(){a.slideshow&&a.slideshowStart()});a.updateCaption()})}else a.currentItem=0,a.showImage(),a.slideshow&&a.slideshowStart()};r.prototype.slideshowStart=function(){var a=this;a.showImage(!1);clearTimeout(a.slideshowTimer);a.slideshow=!0;a.slideshowButton.css({background:v(p.images.folder+"cubic-buttons.png")+" no-repeat 0px -76px"});a.slideshowButton.unbind("click").click(function(){a.slideshowStop()});a.slideshowTimer=setTimeout(function(){a.next()},1E3*
a.settings.slideshowDelay)};r.prototype.slideshowStop=function(){var a=this;a.slideshow=!1;clearTimeout(a.slideshowTimer);a.slideshowButton.css({background:v(p.images.folder+"cubic-buttons.png")+" no-repeat 0px -51px"});a.slideshowButton.unbind("click").click(function(){a.slideshowStart()})};r.prototype.cleanup=function(){this.canvas.element.find(".altgallery-clone").remove();d(this.canvas.element).find(".altgallery-thumbnail").css({opacity:1})};H.prototype.showScrollbar=function(){var a=this,b=this.settings,
c=this.canvas,e=d('<div class="altgallery-scrollbar"></div>'),g=Math.round(0.8*c.width())-36;e.css({position:"absolute",zIndex:1E3,left:(c.width()-g)/2,bottom:5,width:g+36,height:17,background:B(b.scrollbar.bgColor,b.scrollbar.bgAlpha/100),"-moz-border-radius":8,"-webkit-border-radius":8,borderRadius:8});if(d.browser.msie&&9>d.browser.version){var h=sprintf("%02x%s",255*b.scrollbar.bgAlpha/100,n(b.scrollbar.bgColor).replace("#",""));e.css({filter:"progid:DXImageTransform.Microsoft.gradient(startColorstr=#"+
h+",endColorstr=#"+h+")"})}var i=d('<div class="altgallery-scrollbar-handle"></div>'),m=g/a.items.length;i.css({position:"absolute",left:Math.round(a.currentItem*m),width:Math.floor(m),height:13,background:n(b.scrollbar.handleColor),opacity:b.scrollbar.handleAlpha/100,cursor:"default"});i.hover(function(){i.css({opacity:1})},function(){i.css({opacity:b.scrollbar.handleAlpha/100})});h=d("<div></div>");h.css({position:"relative",top:2,height:13,margin:"0 18px"});h.click(function(b){b=b.pageX-d(this).offset().left;
a.currentItem=Math.floor(b/g*a.items.length);i.css({left:Math.round(a.currentItem*m)});a.animate()});var k={position:"absolute",top:2,width:16,height:16,fontFamily:"Arial, Helvetica, sans-serif",fontSize:"10px",lineHeight:"14px",textAlign:"center",color:n(b.scrollbar.arrowsColor),opacity:b.scrollbar.arrowsAlpha/100,cursor:"pointer"},j=d("<div>&#9668;</div>");j.css(k);j.css({left:1});j.click(function(){a.prev()});e.append(j);j=d("<div>&#9658;</div>");j.css(k);j.css({right:1});j.click(function(){a.next()});
e.append(j);h.append(i);e.append(h);c.element.append(e)};H.prototype.updateScrollbar=function(){var a=this.canvas,b=(Math.round(0.8*a.width())-36)/this.items.length;a.element.find(".altgallery-scrollbar-handle").css({left:Math.round(this.currentItem*b)})};H.prototype.getItemStyle=function(a,b){var d=this.settings,c=this.canvas,e,g;e=this.getItemX(b);g=this.getItemZ(b);var i;i=Math.abs(e);var h=z.fit(a.width,a.height,d.maxImageWidth*(1>i?1:2>i?0.55:3>i?0.5:0.6-0.05*i),c.height()-60);return{zIndex:g,
left:(c.width()-h.width)/2+e*c.width()/8+(e?e/i*d.maxImageWidth/3:0),top:(c.height()-h.height)/2-30,width:h.width,height:h.height,opacity:e?0.8:1,transform:{rotateY:-(e?e/i:0)*d.imageAngle+"deg"}}};H.prototype.render=function(){function a(f,i){g(h[f].source,function(a){var g=b.getItemStyle(a,f),k=d('<a class="altgallery-item-'+f+'"></a>');h[f].link&&(k.attr("href",h[f].link),h[f].target&&k.attr("target",h[f].target));k.css({display:"block",position:"absolute",zIndex:g.zIndex,left:g.left,top:g.top,
width:g.width,height:g.height,overflow:"visible",background:"#000",cursor:"pointer",outline:"none"});c(k,{rotateY:g.transform.rotateY});var m=d('<img src="" alt="" />');m.attr("src",a.src);D(m);m.css({display:"block",width:g.width,height:g.height,opacity:g.opacity});k.append(m);if(b.showReflections){a=m.clone();a.css({position:"absolute",opacity:e.reflectionAlpha/100,"-moz-transform":"scaleY(-1)","-webkit-transform":"scaleY(-1)","-o-transform":"scaleY(-1)","-ms-transform":"scaleY(-1)",transform:"scaleY(-1)",
zIndex:1});var j=d('<div class="altgallery-overlay"></div>');j.css({position:"absolute",top:g.height,width:g.width,height:g.height,background:l.element.css("backgroundColor"),zIndex:0});var p=d('<div class="altgallery-overlay"></div>');p.css({position:"absolute",top:g.height,width:g.width,height:g.height,zIndex:2});var g=l.element.css("backgroundColor"),s=[B(g,0),B(g,0.5),B(g,1)];d.browser.mozilla?p.css({background:"-moz-linear-gradient(top, "+s[0]+" 0%, "+s[1]+" 15%, "+s[2]+" 50%)"}):d.browser.webkit?
p.css({background:"-webkit-linear-gradient(top, "+s[0]+" 0%, "+s[1]+" 15%, "+s[2]+" 50%)"}):d.browser.opera?p.css({background:"-o-linear-gradient(top, "+s[0]+" 0%, "+s[1]+" 15%, "+s[2]+" 50%)"}):d.browser.msie?(g=n(g).replace("#",""),p.css({filter:"progid:DXImageTransform.Microsoft.gradient(startColorstr=#00"+g+",endColorstr=#ff"+g+",GradientType=0)"})):p.css({background:"linear-gradient(top, "+s[0]+" 0%, "+s[1]+" 15%, "+s[2]+" 50%)"});k.append(a);k.append(j);k.append(p)}k.click(function(){b.currentItem+=
i;if(0>b.currentItem)b.currentItem=0;else if(b.currentItem>=h.length)b.currentItem=h.length-1;b.animate();return!1}).hover(function(){m.css({opacity:1})},function(){m.css({opacity:i?0.8:1})});f==b.currentItem&&k.unbind("click");b.scene.append(k)})}var b=this,e=this.settings,l=this.canvas,h=this.items;b.scene.empty();b.scene.css({"-webkit-perspective":400,"-moz-perspective":400,perspective:400});var j,i,m,k,p;k=b.currentItem;p=2*Math.max(k,h.length-k);for(j=1;j<=p;j++)i=k+(j%2?parseInt(j/2):-parseInt(j/
2)),0<=i&&i<h.length&&(m=b.getItemX(i),a(i,m));e.useScrollBar&&b.showScrollbar();d.browser.mozilla&&b.showReflections&&b.animate()};H.prototype.animate=function(){function a(f,i){g(e[f].source,function(a){var g=b.scene.find(".altgallery-item-"+f),h=g.find("img"),k={left:parseInt(g.css("left")),top:parseInt(g.css("top")),width:g.width(),height:g.height(),opacity:g.find("img").css("opacity"),transform:c(g)},m=b.getItemStyle(a,f);g.show().css({zIndex:m.zIndex});g.unbind("click").click(function(){b.currentItem+=
i;if(0>b.currentItem)b.currentItem=0;else if(b.currentItem>=e.length)b.currentItem=e.length-1;b.animate();return!1}).unbind("hover").hover(function(){h.first().css({opacity:1})},function(){h.first().css({opacity:i?0.8:1})});h.first().css({opacity:m.opacity});var j=g.find(".altgallery-overlay");g.animate({animate:1E4},{duration:800*d.flipDuration,easing:"easeOutCubic",step:function(a){function d(b){return k[b]+(m[b]-k[b])*a/1E4}g.css({left:Math.round(d("left")),top:Math.round(d("top")),width:Math.round(d("width")),
height:Math.round(d("height"))});h.css({width:Math.round(d("width")),height:Math.round(d("height"))});b.showReflections&&j.css({top:Math.round(d("height")),width:Math.round(d("width")),height:Math.round(d("height"))});c(this,{rotateY:parseInt(k.transform.rotateY)+(parseInt(m.transform.rotateY)-parseInt(k.transform.rotateY))*a/1E4+"deg"})},complete:function(){g.prop("animate",0);f==b.currentItem&&g.unbind("click")}})})}var b=this,d=this.settings,e=this.items,h,j,i,m,k;m=b.currentItem;k=2*Math.max(m,
e.length-m);for(h=1;h<=k;h++)j=m+(h%2?parseInt(h/2):-parseInt(h/2)),0<=j&&j<e.length&&(i=b.getItemX(j),a(j,i));d.useScrollBar&&b.updateScrollbar()};H.prototype.showAlbums=function(){};H.prototype.open=function(){};H.prototype.prev=function(){0<this.currentItem&&(this.currentItem--,this.animate())};H.prototype.next=function(){this.currentItem<this.items.length-1&&(this.currentItem++,this.animate())};x.prototype.render=function(){var a=this,b=this.settings,c=this.canvas;c.element.css({fontFamily:b.fontName,
fontSize:parseInt(b.fontSize)+"px",lineHeight:1.2*parseInt(b.fontSize)+"px"});(function(){var e=d('<div class="altgallery-imageFrame"></div>');e.css({width:c.width()-2*b.frameSize,height:c.height()-2*b.frameSize,padding:b.frameSize,background:n(b.frameColor),borderRadius:b.cornerRadius/2});var g=d('<div class="altgallery-image"></div>');g.css({position:"relative",width:c.width()-2*b.frameSize,height:c.height()-2*b.frameSize,overflow:"hidden",background:n(b.backgroundColor),borderRadius:b.cornerRadius/
2-b.frameSize/4,cursor:"pointer"});var h=d('<img src="" alt="" />');D(g.children("img"));h.css({position:"absolute"});e.click(function(){a.next()});g.append(h);e.append(g);c.element.append(e);a.open(a.getCurrentItem())})();switch(b.initialState.toLowerCase()){default:case "show albums":this.showAlbums();break;case "show thumbnails":this.showThumbnails();case "load image":case "start slideshow":}};x.prototype.showAlbums=function(){function a(){function f(){var a=o*j+1,d=o*j+j;if(d>b.albums.length)d=
b.albums.length;w.html(a+"-"+d+" "+e.translation.Of+" "+b.albums.length);0>=o?(n.css({opacity:0.3,cursor:"default"}),n.unbind("click").click(function(){return!1})):(n.css({opacity:1,cursor:"pointer"}),n.unbind("click").click(t));o>=C-1?(r.css({opacity:0.3,cursor:"default"}),r.unbind("click").click(function(){return!1})):(r.css({opacity:1,cursor:"pointer"}),r.unbind("click").click(x))}b.hideThumbnails();b.hideButtons();b.hideCaption();b.hideNavigation();var h=d('<div class="altgallery-albums"></div>'),
i=c.width()-2*e.frameSize,m=e.iconHeight+115;h.css({position:"absolute",left:e.frameSize,top:(c.height()-m)/2,width:c.width()-2*e.frameSize,height:m,overflow:"hidden",color:"#fff",border:"1px #000",borderStyle:"solid none",zIndex:2});var k=d('<div class="altgallery-albums-overlay"></div>');k.css({position:"absolute",left:e.frameSize,top:(c.height()-m)/2,width:c.width()-2*e.frameSize,height:m+1,background:"#000",opacity:e.panelBackgroundAlpha/100,zIndex:1});c.element.append(k);m=d("<div></div>");m.css({position:"absolute",
top:10,right:20});k=d('<a class="altgallery-close" href="#">'+e.translation.Close+"</a>");k.css({marginRight:0,color:"#fff",fontWeight:"bold",textDecoration:"none",textShadow:"0 1px 0 rgba(0, 0, 0, 0.5)",background:"no-repeat left center",backgroundImage:v(p.images.folder+"zen-close.png"),paddingLeft:12});k.click(function(){b.hideAlbums();b.showButtons();b.showCaption();b.showNavigation();return!1});m.append(k);h.append(m);var j=Math.floor((i-20)/(e.iconWidth+e.iconPadding)),j=j>b.albums.length?b.albums.length:
j,m=(e.iconWidth+e.iconPadding)*j-e.iconPadding,k=(e.iconWidth+e.iconPadding)*b.albums.length-e.iconPadding,C=Math.ceil(b.albums.length/j),o=0,q=d("<div>"+e.translation.Albums+"</div>");q.css({position:"absolute",left:9,top:0,padding:10,paddingLeft:25,textShadow:"-1px 1px 0 rgba(0, 0, 0, 0.5)",fontWeight:"bold",background:"no-repeat left center",backgroundImage:v(p.images.folder+"zen-albums.png")});h.append(q);var w=d("<span></span>");w.css({marginLeft:"1em",fontWeight:"normal"});q.append(w);q=d("<div></div>");
q.css({position:"absolute",left:(i-m)/2-4,top:42,width:m+4,height:e.iconHeight+70,overflow:"hidden"});var y=d("<div></div>");y.css({position:"relative",left:0,width:k});q.append(y);i=d("<div></div>");i.css({position:"absolute",right:4,bottom:3,height:20,opacity:0.9});var n=d('<a href="#" style="float:left;"></a>');n.css({display:"block",cssFloat:"left",width:16,height:16,marginRight:3,background:"no-repeat center",backgroundImage:v(p.images.folder+"zen-prev.png")});var t=function(){o--;var a=(e.iconWidth+
e.iconPadding)*j*o;y.stop();y.animate({left:-a},2*p.animation.duration,"easeOutQuart");f();return!1};n.click(t);i.append(n);h.append(q);var r=d('<a href="#" style="float:left;"></a>');r.css({display:"block",cssFloat:"left",width:16,height:16,marginRight:3,background:"no-repeat center",backgroundImage:v(p.images.folder+"zen-next.png")});var x=function(){o++;var a=(e.iconWidth+e.iconPadding)*j*o;y.stop();y.animate({left:-a},2*p.animation.duration,"easeOutQuart");f();return!1};r.click(x);i.append(r);
h.append(i);f();for(i=0;i<b.albums.length;i++)(function(a,c){var f=d("<div></div>");f.css({position:"absolute",left:(e.iconWidth+e.iconPadding)*c,top:0,width:e.iconWidth+e.iconPadding+6,overflow:"hidden",textShadow:"0 1px 0 rgba(0, 0, 0, 0.5)"});var i=d("<div></div>");i.css({position:"relative",width:e.iconWidth-2,height:e.iconHeight-2,overflow:"hidden",border:"1px solid",borderColor:b.currentAlbum==c?"#000":"#fff",margin:"2px",cursor:"pointer"});g(a.items[0].thumb,function(a){var b=d('<img src="" alt="" />');
b.attr("src",a.src);D(b);b.css({position:"absolute"});b.css(z.fill(a.width,a.height,e.iconWidth-2,e.iconHeight-2));i.append(b)},50*c);f.append(i);f.append('<div style="padding:7px 2px 2px; font-weight:bold;">'+(a.description||"Album "+(c+1))+"<div>");f.append('<div style="padding:1px 2px;">'+a.items.length+" "+(1==a.items.length?e.translation.Image:e.translation.Images)+"<div>");f.hover(function(){i.css({borderWidth:"3px",margin:"0px"})},function(){i.css({borderWidth:"1px",margin:"2px"})}).click(function(){if(b.currentAlbum!=
c)b.currentItem=-1;b.currentAlbum=c;b.showThumbnails()});y.append(f)})(b.albums[i],i);c.element.append(h)}var b=this,c=this.canvas,e=this.settings;c.element.find(".altgallery-albums").size()||a()};x.prototype.hideAlbums=function(){this.canvas.element.find(".altgallery-albums, .altgallery-albums-overlay").remove()};x.prototype.showThumbnails=function(){function a(){function f(){var a=q*n+1,b=q*n+n;if(b>h.items.length)b=h.items.length;y.html(a+"-"+b+" "+e.translation.Of+" "+h.items.length);0>=q?(r.css({opacity:0.3,
cursor:"default"}),r.unbind("click").click(function(){return!1})):(r.css({opacity:1,cursor:"pointer"}),r.unbind("click").click(t));q>=o-1?(x.css({opacity:0.3,cursor:"default"}),x.unbind("click").click(function(){return!1})):(x.css({opacity:1,cursor:"pointer"}),x.unbind("click").click(B))}b.hideAlbums();b.hideButtons();b.hideCaption();b.hideNavigation();var i=d('<div class="altgallery-images"></div>'),m=c.width()-2*e.frameSize,k=e.iconHeight+75;i.css({position:"absolute",left:e.frameSize,top:(c.height()-
k)/2,width:c.width()-2*e.frameSize,height:k,overflow:"hidden",color:"#fff",border:"1px #000",borderStyle:"solid none",zIndex:2});var j=d('<div class="altgallery-images-overlay"></div>');j.css({position:"absolute",left:e.frameSize,top:(c.height()-k)/2,width:c.width()-2*e.frameSize,height:k+1,background:"#000",opacity:e.panelBackgroundAlpha/100,zIndex:1});c.element.append(j);k=d("<div></div>");k.css({position:"absolute",top:10,right:20});1<b.albums.length&&(j=d('<a class="altgallery-back" href="#">'+
e.translation.BackToAlbums+"</a>"),j.css({marginRight:"1.5em",color:"#fff",fontWeight:"bold",textDecoration:"none",textShadow:"0 1px 0 rgba(0, 0, 0, 0.5)",background:"no-repeat left center",backgroundImage:v(p.images.folder+"zen-backToAlbums.png"),paddingLeft:14}),j.click(function(){b.showAlbums();return!1}),k.append(j));j=d('<a class="altgallery-close" href="#">'+e.translation.Close+"</a>");j.css({marginRight:0,color:"#fff",fontWeight:"bold",textDecoration:"none",textShadow:"0 1px 0 rgba(0, 0, 0, 0.5)",
background:"no-repeat left center",backgroundImage:v(p.images.folder+"zen-close.png"),paddingLeft:12});j.click(function(){b.hideThumbnails();b.showButtons();b.showCaption();b.showNavigation();return!1});k.append(j);i.append(k);var n=Math.floor((m-20)/(e.iconWidth+e.iconPadding)),n=n>h.items.length?h.items.length:n,k=(e.iconWidth+e.iconPadding)*n-e.iconPadding,j=(e.iconWidth+e.iconPadding)*h.items.length-e.iconPadding,o=Math.ceil(h.items.length/n),q=0,w=d("<div>"+e.translation.Images+"</div>");w.css({position:"absolute",
left:9,top:0,padding:10,paddingLeft:25,textShadow:"-1px 1px 0 rgba(0, 0, 0, 0.5)",fontWeight:"bold",background:"no-repeat left center",backgroundImage:v(p.images.folder+"zen-thumbnails.png")});i.append(w);var y=d("<span></span>");y.css({marginLeft:"1em",fontWeight:"normal"});w.append(y);w=d("<div></div>");w.css({position:"absolute",left:(m-k)/2-4,top:42,width:k+4,height:e.iconHeight+4,overflow:"hidden"});var F=d("<div></div>");F.css({position:"relative",left:0,width:j});w.append(F);i.append(w);m=
d("<div></div>");m.css({position:"absolute",right:4,bottom:3,height:20,opacity:0.9});var r=d('<a href="#" style="float:left;"></a>');r.css({display:"block",cssFloat:"left",width:16,height:16,marginRight:3,background:"no-repeat center",backgroundImage:v(p.images.folder+"zen-prev.png")});var t=function(){q--;var a=(e.iconWidth+e.iconPadding)*n*q;F.stop();F.animate({left:-a},2*p.animation.duration,"easeOutQuart");f();return!1};r.click(t);m.append(r);var x=d('<a href="#" style="float:left;"></a>');x.css({display:"block",
cssFloat:"left",width:16,height:16,marginRight:3,background:"no-repeat center",backgroundImage:v(p.images.folder+"zen-next.png")});var B=function(){q++;var a=(e.iconWidth+e.iconPadding)*n*q;F.stop();F.animate({left:-a},2*p.animation.duration,"easeOutQuart");f();return!1};x.click(B);m.append(x);i.append(m);f();for(m=0;m<h.items.length;m++)(function(a,c){var f=d("<div></div>");f.css({position:"absolute",left:(e.iconWidth+e.iconPadding)*c,top:0,width:e.iconWidth+e.iconPadding+6,overflow:"hidden",textShadow:"0 1px 0 rgba(0, 0, 0, 0.5)"});
var i=d("<div></div>");i.css({position:"relative",width:e.iconWidth-2,height:e.iconHeight-2,overflow:"hidden",border:"1px solid",borderColor:b.currentItem==c?"#000":"#fff",margin:"2px",cursor:"pointer"});g(a.thumb,function(a){var b=d('<img src="" alt="" />');b.attr("src",a.src);D(b);b.css({position:"absolute"});b.css(z.fill(a.width,a.height,e.iconWidth-2,e.iconHeight-2));i.append(b)},50*c);f.append(i);f.hover(function(){i.css({borderWidth:"3px",margin:"0px"})},function(){i.css({borderWidth:"1px",
margin:"2px"})}).click(function(){b.currentItem=c;b.open(b.getCurrentItem())});F.append(f)})(h.items[m],m);c.element.append(i)}var b=this,c=this.canvas,e=this.settings,h=this.getCurrentAlbum();c.element.find(".altgallery-images").size()||a()};x.prototype.hideThumbnails=function(){this.canvas.element.find(".altgallery-images, .altgallery-images-overlay").remove()};x.prototype.showButtons=function(){function a(){var c=d('<div class="altgallery-buttons"></div>');c.css({position:"absolute",right:b.settings.frameSize,
top:25+b.settings.frameSize,padding:"3px 3px 3px 1px",background:"rgba(0, 0, 0, "+b.settings.buttonsBackgroundAlpha/100+")",border:"1px solid rgba(0, 0, 0, 0.8)",borderRight:"none","-moz-border-top-left-radius":"3px","-moz-border-bottom-left-radius":"3px","-webkit-border-top-left-radius":"3px","-webkit-border-bottom-left-radius":"3px","border-top-left-radius":"3px","border-bottom-left-radius":"3px"});if(d.browser.msie&&9>d.browser.version){var f=Math.round(255*parseInt(b.settings.buttonsBackgroundAlpha)/
100),f=16>f?"0"+f.toString(16):f.toString(16);c.css({borderColor:"#000",filter:"progid:DXImageTransform.Microsoft.gradient(startColorstr=#"+f+"000000,endColorstr=#"+f+"000000)"})}b.settings.showAlbumsButton&&1<b.albums.length&&(f=d('<a href="#" style="float:left;"></a>'),f.css({display:"block",cssFloat:"left",margin:"0 2px",width:16,height:16,background:"no-repeat center",backgroundImage:v(p.images.folder+"zen-albums.png"),opacity:0.8}),f.click(function(){b.showAlbums();return!1}),c.append(f));b.settings.showThumbnailsButton&&
(f=d('<a href="#" style="float:left;"></a>'),f.css({display:"block",cssFloat:"left",margin:"0 2px",width:16,height:16,background:"no-repeat center",backgroundImage:v(p.images.folder+"zen-thumbnails.png"),opacity:0.8}),f.click(function(){b.showThumbnails();return!1}),c.append(f));b.canvas.element.append(c)}var b=this;if("never"!=b.settings.showButtons.toLowerCase()&&(b.settings.showAlbumsButton||b.settings.showThumbnailsButton))b.canvas.element.find(".altgallery-buttons").size()||a()};x.prototype.hideButtons=
function(){this.canvas.element.find(".altgallery-buttons").remove()};x.prototype.showCaption=function(){this.hideCaption();if("never"!=this.settings.showCaption.toLowerCase()&&(this.getCurrentAlbum()&&this.getCurrentAlbum().description||this.getCurrentItem()&&this.getCurrentItem().description)){var a=d('<div class="altgallery-caption"></div>');a.css({position:"absolute",left:this.settings.frameSize,top:25+this.settings.frameSize,padding:"4px 10px 5px 7px",color:"#fff",textShadow:"-1px 1px 0 rgba(0, 0, 0, 0.3)",
background:"rgba(0, 0, 0, "+this.settings.captionBackgroundAlpha/100+")",border:"1px solid rgba(0, 0, 0, 0.8)",borderLeft:"none","-moz-border-top-right-radius":"3px","-moz-border-bottom-right-radius":"3px","-webkit-border-top-right-radius":"3px","-webkit-border-bottom-right-radius":"3px","border-top-right-radius":"3px","border-bottom-right-radius":"3px"});if(d.browser.msie&&9>d.browser.version){var b=Math.round(255*parseInt(this.settings.captionBackgroundAlpha)/100),b=16>b?"0"+b.toString(16):b.toString(16);
a.css({borderColor:"#000",filter:"progid:DXImageTransform.Microsoft.gradient(startColorstr=#"+b+"000000,endColorstr=#"+b+"000000)"})}this.getCurrentAlbum().description&&a.append('<div style="font-weight:bold;">'+this.getCurrentAlbum().description+"</div>");this.getCurrentItem().description&&a.append('<div style="">'+this.getCurrentItem().description+"</div>");this.canvas.element.append(a)}};x.prototype.hideCaption=function(){this.canvas.element.find(".altgallery-caption").remove()};x.prototype.showNavigation=
function(){function a(){var c=d('<div class="altgallery-navigation"></div>');c.css({position:"absolute",right:b.settings.frameSize,bottom:25+b.settings.frameSize,padding:"3px 3px 3px 1px",background:"rgba(0, 0, 0, "+b.settings.buttonsBackgroundAlpha/100+")",border:"1px solid rgba(0, 0, 0, 0.8)",borderRight:"none","-moz-border-top-left-radius":"3px","-moz-border-bottom-left-radius":"3px","-webkit-border-top-left-radius":"3px","-webkit-border-bottom-left-radius":"3px","border-top-left-radius":"3px",
"border-bottom-left-radius":"3px"});if(d.browser.msie&&9>d.browser.version){var f=Math.round(255*parseInt(b.settings.buttonsBackgroundAlpha)/100),f=16>f?"0"+f.toString(16):f.toString(16);c.css({borderColor:"#000",filter:"progid:DXImageTransform.Microsoft.gradient(startColorstr=#"+f+"000000,endColorstr=#"+f+"000000)"})}b.settings.showNavigationButton&&(f=d('<a href="#" style="float:left;"></a>'),f.css({display:"block",cssFloat:"left",margin:"0 2px",width:16,height:16,background:"no-repeat center",
backgroundImage:v(p.images.folder+"zen-prev.png"),opacity:0.8}),f.click(function(){b.prev();return!1}),c.append(f),f=d('<a href="#" style="float:left;"></a>'),f.css({display:"block",cssFloat:"left",margin:"0 2px",width:16,height:16,background:"no-repeat center",backgroundImage:v(p.images.folder+"zen-next.png"),opacity:0.8}),f.click(function(){b.next();return!1}),c.append(f));b.canvas.element.append(c)}var b=this;"never"!=b.settings.showButtons.toLowerCase()&&b.settings.showNavigationButton&&(b.canvas.element.find(".altgallery-navigation").size()||
a())};x.prototype.hideNavigation=function(){this.canvas.element.find(".altgallery-navigation").remove()};x.prototype.open=function(a){var b=this,c=this.canvas,e=this.settings;b.hideAlbums();b.hideThumbnails();b.showButtons();b.showCaption();b.showNavigation();c.element.find(".altgallery-image img").hide();var h=c.element.find(".altgallery-imageFrame"),j=d('<img class="altgallery-preloader" src="'+p.images.loader+'" alt="" />');D(j);j.css({position:"absolute",left:"50%",top:"50%",zIndex:10,margin:"-16px 0 0 -16px"});
g(a.source,function(d){j.hide();c.element.find(".altgallery-preloader").remove();var g=c.element.find(".altgallery-image img");"fit"==e.imageScaleMode?g.css(z.fit(d.width,d.height,c.width()-2*e.frameSize,c.height()-2*e.frameSize)):g.css(z.fill(d.width,d.height,c.width()-2*e.frameSize,c.height()-2*e.frameSize));g.attr("src",a.source).fadeIn(2*p.animation.duration);b.cache()});setTimeout(function(){c.element.find(".altgallery-preloader").remove();h.append(j)},500)};x.prototype.prev=function(){0<this.currentItem?
this.currentItem--:this.currentItem=this.getCurrentAlbum().items.length-1;this.open(this.getCurrentItem())};x.prototype.next=function(){this.currentItem<this.getCurrentAlbum().items.length-1?this.currentItem++:this.currentItem=0;this.open(this.getCurrentItem())};var p={};d.fn.altgallery=function(a,b){function c(){e.each(function(){W(this,a,b)})}var e=this,a=d.extend(!0,{width:"550px",height:"400px",background:"none",images:{folder:S+"img/",left:"left.png",right:"right.png",close:"close.png",loader:"loader.png"},
animation:{duration:500},config:{settings:{}}},a);if(a.images.folder){a.images.folder=a.images.folder.replace(/\/+$/,"")+"/";for(var g in a.images)"folder"!=g&&!a.images[g].match("/")&&(a.images[g]=a.images.folder+a.images[g])}if("string"==typeof a.config){e.css({visibility:"hidden"});var h={load:function(a,b,d){if(b!==t)switch(b.toLowerCase()){case "xml":this.loadXML(a,d);break;default:case "json":this.loadJSON(a,d)}else a.match(/(xml)$/i)?this.loadXML(a,d):this.loadJSON(a,d)},loadJSON:function(a,
b){d.ajax({url:a,dataType:"json",success:function(a){a=h.parse(a);"function"==typeof b&&b(a)},error:function(){"function"==typeof b&&b({})}})},loadXML:function(a,b){function c(a){var b;"undefined"==typeof b&&(b=function(){});b.ObjTree=function(){return this};b.ObjTree.prototype.attr_prefix="";b.ObjTree.prototype.parseDOM=function(a){if(a){this.__force_array={};if(this.force_array)for(var b=0;b<this.force_array.length;b++)this.__force_array[this.force_array[b]]=1;b=this.parseElement(a);this.__force_array[a.nodeName]&&
(b=[b]);if(11!=a.nodeType){var d={};d[a.nodeName]=b;b=d}return b}};b.ObjTree.prototype.parseElement=function(a){if(7!=a.nodeType){if(3==a.nodeType||4==a.nodeType)return null==a.nodeValue.match(/[^\x00-\x20]/)?void 0:a.nodeValue;var b,d={};if(a.attributes&&a.attributes.length){b={};for(var c=0;c<a.attributes.length;c++){var e=a.attributes[c].nodeName;if("string"==typeof e){var f=a.attributes[c].nodeValue;f&&(e=this.attr_prefix+e,"undefined"==typeof d[e]&&(d[e]=0),d[e]++,this.addNode(b,e,d[e],f))}}}if(a.childNodes&&
a.childNodes.length){e=!0;b&&(e=!1);for(c=0;c<a.childNodes.length&&e;c++)f=a.childNodes[c].nodeType,3==f||4==f||(e=!1);if(e){b||(b="");for(c=0;c<a.childNodes.length;c++)b+=a.childNodes[c].nodeValue}else{b||(b={});for(c=0;c<a.childNodes.length;c++)if(e=a.childNodes[c].nodeName,"string"==typeof e&&(f=this.parseElement(a.childNodes[c])))"undefined"==typeof d[e]&&(d[e]=0),d[e]++,this.addNode(b,e,d[e],f)}}return b}};b.ObjTree.prototype.addNode=function(a,b,d,c){this.__force_array[b]?(1==d&&(a[b]=[]),a[b][a[b].length]=
c):1==d?a[b]=c:2==d?a[b]=[a[b],c]:a[b][a[b].length]=c};b=new b.ObjTree;b.attr_prefix="";return b.parseDOM(a)["#document"]}d.ajax({url:a,dataType:"xml",success:function(a){a=c(a);a=h.parse(a);"function"==typeof b&&b(a)},error:function(){"function"==typeof b&&b({})}})},parse:function(a){if(a.gallery){if(a.galleryName)a.gallery.galleryName=a.galleryName;a=a.gallery;if(a.items&&a.items.item)a.items=a.items.item.length?a.items.item:[a.items.item];if(a.albums){if(a.albums.album)a.albums=a.albums.album.length?
a.albums.album:[a.albums.album];for(var b=0;b<a.albums.length;b++)if(a.albums[b].items.item)a.albums[b].items=a.albums[b].items.item.length?a.albums[b].items.item:[a.albums[b].items.item]}}return a}};h.load(a.config,a.configType,function(b){e.css({visibility:"visible"});a.config=b;c()})}else c();return this};d.altbox=function(a,b){if(c!=top)var c=top,e=c.document;b=d.extend(!0,{frame:{color:"#000",borderRadius:0},mask:{color:"#000",opacity:0.7},images:{folder:S+"img/",close:"close.png",loader:"loader.gif"},
animation:{duration:700}},b);if(b.images.folder){b.images.folder=b.images.folder.replace(/\/+$/,"")+"/";for(var g in b.images)"folder"!=g&&!b.images[g].match("/")&&(b.images[g]=b.images.folder+b.images[g])}var h=d('<div style="position:fixed; z-index:999; left:0; top:0; width:100%; height:100%; background:no-repeat center;"></div>');h.css({opacity:0,backgroundColor:b.mask.color,backgroundImage:v(b.images.loader)});d(e.body).append(h);h.animate({opacity:b.mask.opacity},b.animation.duration);var i=
new Image;i.onload=function(){function g(){h.remove();q.remove()}var j=d(c).width()-100,p=d(c).height()-100,n=z.fit(i.width/4,i.height/4,j,p,{noEnlarge:!0,minWidth:100,minHeight:100});n.left+=50;n.top+=50;var o=z.fit(i.width+20,i.height+20,j,p,{noEnlarge:!0,minWidth:120,minHeight:120});o.left+=50;o.top+=50;var q=d('<div style="position:fixed; z-index:1000;"></div>');q.css(n);q.css({backgroundColor:b.frame.color,borderRadius:b.frame.borderRadius,MozUserSelect:"none",webkitUserSelect:"none",userSelect:"none"});
q.hide();var r=d('<img src="'+a+'" alt="" style="display:block;" />');r.css({margin:"10px",width:n.width-20,height:n.height-20,borderRadius:8<b.frame.borderRadius?b.frame.borderRadius-8:0});var t=d('<a href="#" style="display:block; position:absolute; right:-12px; top:-10px; width:30px; height:30px; background:no-repeat center;"></a>');t.css({backgroundImage:v(b.images.close)});q.append(r);d(e.body).append(q);(function(){h.css({backgroundImage:"none"});r.animate({width:o.width-20,height:o.height-
20,margin:"10px"},b.animation.duration,"easeOutBack");o.opacity="show";q.animate(o,b.animation.duration,"easeOutBack",function(){q.append(t)})})();d(c).resize(function(){j=d(c).width()-100;p=d(c).height()-100;n=z.fit(i.width/4,i.height/4,j,p,{noEnlarge:!0,minWidth:100,minHeight:100});n.left+=50;n.top+=50;o=z.fit(i.width+20,i.height+20,j,p,{noEnlarge:!0,minWidth:120,minHeight:120});o.left+=50;o.top+=50;q.css(o);r.css({width:o.width-20,height:o.height-20})});h.click(g);t.click(function(){t.remove();
n.opacity="hide";q.animate(n,0.67*b.animation.duration);r.animate({width:n.width-20,height:n.height-20},0.67*b.animation.duration);h.fadeOut(b.animation.duration,function(){g()});return!1})};i.src=a}})(jQuery);
